### ISSUE TITLE
Request: "switch between hotbar items" be moved to Right controller

### ISSUE THREAD

**Issue by rogueqd** [jrbudda/minecrift#10]
Not a bug, but since attack and place block are on the right controller, could the "Swipe touchpad - switch between hotbar items" gesture be moved there too? It would feel more natural.
Unless it's on the Left controller to stop you swiping accidentally?

**Comment by jrbudda** [comment]
Yea I thought about that, i think you'd accidentally switch too often, plus the hotbar itself is on that hand.

**Comment by jrbudda** [comment]
eh what the hell its one line of code. Here give it a shot.

[minecrift-1.7.10-R2b-Vive-jrbudda9-installer-rctrl.exe.zip](https://github.com/jrbudda/minecrift/files/287554/minecrift-1.7.10-R2b-Vive-jrbudda9-installer-rctrl.exe.zip)

**Comment by rogueqd** [comment]
Thanks. I tried it and I'm a bit 50/50. If you're looking at your right hand as your scrolling it works well, but as soon as you look at the hotbar/inventory on your left hand it gets confusing.
I thought about moving the inventory to your right hand, but then you'd have to use your left hand to move things around inside it.
Easier just to leave things how they were in the first place. Thanks for letting me try it out for myself.

**Comment by jrbudda** [comment]
Thank you for the feedback. reverted the change.
