### ISSUE TITLE
Contributing tips for Integration to Latest MC versions

### ISSUE THREAD

**Issue by Xrave** [jrbudda/minecrift#100]
I'm interested in starting a moonshot to update to a recent stable of MC, but I'm not sure where to start, where would you guys recommend to be the best approach to begin? There must've been tons of changes since 1.7.10, and the original Minecrift is currently somewhat inactive on all branches (with jrbudda's being the only actively contributed-to fork.

**Comment by jrbudda** [comment]
There's a issue already open about this topic, and we've talked about it a bunch. Beyond that your best bet is to come to the discord channel listed on the server listing wiki on reddit and talk about it.

**Comment by Xrave** [comment]
Ah great. Thanks for the info :)
