### ISSUE TITLE
Changing transportation crashes game.

### ISSUE THREAD

**Issue by eighthourblink** [jrbudda/minecrift#102]
First off, Thank you for your support and advancement of ViveCraft. For about a year now, i have been playing Minecraft in VR ( Oculus Dk2) but some mods wouldnt show some of the UI. It was being cropped out. Loaded up V20, and its in the game now. You have no idea how thrill i am to play this all over again. 

[ISSUE]
So teleporting around has never be ideal for me, it almost breaks the immersion, so i was happy to see that they was a better way to move around. The constant moving doesnt make me sick like it does with others. And switching between both modes (right CRTL+ T) seems to work in previous versions. But for some odd reason, it either locks up the game or automatically goes back to teleport mode. It goes from False to True back to False and so on.

 I have a video of it in action if you want to see it.

**Comment by OscarHalse** [comment]
have you tried holding the grip button for 4 seconds?

**Comment by jrbudda** [comment]
Are you playing multiplayer?

**Comment by jrbudda** [comment]
still happening?
