### ISSUE TITLE
[Discussion] Mixed Reality Third Controller

### ISSUE THREAD

**Issue by nightfiree** [jrbudda/minecrift#104]
Hey guys just saw this video and did a little research.  

https://www.youtube.com/watch?v=IPTazOkOLRw

It looks to me like this isnt something i can download on my end and add in, but rather something that would go into the project itself? idk. 

https://steamcommunity.com/app/358720/discussions/0/405694031549662100/

Basically it seems that you can use a third controller to generate a camera in unity.

**Comment by giltwist** [comment]
Minecraft isn't made in unity, though.

**Comment by Techjar** [comment]
I think this could possibly be implemented in the future by using different values for the far and near Z of the view frustum, which is probably how other games are doing it. However, it would probably be really terrible on performance due to rendering the game scene 4 or 5 times.

**Comment by nightfiree** [comment]
Yep was thinking the same thing.  Shortly realized you need to also render the foreground seperatley.  AR is hard :(

**Comment by Techjar** [comment]
Oh, of course! We don't have to redraw the whole scene 2 or 3 times for the third person view. We can simply draw it once, then use the depth buffer to mask and copy that framebuffer into different viewports with the "foreground" and "background" layers. Way faster than redrawing the game scene several times with different view frustums.

**Comment by jrbudda** [comment]
Thread is old, for more specfic things about MR mode make new thread.
