### ISSUE TITLE
Changing Stereo Rendering setting to monoscopic caused issues

### ISSUE THREAD

**Issue by Snowblxnd** [jrbudda/minecrift#105]
As the title says, I changed the rendering mode to monoscopic.
When starting the game, the monitor shows the main menu room for a split second and then goes black. The controller models are still visible.

The Vive displays only the Vive area, not the game display.

**I fixed the issue by renaming "optionsviveprofiles.txt" and letting the game create a new one upon launch.**

**Comment by Snowblxnd** [comment]
[optionsviveprofiles1.txt](https://github.com/jrbudda/minecrift/files/322525/optionsviveprofiles1.txt)

I tried spotting any differences between this file and the replacement but didn't see any. I'm guessing that since the one file was missing it may have replaced all of the configuration files.

**Comment by jrbudda** [comment]
this is slightly fixed but not really, the mono renderer is only there as a fallback if openVR doesnt load. It's not meant to be playable.
