### ISSUE TITLE
Forge Mod Keybinding not triggering?

### ISSUE THREAD

**Issue by ExcaliburVT** [jrbudda/minecrift#106]
Probably related to:
https://github.com/jrbudda/minecrift/issues/11

I tried installing journeymap, which does work but so far i'm forced to go to the keyboard and hit "j" to get it to come up with the full map.  I did try the keybindings and there does appear to be an option for the journeymap toggle, but for whatever reason it doesn't appear to work (or I have something screwed up).

Taken from optionsviveprofiles.txt:

"BUTTON_LEFT_TOUCHPAD_BL": "key.journeymap.map_toggle",
 "BUTTON_LEFT_TOUCHPAD_BR": "key.journeymap.minimap_preset",

-Thank you for all your hard and WONDERFUL work!

**Comment by missionfloyd** [comment]
I'm getting this as well, with mapwriter and waila (haven't tried binding others yet.) Both work, but binding them to the controller does nothing

**Comment by jrbudda** [comment]
This should be fixed in 21
