### ISSUE TITLE
The R-grip doesn't change on Vive supported server

### ISSUE THREAD

**Issue by TaiyangTamago** [jrbudda/minecrift#107]
First, thanks for working on this great plugin-- it's super addicting and can't wait to see what you guys throw into it next. 

I wanted to mention an issue I had connecting to a friend's Thermos-run FTB Infinity server; as of v20 the R-grip mode change won't work despite his use of the plug-in. I figured that was what was intended by the recent change, but his server allows teleport so... kind of problematic? Thanks

**Comment by jrbudda** [comment]
latest version doesn't prevent you from switching, just warns you.

**Comment by TaiyangTamago** [comment]
Actually, it was straight up not letting me switch, warning or not warning. But I got it working, the problem was a result of me using the Curse launcher directory (loaded through the vanilla launcher). Curse probably does something weird with their folder management, the method to launch works just fine with my FTB launcher directory.

Hopefully when final revisions of this mod are made, FTB, Technic, etc, will straight up add support VR in their mods.
