### ISSUE TITLE
[Wishlist] Hotkey to place torch

### ISSUE THREAD

**Issue by ExcaliburVT** [jrbudda/minecrift#108]
Any chance that you can have a keybind option to place a torch (assuming you have one somewhere in your toolbar?)  This was a feature that was in the early minecrift for vive that I played and it made life so much easier than having to flip back and forth on the toolbar every time I moved forward digging in a tunnel.

**Comment by OscarHalse** [comment]
Ditto

**Comment by jrbudda** [comment]
Fine. You've beaten me down.

**Comment by jrbudda** [comment]
take it and get out.
