### ISSUE TITLE
[Question] Is Optifine built in/required?

### ISSUE THREAD

**Issue by CoreyHyde** [jrbudda/minecrift#109]
I've recently been working on an Iron Farm on my Vivecraft server. However, I found out (once I finished) that Optifine breaks it because of how it unloads spawn chunks. Is Optifine built in to Vivecraft, and if not, is there a way to remove it? It's okay for me to run Optifine client-side, but server side is breaking the farm.

**Comment by fucnknown** [comment]
Optifine is required for the increse in FPS it brings, which it's crucial for using it in a VR headset. 
I would recommend a simple chunck loader mod (ChickenChunks for example), heck the FTB utilities mod offers a free chunkloader, if you don't want to "pay" for it.

**Comment by jrbudda** [comment]
Optifine and Vivecraft are more intertwined than an anaconda orgy.
