### ISSUE TITLE
Request bind controller buttons to different keys on forge version

### ISSUE THREAD

**Issue by pfgithub** [jrbudda/minecrift#11]
On forge, you usually need keys, and that currently means you have to walk over to your keyboard to press them all the time. Something like binding the left grip to sneak and right grip to backtick, or having the right touchpad be used to press keys

**Comment by jrbudda** [comment]
This is gonna be tricky, minecraft has no built in support for controllers or anything other than keybouard/mouse, binding a key to the controller buttons might wind up being easier in something like Joy2Key.

Also may look into beign able to pass raw keys to MC via the openvr keyboard

**Comment by fucnknown** [comment]
What about the 13 extra button keys available to minecraft regarding the mouse. http://minecraft.gamepedia.com/Key_codes under Mouse Keys. Also:    F11 to F19 and KANA / KANJI

**Comment by jrbudda** [comment]
Most mods are hard-coded to react to a specific keyboard key code

**Comment by pfgithub** [comment]
java.awt.Robot to simulate keypresses?

on grip down, keyPress() and on grip up, keyRelease

**Comment by fucnknown** [comment]
If I'm not mistaken Forge compatible mods declare keypresses that get assigned a default value, which can be changed in the configuration options. It's bad form programming a Forge mod that has a hardcoded value. I think that If you direct keypresses from ViveControls to those Keycodes they could be assigned to functions in the Forge provided options..

**Comment by jrbudda** [comment]
Done!
