### ISSUE TITLE
Can't dismount horse

### ISSUE THREAD

**Issue by rogueqd** [jrbudda/minecrift#12]
I found a saddle and thought I'd really test my motion sickness by riding a horse around.
Now I can't dismount. Can the lower half of the right trackpad be dismount if you're on a horse?
Also when you're on a horse the movement goes back to headset direction rather than controller direction, could the controller steer the horse so you can still look around while riding?

To assist here's a seed with HEAPS of horses. There's a temple close by which has a saddle in it's chest.
seed: -8397261408588314269

**Comment by jrbudda** [comment]
the left grip is sneak/dismount, does that not work?

**Comment by rogueqd** [comment]
Ahh, I forgot to try the grips. I'll test when I get home, in 5-6 hours.

**Comment by rogueqd** [comment]
Sorry, forgot to close this. Left grip worked to dismount.
