### ISSUE TITLE
Failed: Couldn't setup Vivecraft...

### ISSUE THREAD

**Issue by namico2000** [jrbudda/minecrift#122]
Issue when installing:
Failed: couldn't setup Vivecraft 1.7.10 as library. Have you run 1.7.10 at least once yet? Error: unexpected end of ZLIB input stream.

I've tried a clean install of Minecraft and different versions of Vivecraft (and of course run MC 1.7.10 at least once, haha). Any ideas would be appreciated!

**Comment by jrbudda** [comment]
the installer is looking for the normal 1.7.10 .jar file for minecraft and it's either missing or corrupt. It does try to download it too so many the download is failing.

**Comment by xXjordzaXx** [comment]
Hi, I have the same issue with the latest build. Only version that worked for me was the one used for vive + forge for the FTB server. Possible to put the .jar file elsewhere so it finds it or any other ideas?

Edit: It worked once, now even that file doesn't work. Tried re-installing multiple times, same error.

**Comment by xXjordzaXx** [comment]
Maybe Java related. I uninstalled all java, reinstalled 32 and 64bit and then tried again, flawless. Might help you OP.

**Comment by namico2000** [comment]
I've tried a new 1.7.10 jar, but haven't had any luck yet. Is it looking for the jar in the normal "versions/1..7.10" path?

I also tried unist/reinstalling Java, but it didn't fix it for me. 

Thanks for the replys!

**Comment by xXjordzaXx** [comment]
Not sure if this will help, here is what I did.

1) Uninstalled Minecraft, all Java versions and curse & forge (if you have it)

2) Cleaned with CCleaner normally and registry fix (run a few times)

2.5) I ran registry editor and searched for Minecraft, vivecraft and deleted all entries containing it 

3) rebooted and what not

4) installed Minecraft again and 32 + 64 bit Java

5) Reboot

6) tried the vivecraft install again

In between 5-6 I did install FTB mods but shouldn't be required I would imagine

**Comment by xXjordzaXx** [comment]
Also disabled firewall as well before all of the steps. Good luck!

Edit: Just remembered that I also deleted all Minecraft folders like the one in appdata/roaming and the installation folder

**Comment by jrbudda** [comment]
Minecraft/vivecraft doesn't do anything to the registry so that and ccleaner should not be needed at all. Deleting your .minecraft folder and reinstalling with the launcher is all that's needed to start from scratch. I can't speak for what the curse or FTB launchers do, though.
