### ISSUE TITLE
Installer not running

### ISSUE THREAD

**Issue by mgriffin1994** [jrbudda/minecrift#123]
The installer, when run, opens up the UAC prompt, and then fails to run after clicking yes. I've even temporarily disabled Windows Defender to see if it saw it as malware but it didn't help. Minecraft is installed, has been run, has been uninstalled and reinstalled, and then run yet again.

Manually building the installer also doesn't work. Running install.bat works fine, but then build.bat fails after "Creating Installer exe..." and "Invoking launch4j..." with a "Error occurred during initialization of VM, NoClassDefFoundError: java/lang/Object" error. JDK 1.8 is installed and added to the PATH environment variable.

**Comment by jrbudda** [comment]
certainly sounds like something is wrong with your Java installation.
