### ISSUE TITLE
Right trackpad UL and UR click acts like BL and BR button even if rebound

### ISSUE THREAD

**Issue by pmcthor777** [jrbudda/minecrift#125]
The right trackpad UL and UR click doesn't bind at all. Acts like the right trackpad BL and BR click.

**Comment by jrbudda** [comment]
Cannot reproduce, I just tried binding hotbar slot 1,2,3,4 to the R_touchpad and all 4 work as expected. Could you try resetting your button mapping to default and set them up again?

**Comment by jrbudda** [comment]
This is likely related to another issue that we solved with science. If you click the verrry edge of the touchpad steam doesnt register your thumb location (reads 0,0) At 0.0 it triggers the bottom-right button.

Changing future version to not press any button at all at 0,0
