### ISSUE TITLE
[Forge Mod] keyboard doesn't come up in Not Enough Items mod textbox

### ISSUE THREAD

**Issue by pmcthor777** [jrbudda/minecrift#126]
the Steam keyboard doesn't pop up when clicking on the Not Enough Items textbox within the inventory. Steam keyboard works fine with JourneyMap menu and other textboxes.

**Comment by jrbudda** [comment]
If the NEI textbox doesn't inherit from the base Minecraft GuiTextBox it won't. You'll have to open the keyboard with the controller combo (left_grip+appmenu)

**Comment by pmcthor777** [comment]
thanks for the info. I did also try to bring up the keyboard using that combo, but nothing happens. I did rebind the left grip to "hotbar slot 1". Would that make a difference?

**Comment by jrbudda** [comment]
ahh sorry it is specifically the sneak button and left app menu... I guess that should be hard coded to the grip button.

**Comment by jrbudda** [comment]
v23 should always be grip+appmenu if you rebind sneak.
