### ISSUE TITLE
V22 Cannot cook food in furnace?

### ISSUE THREAD

**Issue by wildstyle007** [jrbudda/minecrift#128]
As the title says, cannot cook any food, however can cook materials such as sand to glass.

Checked another world / save game and same thing happens.

**Comment by jrbudda** [comment]
Cant reproduce. Just cooked some chicken. Forge or vanilla? single or multi-player?

**Comment by wildstyle007** [comment]
Forge single player... I have chomahills texture pack installed, but nothing else. Thanks for looking into this issue.

**Comment by jrbudda** [comment]
Do you get the same withing without forge?

**Comment by wildstyle007** [comment]
I'll test further today and let you know. I've been playing most of your previous builds with no problem. Just changed to forge on this latest

**Comment by wildstyle007** [comment]
I deleted all profile and did a clean install, then it started working correctly again... pretty strange.

Closing this issue... thanks!
