### ISSUE TITLE
[Forge Mod] Thermal Expansion Crosshair Missing

### ISSUE THREAD

**Issue by TauAkiou** [jrbudda/minecrift#129]
When I open the inventory of any kind of Thermal Expansion block or machine, I cannot see the crosshair, making it very difficult to navigate within those machines. Clicks still work and items will still highlight. Picking up an item causes it to become invisible on screen.

Steps To Reproduce: Occurs whenever a Thermal Expansion machine window is open.
Version: v22

**Comment by asaf400** [comment]
+1, I've noticed the issue in v20 as well,
Came by to submit a report, good thing I've check the list :)

Some mod info:
Latest Forge 1.7.10 and Latest Optifine 1.7.10 D4 [NOT THE D1 INCLUDED],
Latest Thermal Expansion.

**Comment by kuar-z** [comment]
Issue occurs with Minefactory Reloaded as well so possibly something in CoFHCore buggering things up.

**Comment by jrbudda** [comment]
I tired to fix this I really did. He's doing his own thing with the cursor position and I can't fix this without a super-invasive bunch of reflection.

**Comment by KingLemming** [comment]
Alright, so now at least I know the root cause, sort of. Why are you modifying the vanilla GUI exactly?

**Comment by jrbudda** [comment]
I'm revisiting this now, a lot has changed in the past months, I think I have a fix for it.
