### ISSUE TITLE
Breaking a block, all nearby blocks disapear for 1-2 seconds

### ISSUE THREAD

**Issue by vivegamer** [jrbudda/minecrift#13]
I'm on the latest version,  1.7.10_R2b_jrbudda9.  I didn't have this issue on the one I installed over.  Not sure what that one was.

Let me know if I can provide more details.

**Comment by Tyrindor** [comment]
Turn off all multicore settings in optifine. Those settings always cause similar issues even in non-VR minecraft.

**Comment by fucnknown** [comment]
They work fine, as long as, **everytime**, you start the game you disable and re-enable them, known issue with it

**Comment by rogueqd** [comment]
Since this is an issue with Optifine, not Vivecraft, can we close it?
