### ISSUE TITLE
[Forge Mod] DragonAPI crashes game

### ISSUE THREAD

**Issue by pgrosslicht** [jrbudda/minecrift#132]
Hi,

when DragonAPI[1](https://sites.google.com/site/reikasminecraft/dragonapi) is installed, the game crashes instantly, here is the corresponding log of just Vivecraft with Forge and DragonAPI V15a: https://gist.github.com/pdgwien/d9bc36e3bfc1edbbedeaaec1a8b686b5

Thanks in advance!

**Comment by jrbudda** [comment]
Thank you, known incompatibility, should list that somewhere.

**Comment by Techjar** [comment]
Yeah this is because of a ClassCircularityError in the Vivecraft detection Reika added to disable certain patches. It's been fixed in his code, so we'll see what happens in the next release.

**Comment by Techjar** [comment]
Fixed in latest DragonAPI builds, the fix will be included in the v15b release of DragonAPI.

**Comment by Techjar** [comment]
Leaving open until Reika actually releases v15b.

**Comment by Techjar** [comment]
This may not really matter much anyways. See issue #168
