### ISSUE TITLE
v23r1 - Unable to Split stacks/Items can be "used" from inventory screen.

### ISSUE THREAD

**Issue by kuar-z** [jrbudda/minecrift#135]
Right touchpad no longer splits stacks from inventory screens, instead the held item is used like normal behavior outside of inventory.

Issue is only present when Minecraft window has focus.

**Comment by ExcaliburVT** [comment]
I have this too

**Comment by Valadon** [comment]
+1 for me as well. I can no longer split stacks with the right touchpad.

**Comment by Techjar** [comment]
That's odd, it should be working fine. Will test.
