### ISSUE TITLE
[SP, Forge] Ghosting issues with swing attack

### ISSUE THREAD

**Issue by DoctorPCfin** [jrbudda/minecrift#136]
When breaking blocks that only requires one swing to break, the block ghosts.

**Comment by jrbudda** [comment]
See if this affects the behavior
[vivecraft-1.7.10-Vivecraft-jrbudda23r1-installer.zip](https://github.com/jrbudda/minecrift/files/334004/vivecraft-1.7.10-Vivecraft-jrbudda23r1-installer.zip)

**Comment by DoctorPCfin** [comment]
It does not :/

**Comment by jrbudda** [comment]
huh. I was testing it with torches like you said and was not able to get them to ghost. I guess I'll have to try harder.

**Comment by DoctorPCfin** [comment]
Oh, sorry!
With torches, it now works - brilliant :dancers: 
What I was testing with was stone shovel + dirt block (not grass, dirt.)
With that, it does not work.

**Comment by jrbudda** [comment]
So it's fixed for only torches????? what.....

**Comment by DoctorPCfin** [comment]
yes. This wasn't a block specific change you made? xD
Perhaps it is something to do with the fact that torches are broken with one hit by anything, while dirt needs to be broken with a shovel. If I smack the dirt block into pieces with, say, a stick or a pickaxe, it works fine.

**Comment by jrbudda** [comment]
no it was certainly not a block specific change i made, lol. You're likely on to something there tool related.

**Comment by DoctorPCfin** [comment]
Let's hope you can find a fix for it soon. The stick has a terrible reach >.<

**Comment by jrbudda** [comment]
[vivecraft-1.7.10-Vivecraft-jrbudda23r1-installer (2).zip](https://github.com/jrbudda/minecrift/files/335146/vivecraft-1.7.10-Vivecraft-jrbudda23r1-installer.2.zip)

try dis. only thing is for me at least im getting a render bug. I think the server dislikes the idea of a survival player destroying normal blocks in one click. not sure i can fix without nerfing the swing attack to always need minimum of 2 swings

**Comment by DoctorPCfin** [comment]
Yep, it works. Frankly, I don't think there is much of a point in one swing - destroy blocks. 
I mean, it does make me feel manly as f**\* when I can use a tiny spade to shovel up a cubic metre of dirt up, but it doesn't feel quite right.

Somewhat related (well, not really), after playing around with the world scale I realised that 1x made me feel like a midget, and 1,5x a giant. So, I wonder, if the correct world scale is calculable from the height of the player. Perhaps the correct world scale is 2/P, where p is the height of the player in metres.

If this is true, you could probably set some nifty world scale configurator based on player height, either inputted manually or even better, a system similar to what they have in Hover Junkers.
Correct scaling would really help with immersion and really put you in the boots of Steve. Sure, you could add a manual multiplier afterwards in case you want to either get that really cool 20x view of the world or check out what an ant would see in your virtual kitchen :P

**Comment by jrbudda** [comment]
I think I'll just add some granularity to the slider

**Comment by DoctorPCfin** [comment]
That would work too. You could also add that "2/your height in metres" trick to the tooltip.

**Comment by jrbudda** [comment]
technically at 1.0 scale blocks are exactly the size they're supposed to be at 1 meter.

**Comment by jrbudda** [comment]
OK after looking at it I have no way to tell how many hits its going to take for it to break, so we will have to live with the rendering glitch for the foreseeable future
