### ISSUE TITLE
Black-out screen during teleport to prevent motion sickness

### ISSUE THREAD

**Issue by lukexi** [jrbudda/minecrift#137]
I have a friend who's extremely sensitive to vection, where even the tiny teleport transition in Vivecraft takes him out of commission for hours after about 3 minutes of play : ). So it would be great to have an option to black out the screen during the move. (He has no problem with teleportation in e.g. The Lab.)

(Instantaneous teleportation would be great too but I think I understood from the options screen that the "animated" movement is there for multiplayer compatibility?)

OpenVR's fadeToColor is a super easy way to do this
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1987

Incredible work on the mod : )))

**Comment by Techjar** [comment]
The short "transition" happens due to interpolation of the renderViewEntity. I guess we could add an option to just blank the screen during the interpolation, but it can't be a fade since we have no real control over it's speed and it's only 5 frames.

**Comment by jrbudda** [comment]
The dash thing is actually now gone in 25.
