### ISSUE TITLE
Failed to initialize stereo rendering plugin: OpenVR

### ISSUE THREAD

**Issue by jkluch** [jrbudda/minecrift#14]
I tried installing this mod and haven't been able to get it to work, I tried installing, and had issues so I deleted my .minecraft folder, reran my launcher to build up the .minecraft folder, closed the launcher, ran the installer with just the first check box checked and still had the problem.  I'm seeing this upon launch and I'm not sure why.
![image](https://cloud.githubusercontent.com/assets/514150/15631384/0dc391aa-2536-11e6-8637-39d4a7d2d9b9.png)

Pastebin of my game output: http://pastebin.com/ZVBsNJK7

**Comment by jrbudda** [comment]
It's not finding your Vive headset plugged in.

**Comment by jkluch** [comment]
Hmm, not sure why that is.  I found out running minecraft as admin fixes the problem.
