### ISSUE TITLE
[Suggestion] Option to move where headset is facing

### ISSUE THREAD

**Issue by Mckaos** [jrbudda/minecrift#141]
(me again sorry i did see your last reply to my thread asking to move without teleporting) Now that i've figured out the free-move feature, i would like to suggest the option to move where my head is facing, instead of where my controller is facing.

**Comment by jrbudda** [comment]
right_control + M switches to that mode. I'm not entirely sure it still works, no one really uses it.

**Comment by Mckaos** [comment]
Oh thank you!

**Comment by Mckaos** [comment]
Oh thank you! So do you mean CTRL + M?

**Comment by jrbudda** [comment]
specifically right control

**Comment by jrbudda** [comment]
(i dunno why its like that)

**Comment by Mckaos** [comment]
oh ok
