### ISSUE TITLE
Control vibration in FTB standing on Minicio plants

### ISSUE THREAD

**Issue by GroxicTinch** [jrbudda/minecrift#144]
I'm not sure how its implemented, to vibrate on certain sounds or events but I have noticed that it happens when villagers close doors and stuff and while standing on Minicio plants, I'm fine with the vibrations normally but if I'm trying to harvest Minicio plants then the controllers are vibrating constantly until I get off which is a little annoying.

This isn't really an issue as such and more of a annoyance but if it could be fixed without breaking other things that would be great :)

Edit(trying to reply without bugging you with a message): Thank you Techjar for applying a label, not sure how to do it myself since I'm a gitpleb, or if I even can.

**Comment by jrbudda** [comment]
I removed the door closing haptics in 25, see if that fixes it.

**Comment by kuar-z** [comment]
Still broken with v25. For the record: no noticeable sound associated with the haptic feedback.

**Comment by GroxicTinch** [comment]
If it helps at all Minicio has enchanting table particles coming out of it but like Kuar-z said, no noticeable sound.

**Comment by jrbudda** [comment]
Ok every time a haptic pulse trigger it's going to dump the code path to your console. It's gonna be a lot of spam. See if you can grab one of the dumps when you're on the plant and paste it here so I can see how we're triggering a pulse.

[vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.exe.zip](https://github.com/jrbudda/minecrift/files/341023/vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.exe.zip)

**Comment by kuar-z** [comment]
I think its trimmed to the important bits
http://pastebin.com/sBjVKjsA

**Comment by jrbudda** [comment]
at net.minecraft.client.entity.EntityClientPlayerMP.func_70097_a(EntityClientPlayerMP.java:124)
at com.mark719.magicalcrops.blocks.BlockMagicalCrops.func_149670_a(BlockMagicalCrops.java:56)

func_70097_a is attackEntityFrom... the plants are attacking you.... weird

**Comment by GroxicTinch** [comment]
I just tried standing in Minicio while in singleplayer and not in VR and it actually hurts you like you were standing on cactus which means that it attacking you makes sense. Im not sure if maybe the server owner has disabled them hurting players or if it is another mod or plugin that is preventing the damage so I dont think it is a problem with the Vivecraft mod, it must still be calling the damage player function maybe with a 0 damage which still causes the haptic feedback.

**Comment by jrbudda** [comment]
exactly so. I had a reason for not filtering out 0 damage attacks but I cannot remember why.

This has it filtered out.

[vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.zip](https://github.com/jrbudda/minecrift/files/341897/vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.zip)

**Comment by GroxicTinch** [comment]
I tried the new version you linked and it didn't work so I played around with some settings and apparently it was because the Minicio was set to hurt me in clientside config but the server had disabled it hurting players, I am not sure why disabling 0 damage from vibrating didnt work but maybe it was because the client was trying to hurt me for half a heart but every time it did then the server told the client nothing happened so it ignored it. Anyway disabling the harm in my own config solved the problem and I am not sure how or if you could solve this.

On an unrelated note where would be the best place to suggest\request features?

**Comment by jrbudda** [comment]
Good to know and I guess it's not something I can fix, it should vibrate on non-zero damage on the client. Suggestions just open another github issue.
