### ISSUE TITLE
[Forge Mod] Tinker's Construct Tools/Weapons Misaligned

### ISSUE THREAD

**Issue by TaiyangTamago** [jrbudda/minecrift#145]
This is both a bug and a request, really, both dealing with tinker's construct tools/weapons. 

The bug: tinkers mod tools and weapons appear misaligned when I am holding them, probably a result of how the mod does it's custom tiles (which is probably a lot, given all the modifications a tool can have). The request: can you apply the same touch mechanics to the tinker's tools (and probably any other tool/weapon mod) that the vanilla tools already have? I'd love to see what happens when I take a hammer to a tile and see everything around it smash. 

It probably also applies to other tools/weapon mods, but I haven't been messing with those yet. I just love me some auto-regen and haste...

**Comment by Techjar** [comment]
Apply these effects to mod items is kind of messy, since we'd have to reflectively check for all the item types.

**Comment by TaiyangTamago** [comment]
That makes sense; I imagine each mod handles these things slightly differently, too, so it'd end up being too messy. You guys should only worry about the visual glitch-- it's weird having these things floating in front of you (and I wonder if any other mod has this problem?) 

As for adding support similar to vanilla's tools, it's probably more reasonable (and perhaps more legal?) for mod developers to create supplement Vive mods that can complement existing modpacks (I'm looking at you, FTB). I imagine if it was done this way, one could apply your magical Vive code to different item IDs, which may vary by modpack but could be installed within instances (e.g. FTB Infinity support mod). Just an idea, though, I'm no programmer. I just wish I could help in some way-- you guys are pros.

**Comment by TaiyangTamago** [comment]
Btw, this is the same issue as Item Flip (#101), it seems to be specific to Tinker's Construct. His video shows the same weird floating item issue I see.

**Comment by Techjar** [comment]
Ah, yes, you're right. This is indeed the same as #101.
