### ISSUE TITLE
Forge support in new Minecraft version

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#147]
This is just a milestone issue related to #96

**Comment by jrbudda** [comment]
I think once I have the code changes nicely blocked out so they can be injected into 1.10 the same could be done directly into Forge. I really really really don't want to get into reflection again. We'll just distribute 2 separate jars in the installer, one with a vanilla base and one with a Forge base.

**Comment by Techjar** [comment]
Yeah this reflection and reimplementation stuff is a pain in the ass. That honestly sounds like a better idea.

**Comment by jrbudda** [comment]
will reopen in 1.10 tracker.
