### ISSUE TITLE
Blocks break extremely slowly

### ISSUE THREAD

**Issue by edcarroll** [jrbudda/minecrift#149]
Hi, had this problem for a while now, where blocks take a long time to break using the trigger, even with tools.

Happens in both SP & MP, on v19 -> v24, using Windows 10 x64, running without Forge.

Thanks in advance!!

**Comment by Techjar** [comment]
Do you mean they take the same time to break as with wooden tools even if you're using diamond tools?

**Comment by edcarroll** [comment]
Relatively the tools still increase the speed according to their type, but the base block breaking rate is much slower meaning all of the tools take longer

**Comment by Techjar** [comment]
What? That doesn't make any sense. You don't have mining fatigue or something do you? Is this a vanilla or modded install? If modded, please try it on vanilla.

**Comment by edcarroll** [comment]
I don't have any status effects, nor any mods installed. Tried deleting the .minecraft folder and completely reinstalling to no avail :(

**Comment by Techjar** [comment]
I don't know what to say to that. It doesn't happen on any of my instances, so I have absolutely no idea. I can't fix something that isn't apparently broken.

**Comment by edcarroll** [comment]
This is also why I am so confused that it happens, as I cannot find anything related to it anywhere on the internet :/ are there any more steps I can take in terms of reinstalling minecraft - is deleting the .minecraft folder in %AppData% enough to delete everything?

**Comment by edcarroll** [comment]
I have just reinstalled one more time, and I can confirm the bug is still an issue. When creating a new world everything is the correct speed, yet when reloading it a few times later it is slow, then remains slow. I have videoed the game exhibiting this behaviour (please excuse the low quality, I couldn't find a decent screen recorder in a pinch).

Here is the video: [Vivecraft bug](https://drive.google.com/file/d/0B4rMBxspIDoBRVdJZ1RoNXRSeUk/view?usp=sharing)

**Comment by Techjar** [comment]
Looks like the slower block breaking that occurs when your player isn't in the "onGround" state.

**Comment by edcarroll** [comment]
What determines the onGround state? as it doesn't get faster when I return to the ground

**Comment by jrbudda** [comment]
ooooooooooh. onground...... interesting! does changing into Free Move mode make it speed back up?

**Comment by edcarroll** [comment]
Just tested, turning free move on immediately solves the issue, and putting tp mode back on starts it up again!

**Comment by jrbudda** [comment]
ah ha! progress! Do you have 'Simulate Falling' on or off in the locomotion options?

**Comment by edcarroll** [comment]
I have simulate falling off :) thank you both for the help getting this sorted!

**Comment by jrbudda** [comment]
and i assume turning simulate falling on fixes it in TP mode?

**Comment by edcarroll** [comment]
I unfortunately cannot test this now until tomorrow, but given that it sorts itself in free move mode it makes sense that it would work with simulate falling on

**Comment by jrbudda** [comment]
assume nothing! It's actually a very different code path. Well, not very, but different.

**Comment by edcarroll** [comment]
Ah ok. Will test tomorrow morning and get back to you! :)

**Comment by jrbudda** [comment]
Try your version first, for science, and then try this version.

[vivecraft-1.7.10-Vivecraft-jrbudda24-installer.exe.zip](https://github.com/jrbudda/minecrift/files/336198/vivecraft-1.7.10-Vivecraft-jrbudda24-installer.exe.zip)

**Comment by edcarroll** [comment]
Just tested, with original version turning simulate falling on fixes the breaking speed issue, however the version you provided doesn't fix the issue without simulate falling on sadly.

**Comment by jrbudda** [comment]
o rly

**Comment by edcarroll** [comment]
Yup, just double checked and I am still having the problem with the provided version :/

**Comment by jrbudda** [comment]
Ive been trying and I cant seem to get myself off the ground in tp mode without being able to jump. Could you maybe describe a repeatable series of steps to get it into slow mode? thanks.

**Comment by edcarroll** [comment]
It's slightly low quality but the video attached earlier shows how I make it happen.

Essentially:
- Create a new survival world
- Login to the world, break some blocks, teleport around a bit
- Logout of the world
- Login again and try destroying blocks
- Relog until it is slow (this has never taken more than 2 total relogs for me)

**Comment by jrbudda** [comment]
oooh ok, didnt try the relogging thing, that may be the key

**Comment by jrbudda** [comment]
hmmm stillll nothing, trying with vanilla and single player, logging in and out on ground and while in the 'air' after breaking the blocks below me... haven't gotten the not-on-ground to trigger yet, or slow breaking at all..

**Comment by edcarroll** [comment]
Hmm how peculiar! Would you like a copy of my .minecraft folder?

**Comment by jrbudda** [comment]
Lets just be double sure I didn't fix it and screw up the build I gave you to test. Try this, make sure the minecraft launcher isnt running when you install it.  (i should have changed the version number, ugh)

[vivecraft-1.7.10-Vivecraft-jrbudda24-installer (2).zip](https://github.com/jrbudda/minecrift/files/337488/vivecraft-1.7.10-Vivecraft-jrbudda24-installer.2.zip)

**Comment by edcarroll** [comment]
Happy to report that you have indeed fixed it, as the newest bundle works perfectly. Thanks!!

**Comment by jrbudda** [comment]
dangit i didnt change anything, oh well, case closed!

**Comment by edcarroll** [comment]
You didn't change anything from the current released version to the one you just gave me?

**Comment by jrbudda** [comment]
no from the one i gave you yesterday to this one

**Comment by edcarroll** [comment]
Ahh okay that makes sense. Thanks again for the help :)
