### ISSUE TITLE
World Freezes With Right Trigger - Poll Error

### ISSUE THREAD

**Issue by LaZZer010** [jrbudda/minecrift#15]
When using the inventory, clicking with the right trigger causes the world to stop moving. So, when you move your head the world doesn't move. Causes instant motion sickness. 

In the menus, buttons can be pushed, but other items cannot be interacted with. 
For example, on the main menu the button 'Single Player' works fine. I can click and interact with it. But then on the 'Select World' menu I cannot choose any world. The buttons on the bottom work fine, I can make a new world, but I cannot click on a world to load an existing one.

**Upon pressing or holding the right trigger, this is spammed in the 'Game Output' window:**
_Plugin com.mtbs3d.minecrift.provider.MCOpenVR@2e013ba1 poll error java.lang.IndexOutOfBoundsException_

Using the latest version: 1.7.10_R2b_jrbudda9

Some other things I tried
_Same results with Steam beta client, and normal client. 
All vive firmware is up to date. 
Deleted everything Minecraft and downloaded it fresh.
Same results with 1.7.10_r2b_jrbudda8
Tried different versions of JRE and JDK._ 

**Using version 1.7.10_R2b-vive-nohydra produces this crash as soon as the right trigger is pressed**

Description: Unexpected error

java.lang.IndexOutOfBoundsException: 0
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:306)
    at com.mtbs3d.minecrift.provider.MCOpenVR.poll(MCOpenVR.java:435)
    at com.mtbs3d.minecrift.api.PluginManager.pollAll(PluginManager.java:222)
    at bao.ak(Minecraft.java:1446)
    at bao.f(Minecraft.java:1307)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 429280736 bytes (409 MB) / 511856640 bytes (488 MB) up to 8536260608 bytes (8140 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: minecrift-1.7.10-R2b-Vive-jrbudda-nohydra
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 365.19
OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 12
```

*Side note; thank you so much for your work on minecraft!

**Comment by jrbudda** [comment]
Well that's a new one... is steamVR running? have you had any other controller oddities?

**Comment by LaZZer010** [comment]
Yes, steamvr is running. Haven't had any other controller issues. 

Taking a wild guess, it's almost as if minecraft isn't seeing my mouse. So, might actually be a separate issue from VR altogether.

**Comment by LaZZer010** [comment]
Yeah, that was it. I plugged in another mouse and it's working great now. Minecraft didn't pick up my mouse so it didn't know what to do with the vive controller. 

Anyway, thanks for reading the bug report. Thank you for all your work on this project!

**Comment by jrbudda** [comment]
That's... super weird, i'm not sure how i could go about trying to reproduce that... hmm
