### ISSUE TITLE
Can't set a proper scale after update 24

### ISSUE THREAD

**Issue by RichWP** [jrbudda/minecrift#151]
I can't seem to get the right size after the update - it's either too big or too small when by default, and when I try the scaling options

**Comment by jrbudda** [comment]
Could you elaborate on what exactly is either too big or too small by default?

**Comment by RichWP** [comment]
Sorry - that was really vague...  Not sure if it makes a difference or not, but I'm over 6 feet tall.  I used to be able to comfortably fit in a space that was two blocks tall at 1.0 scaling - now I need to bend over to fit, since I'm about now over two blocks tall.  The next available notch down on scaling is .5 - where I appear too small (maybe just a little over a block tall).  Hope this helps, and thanks for all your hard work - very cool.

**Comment by jrbudda** [comment]
thats interesting, you actually should still be shorter than 2 blocks. I will look into that. Also I've gotten several requests for more granularity to the worldscale slider between 0.5 and 1.5. So look for that in the future too.

**Comment by Techjar** [comment]
Well, 2 blocks is 2 meters, which is 6.56 feet. How tall are you exactly?

**Comment by jrbudda** [comment]
did we shrink the world? it shouldnt have changed in any case

**Comment by jrbudda** [comment]
Ok I just played a bit, I'm about 5'10'' and a 2 block hallway feels almost exactly 8 inches above my head which is right where it's supposed to be.

**Comment by RichWP** [comment]
hmmm...  Okay - I don't think that I changed anything between release 23 and 24, but I'll try it again.  I will also recalibrate my Vive.  I will update this thread tonight with the results.  I am 6' 2" tall.  
In any case, more granularity on the world scale slider would be great.

**Comment by jrbudda** [comment]
see how this works for ya

[vivecraft-1.7.10-Vivecraft-jrbudda24-installer (3).zip](https://github.com/jrbudda/minecrift/files/337664/vivecraft-1.7.10-Vivecraft-jrbudda24-installer.3.zip)

**Comment by RichWP** [comment]
What took so long?!?!?!?   ;-) 
I got a break from my job, and gave it a whirl - it works great...  Thanks.  My scaling issues are gone, and I can now scale to 90%, etc.  Impressive!  
Just donated the other day - will send some more beer money your way soon.
