### ISSUE TITLE
[Wishlist] Creation of a Sitting mode

### ISSUE THREAD

**Issue by jakdax99rb** [jrbudda/minecrift#154]
I would really love to have a sit down mode where I just use the vive for freelook and use the mouse and keyboard to play.

**Comment by CodeKartonka** [comment]
My Controller are on Repair :-) would be nice to play a while with mouse

**Comment by jrbudda** [comment]
IVIrEos recommends the following button setup for seated play

Left_Touchpad_UL : Jump
Left_Touchpad_UR : Jump
Left_Touchpad_BL : Hotbar Prev
Left_Touchpad_BR : Hotbar Next
Left_Grip : Quick Torch
Right_Trigger : Sneak
Right_Trigger_FullClick : Attack/Destroy
Right_AppMenu : Inventory
Right_Touchpad_BL : Rotate Left / Rotate Free / Walkabout (Choose one)
Right_Touchpad_BR : Rotate Right / Rotate Free / Walkabout
Right_Grip : Hotbar Slot 1 (Put your sword here)

**Comment by jrbudda** [comment]
v28 adds seated mode.
