### ISSUE TITLE
release25R1 CRUSH before  mc crash-reports generrate

### ISSUE THREAD

**Issue by wenxiao2012** [jrbudda/minecrift#161]
usingTLauncher， befor r24 everything is ok.
With release25R1 patched， game crushed before  mc crash-reports generrate.

here is Tlauncher error log:http://pastebin.com/ja1iXDRr

**Comment by Techjar** [comment]
A quick Google search shows that this "Tlauncher" is used to play pirated copies, therefore I assume you are using a pirated copy of the game. This is not supported, buy the game or you're on your own.

**Comment by wenxiao2012** [comment]
Ok, I will try the offical launcher. 
I used this launcher because someone tells me that launcher is more compatible with your mod, not because of I used a pirated copy.
