### ISSUE TITLE
Crash using Oculus DK2 and Razer Hydra

### ISSUE THREAD

**Issue by juliopx** [jrbudda/minecrift#162]
java.lang.IllegalArgumentException: Allocation size must be greater than zero
    at com.sun.jna.Memory.<init>(Memory.java:102)
    at com.mtbs3d.minecrift.provider.OpenVRStereoRenderer.getRenderTextureSizes(OpenVRStereoRenderer.java:61)

I run it through SteamVR to be able to use the Razer Hydra.

http://pastebin.com/a5ypdpAu

**Comment by Techjar** [comment]
Uh... I thought we disabled Hydra support? Can you clarify exactly what you're doing? Is this on the latest version?

**Comment by jrbudda** [comment]
Send me an oculus and I will be happy to make it compatible.

**Comment by juliopx** [comment]
I reported it in case it was something obvious, like the SteamVR driver reporting a recommended size of zero, or something like that.

**Comment by Techjar** [comment]
Ah, I see. You've connected a DK2 and Hydras to SteamVR. Yeah, I was wondering if that would work. I guess not. It seems that SteamVR is reporting a resolution of 0 to us or something. Not sure what's going on there.

**Comment by jrbudda** [comment]
actually the oculus doesn't provide eye stencils, is what it is.

**Comment by jrbudda** [comment]
try this for giggles, might fix the crash but you're gonna halve issues elsewhere, hydra support has been removed and I have no idea what other differences there are in how Oculus responds to openvr.

[vivecraft-1.7.10-Vivecraft-jrbudda26-installer.zip](https://github.com/jrbudda/minecrift/files/343368/vivecraft-1.7.10-Vivecraft-jrbudda26-installer.zip)

**Comment by juliopx** [comment]
Thanks!
I tried to disable  "stencilOn" in the config and it doesn't work.

I'm going to try your build now.

**Comment by Techjar** [comment]
Yeah, that didn't work because it doesn't stop it from trying to load the stencil. In theory, if we fix these weird crashes that come up, it should just work since the Hydra controllers are just remapped to Vive controllers in OpenVR.

**Comment by juliopx** [comment]
Great! It works.

Thank you guys!

**Comment by Techjar** [comment]
Huh... so it was that easy? Seems suspicious. Well let us know if you have any other issues and we'll see if we can fix them!
