### ISSUE TITLE
Jumping Stopped working V25 (Default binds) Cause: 'Simulate falling' option

### ISSUE THREAD

**Issue by asaf400** [jrbudda/minecrift#163]
Since v25, While thumb is 100% on the lower part of the touchpad, Clicking it, yields no results,
Jumping does not seem to occur, although the upper part (Inventory) Does work.

I've tried remapping to a different key and rebinding to default key (manually) but that did not work as well.

**Comment by jrbudda** [comment]
simulate falling turned off?

**Comment by asaf400** [comment]
Testing now 'simulate falling', on both V25 & unreleased V26 (Compiled from sources)

**Comment by asaf400** [comment]
Yep, Works now..
Simulate falling was turned off, I've upgraded from V20\21 Directly to V25, And I belive that was a new feature, which I didn't bother to check out, expected the default value to be on, since ladders and waterfalls before this feature didn't 'Simulate falling', but jumping did..

I did Tested World Scale, It's so awesome :)

**Comment by jrbudda** [comment]
simulate falling has been around since the beginning, i may have changed the default but that shouldnt have affected an existing profile. 

Also world scale will soon go up to 100 :)

**Comment by asaf400** [comment]
By the way, I've figured out why suddenly for me Simulate falling was turned off, even though it was on before:

I've accidentally deleted all of my %appdata% folder couple days ago, Fortunately I've restored everything from backup, but my minecraft installation was not included in that backup..

**Comment by Techjar** [comment]
Well hopefully you don't mind if I ask: how does one _accidentally_ delete the AppData folder?

**Comment by asaf400** [comment]
I was Shooting for deleting the content of %temp% Folder, but %appdata% was in the Win+R List as well, and I didn't check which folder I've opened, and so CTRL+A, Shift+Del happened ;)

I use a program which fills up the %temp% folder quickly by design during use, so after I finish using it i clean it manually.
I've since made a symbolic link for the temp folder, to relocate it to another bigger drive :)
