### ISSUE TITLE
Single Player/Forge Enabled/Options Menu - Crash to desktop

### ISSUE THREAD

**Issue by ScholarNZL** [jrbudda/minecrift#165]
Hi there,
As above. When changing KeyBindings in the options menu, a crash to desktop occurs when scrolling down past a certain point.

Very low priority, as keybinding for me isn't a priority, but worth logging anyhow.

> ---- Minecraft Crash Report ----
> // Oops.
> 
> Time: 7/4/16 3:24 PM
> Description: Rendering screen
> 
> java.lang.ArrayIndexOutOfBoundsException: 999
>     at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
>     at net.minecraft.client.settings.GameSettings.func_74298_c(GameSettings.java:377)
>     at net.minecraft.client.gui.GuiKeyBindingList$KeyEntry.func_148279_a(SourceFile:109)
>     at net.minecraft.client.gui.GuiListExtended.func_148126_a(SourceFile:26)
>     at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:514)
>     at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:381)
>     at net.minecraft.client.gui.GuiControls.func_73863_a(SourceFile:107)
>     at net.minecraft.client.renderer.EntityRenderer.drawFramebuffer(EntityRenderer.java:3621)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1484)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1341)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:79)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>     at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
>     at net.minecraft.client.settings.GameSettings.func_74298_c(GameSettings.java:377)
>     at net.minecraft.client.gui.GuiKeyBindingList$KeyEntry.func_148279_a(SourceFile:109)
>     at net.minecraft.client.gui.GuiListExtended.func_148126_a(SourceFile:26)
>     at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:514)
>     at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:381)
>     at net.minecraft.client.gui.GuiControls.func_73863_a(SourceFile:107)
> 
> -- Screen render details --
> Details:
>     Screen name: net.minecraft.client.gui.GuiControls
>     Mouse location: Scaled: (353, 125). Absolute: (1060, 342)
>     Screen size: Scaled: (427, 240). Absolute: (1280, 720). Scale factor of 3
> Stacktrace:
>     at net.minecraft.client.renderer.EntityRenderer.drawFramebuffer(EntityRenderer.java:3621)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1484)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1341)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:79)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 247791904 bytes (236 MB) / 466874368 bytes (445 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 3 mods loaded, 3 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda26-forge-shadersmod
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 20
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 368.39
OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by Techjar** [comment]
This was a typo in the code and has already been fixed. The fix will be included in the next release.

**Comment by jrbudda** [comment]
leave open til release so people see it and dont duplicate

**Comment by jrbudda** [comment]
released
