### ISSUE TITLE
Botania + matmos mods not working

### ISSUE THREAD

**Issue by Dung3onlord** [jrbudda/minecrift#166]
Matmos worked before version 21.
I just tried to install botania and at startup i got an error. Here is the log file:

[expunged]

**Comment by Techjar** [comment]
Please repost the log on gist or pastebin or something, it was too long and got truncated in your post, and therefore was not useful.

**Comment by Dung3onlord** [comment]
here is the paste bin
[http://pastebin.com/hVeBspNH](http://pastebin.com/hVeBspNH)

And of course there was also the matmos issue. Should i open a new issue report?

**Comment by jrbudda** [comment]
There does not appear to be a crash in this log

**Comment by Dung3onlord** [comment]
apologies apparently baubles was missing you can close the issue
