### ISSUE TITLE
Game stuck at Mod Phase 3

### ISSUE THREAD

**Issue by ToffelsKater** [jrbudda/minecrift#167]
HI.
when i start Vivecraft with forge and Shader the game stuck at Mod Phase 3 (Loading the mods)
and the game is flickering the hell out of my screen (NOT IN THE VIVE)
and it's not playable.

**ViveCraft v26**
JVM: -Xmx14G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true

[log.txt](https://github.com/jrbudda/minecrift/files/347575/ghi.txt)
![ghi](https://cloud.githubusercontent.com/assets/20298637/16582576/ff78dcda-42af-11e6-9b6f-f47a31b200a7.PNG)

**WINDOWS 10 64bit
CORE i74770K
GEFORCE GTX 980
16GB DDR3 RAM**

**Comment by Techjar** [comment]
The flickering is normal when the game crashes during launch. The error is coming from the Logistics Pipes tick handler. Does it launch fine on a normal (non-Vivecraft) Forge client?

**Comment by ToffelsKater** [comment]
Yes without vivecraft forge is loading fine

**Comment by Techjar** [comment]
Okay, will look into this later.

**Comment by ToffelsKater** [comment]
i saw some vivecraft error message at the end of the log at line 958

**Comment by Techjar** [comment]
That's irrelevant. The crash is happening because the LP tick handler is throwing an exception. I'll take a quick glance at the code and see if I notice anything super obvious.

**Comment by ToffelsKater** [comment]
ok Thank you

**Comment by Techjar** [comment]
I need you to post the full log, this appears to be only a partial log and missing relevant information.

**Comment by Techjar** [comment]
Also stop starting your JVM with 14GB of memory, that is completely unnecessary. 4GB or so will do just fine.

**Comment by ToffelsKater** [comment]
[expunged due to included session ID]
i hope this is the log you want
ok and i'll use 4 GB RAM

**Comment by Techjar** [comment]
This appears to be completely the wrong log. fml-client-latest.log is the one you're looking for

**Comment by ToffelsKater** [comment]
hmmm log file is too big mom

**Comment by Techjar** [comment]
What do you mean it's too big? Just upload it here.

**Comment by ToffelsKater** [comment]
it's bigger then 10MB github dont allow files bigger then 10MB?

**Comment by ToffelsKater** [comment]
http://workupload.com/file/Ba3mrNw

**Comment by Techjar** [comment]
Oh, wasn't aware they set a size limit. You could have just zipped it up.

**Comment by ToffelsKater** [comment]
[fml-client-latest.zip](https://github.com/jrbudda/minecrift/files/347648/fml-client-latest.zip)

**Comment by Techjar** [comment]
java.io.FileNotFoundException: C:\Users\Damien PC\AppData\Roaming.minecraft\config\WirelessRedstone.cfg (The process cannot access the file because it is being used by another process)

You may have dead client processes running in the background, open task manager and kill any and all java.exe or javaw.exe processes that are running.

**Comment by ToffelsKater** [comment]
I'll try this one

**Comment by ToffelsKater** [comment]
OK tanks it's working. maybe i have to close the minecraft launcher after i start the game? i did that

**Comment by Techjar** [comment]
You probably had your client crash at some point and it got stuck in the background. Well glad it's fixed now.
