### ISSUE TITLE
Chromahills cursor occludes objects

### ISSUE THREAD

**Issue by mnmean** [jrbudda/minecrift#17]
When using Chromahills (128 or 64) graphics pack, the cursor is a solid black square (with a + in the middle). This occludes objects and makes it hard or impossible to see what item I'm holding while crafting.

**Comment by jrbudda** [comment]
Yea Ive seen that too. Does it do that with normal optifine do you know?

**Comment by Tyrindor** [comment]
https://www.reddit.com/r/Vive/comments/4ll45o/is_a_big_black_box_hovering_behind_the/

**Comment by jrbudda** [comment]
fix incoming.
