### ISSUE TITLE
[Forge Mod] Item render issue in LOTR mod multiplayer

### ISSUE THREAD

**Issue by crains606** [jrbudda/minecrift#171]
Whenever I use Vivecraft with the LOTR mod, the game periodically crashes with the error below. I'm assuming it may be a Vivecraft issue because everything works as expected when I use a normal Forge profile.

> ---- Minecraft Crash Report ----
> // Oh - I know what I did wrong!
> Time: 7/4/16 5:14 PM
> Description: Rendering entity in world
> java.lang.NoSuchMethodError: net.minecraft.client.renderer.ItemRenderer.renderItem(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;ILnet/minecraftforge/client/IItemRenderer$ItemRenderType;)V
>     at lotr.client.render.entity.LOTRRenderInvasionSpawner.func_76986_a(LOTRRenderInvasionSpawner.java:36)
>     at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:309)
>     at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:287)
>     at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:260)
>     at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:727)
>     at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1745)
>     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1296)
>     at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:1652)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1523)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1341)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:79)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> Head --
> Stacktrace:
> at lotr.client.render.entity.LOTRRenderInvasionSpawner.func_76986_a(LOTRRenderInvasionSpawner.java:36)
> -- Entity being rendered 
>   --Details:
>     Entity Type: lotr.InvasionSpawner (lotr.common.entity.LOTREntityInvasionSpawner)
>     Entity ID: 265957
>     Entity Name: Invasion Spawner
>     Entity's Exact location: 46754.50, 73.00, -1577.50
>     Entity's Block location: 
>       World: (46754,73,-1578), 
>       Chunk: (at 2,4,6 in 2922,-99; contains blocks 46752,0,-1584 to 46767,255,-1569), 
>       Region: (91,-4; contains chunks 2912,-128 to 2943,-97, blocks 46592,0,-2048 to 47103,255,-1537)
>     Entity's Momentum: 0.00, 0.00, 0.00
> -- Renderer details 
>   --Details:
>     Assigned renderer: lotr.client.render.entity.LOTRRenderInvasionSpawner@48458cde
>     Location: 76.60,3.25,21.78 - 
>       World: (76,3,21), 
>       Chunk: (at 12,0,5 in 4,1; contains blocks 64,0,16 to 79,255,31), 
>       Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>     Rotation: 0.0
>     Delta: 0.09405899
> Stacktrace:
>   at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:309)
>   at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:287)
>   at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:260)
>   at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:727)
>   at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1745)
>   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1296)
> -- Affected level 
>   --Details:
>     Level name: MpServer
>     All players: 1 total; [EntityClientPlayerMP['crains2'/258637, l='MpServer', x=46677.90, y=69.75, z=-1599.28]]
>     Chunk stats: MultiplayerChunkCache: 166, 166
>     Level seed: 0
>     Level generator: ID 00 - default, ver 1. 
>     Features enabled: false
>     Level generator options: 
>       Level spawn location: 
>         World: (0,106,0), 
>         Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), 
>         Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>         Level time: 501485581 game time, 9362210 day time
>         Level dimension: 0
>         Level storage version: 0x00000 - Unknown?
>         Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> Level game mode: Game mode: survival (ID 0). 
> Hardcore: false.
> Cheats: false
> -- System Details 
>   --Details:
>         Minecraft Version: 1.7.10
>         Operating System: Windows 10 (amd64) version 10.0
>     Java Version: 1.8.0_25, Oracle Corporation
>     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>     Memory: 483848928 bytes (461 MB) / 1006907392 bytes (960 MB) up to 2120679424 bytes (2022 MB)
>     JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
>     AABB
>     Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>     FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 4 mods loaded, 4 mods active
>     States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>     UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
>     UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar)
>     UCHIJA  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
>     UCHIJA  lotr{Beta v28.2 for Minecraft 1.7.10} [The Lord of the Rings Mod]([1.7.10] The Lord of the Rings Mod B28.2.jar)
>     GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 780/PCIe/SSE2'
>     Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda26-forge
>     LWJGL: 2.9.1
>     OpenGL: GeForce GTX 780/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
>     GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
>     Is Modded: Definitely; Client brand changed to 'fml,forge'
>     Type: Client (map_client.txt)
>     Resource Packs: []
>     Current Language: English (US)
>     Profiler Position: N/A (disabled)
>     Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>     Anisotropic Filtering: On (16)

**Comment by Techjar** [comment]
This is due to a missing API method we can't implement due to missing references.

**Comment by crains606** [comment]
That was easy. Thanks for letting me know!

**Comment by Techjar** [comment]
Ugh. They're passing in the default value of ItemRenderType.EQUIPPED, so them calling this method is completely dumb and they could have just called the one without the ItemRenderType argument.

**Comment by crains606** [comment]
That sucks. So the only way to make this work would have to require a change on their side?

**Comment by Techjar** [comment]
Yeah since we can't easily implement that missing method, and there's no point in them calling it that way anyways. They don't seem to have a proper issue tracker and I'm not sure if I'd actually get anywhere posting on their forum topic.

**Comment by crains606** [comment]
The forum topic may work but I don't know if any developers still post in it. Their official wiki also has a forum with sections for technical issues and bug reports. There seems to be regular updates and answers there: http://lotrminecraftmod.wikia.com/wiki/Special:Forum

**Comment by jrbudda** [comment]
ASM!

**Comment by Techjar** [comment]
Into the mod? That seems silly...

**Comment by jrbudda** [comment]
nono add the method to itemrenderer

**Comment by Techjar** [comment]
Oh. Yeah I guess that could be done. I'll do it later, after I work out this other world rendering junk.

**Comment by crains606** [comment]
Nice. Thanks for looking into it!

**Comment by Techjar** [comment]
See if this build fixes the issue.

[vivecraft-1.7.10-Vivecraft-jrbudda26-test1-installer.exe](https://owncloud.techjargaming.com/index.php/s/kNZGUkwi9EdHK6I/raw)

**Comment by crains606** [comment]
That build doesn't seem to be working correctly with Forge. I haven't found anything in the logs yet but the main menu is just the vanilla menu, with no option to view mods.

**Comment by Techjar** [comment]
Yeah I noticed that too. It still seems to be loading Forge though, mods are working and all that.

**Comment by crains606** [comment]
When I enter the multiplayer server, the LOTR HUD doesn't show up with this build. So something is still off, since the HUD works completely fine with the previous build.

**Comment by Techjar** [comment]
Possibly related to our recent GUI fuckery.

**Comment by crains606** [comment]
Oh, I see. The custom menu that displays the LOTR map and stuff like that seems fine, but there's just zero HUD (no hotbar, LOTR compass, etc.)

**Comment by Techjar** [comment]
Yeah, we've changed the way it renders, look at the side of your left arm. It's a work in progress still. Also optional, check the options.

**Comment by crains606** [comment]
Oh, sweet. I see it now. I'm good then. Now I can test and make sure the ItemRenderer is working. Thanks!

**Comment by Techjar** [comment]
No problem. Will be glad if this fix actually works.

**Comment by crains606** [comment]
There's still an error related to ItemRenderer, but it's slightly different. Now it's a NoSuchField error:

---- Minecraft Crash Report ----
// Oops.

Time: 7/8/16 11:59 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: mc
    at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:72)
    at lotr.client.render.entity.LOTRRenderInvasionSpawner.func_76986_a(LOTRRenderInvasionSpawner.java:36)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:309)
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:287)
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:260)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:728)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1792)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1310)
    at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:1672)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1570)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Techjar** [comment]
I hate obfuscation.

**Comment by Techjar** [comment]
This is literally the biggest possible pain in the ass. It'll take me like an hour to fix that. Possibly multiple. Sorry.

**Comment by Techjar** [comment]
Maybe I can get away with just reobfuscating the field references, since Forge does runtime deobfuscation anyways so all the class names are correct.

**Comment by crains606** [comment]
It's no problem. I'm just glad it's getting looked into so deeply.

**Comment by crains606** [comment]
Just let me know when you want me to try out a new build.

**Comment by Techjar** [comment]
Whew, that was annoying. Try this build.

(oops)

**Comment by Techjar** [comment]
Messed up that build. Try this one instead.

[vivecraft-1.7.10-Vivecraft-jrbudda27-test1-installer.exe](https://owncloud.techjargaming.com/index.php/s/2FOPpjlDVKxF6UL/raw)

**Comment by crains606** [comment]
It works! No crashes anymore!

**Comment by crains606** [comment]
It probably doesn't belong with this issue but now a NullPointerException is being thrown when I try to bring up the mod achievements.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/9/16 12:29 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at lotr.client.gui.LOTRGuiAchievements.func_73863_a(LOTRGuiAchievements.java:107)
    at net.minecraft.client.renderer.EntityRenderer.drawFramebuffer(EntityRenderer.java:3839)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Techjar** [comment]
Oh fucking hell they're replacing the achievement gui

**Comment by Techjar** [comment]
I'll have to look into that one when I get home. Man this is a really
problematic mod.

**Comment by jrbudda** [comment]
also the background of icons on the hotbar is now transparent running with forge.

**Comment by Techjar** [comment]
Yeah the way I did the patch probably broke stuff. I have another idea in
mind which I'll try tonight.

**Comment by crains606** [comment]
After a couple of hours playtime with the mod, I've not run into any other issues that aren't GUI related. Thanks for making it playable!

**Comment by jrbudda** [comment]
note that I disabled the patch in 27 release, so for LOTR stick with your test version until we can sort out the UI transparency for the next release.

**Comment by crains606** [comment]
Oh yeah, I meant to ask about the new release. Thanks for letting me know.

**Comment by crains606** [comment]
I was mistaken. I'm now getting a different NoSuchMethod error:

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/9/16 5:50 PM
Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s(I)Z
    at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:132)
    at lotr.client.render.tileentity.LOTRRenderWeaponRack.func_147500_a(LOTRRenderWeaponRack.java:101)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:785)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1791)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1309)
    at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:1672)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1570)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jrbudda** [comment]
That's interesting, we don't modify ItemStack

**Comment by crains606** [comment]
Oh wow, that is interesting.

**Comment by Techjar** [comment]
No, it's nothing to do with ItemStack, it's my stupid patch. I'm gonna throw the current patch in the garbage and do it a different, easier way.

**Comment by Techjar** [comment]
Okay, try this one. See if it's completely fixed now.

[vivecraft-1.7.10-Vivecraft-jrbudda27-test2-installer.exe](https://owncloud.techjargaming.com/index.php/s/ZZ5ednpEECwoqsr/raw)

**Comment by crains606** [comment]
Everything looks good to me so far! No more NoSuchMethod errors and all of the menus are working. Thanks! I'll let you know if I run into anything else.
