### ISSUE TITLE
Feeding Animals And Other Interactions

### ISSUE THREAD

**Issue by knockout709** [jrbudda/minecrift#172]
So, i'm not sure if this is even possible. However, I think it would be extremely cool if you could, for example, hold seeds and if you gently bring the seeds to the chicken, it will eat them.

Doing this instead of using buttons would be great imo.

Also, this isn't something I've tried. But if this isn't implemented, could you do something similar where instead of hitting a button to fill a bucket, you would just put the bucket in the water/lava?

**Comment by Techjar** [comment]
I'm not sure how viable either of these features would be, so we'll see.

**Comment by fazo96** [comment]
well, the game could check wether the hand is clipping with a mod or block. If it's a liquid block and the hand holds an empty bucket it refills the bucket? And if it's clipping with a mod and the hand holds something the mod can eat it eats it?

Is this doable?

**Comment by jrbudda** [comment]
Depends on if the resulting action is determined by the server or client. I think it's client so this should be doable and pretty easy.

**Comment by knockout709** [comment]
Awesome.

**Comment by tobloef** [comment]
I'm all for more kinds of interaction, it greatly improves the feel of immersion :+1:

**Comment by jrbudda** [comment]
Already implemented, look for it in next release, great suggestion.

**Comment by jrbudda** [comment]
check out 27
