### ISSUE TITLE
Issue opening minecraft world in non-VR

### ISSUE THREAD

**Issue by klawuk** [jrbudda/minecrift#173]
Apologies if this isn't really the right place, but I figure its worth a try.

Using the latest release 26 I loaded up a previous save from an earlier vivecraft version, and made some changes. I then wanted to load it up in normal flat minecraft, but every time I try and load it, it crashes out with an error. I've set the profile up to use minecraft 1.7.10

Is vivecraft supposed to be compatible with normal minecraft if you're using the same version? 
# The start of the error report is pasted below - full report is attached as .txt file.

[vivecraft.txt](https://github.com/jrbudda/minecrift/files/350365/vivecraft.txt)

java.lang.NullPointerException: Rendering Block Entity
    at agq.a(SourceFile:110)
    at agq.h(SourceFile:236)
    at bmp.a(SourceFile:20)
    at bmp.a(SourceFile:15)
    at bmp.a(SourceFile:10)
    at bmk.a(SourceFile:100)
    at bmk.a(SourceFile:92)
    at bma.a(SourceFile:383)
    at blt.a(SourceFile:994)
    at blt.b(SourceFile:814)
    at bao.ak(SourceFile:801)
    at bao.f(SourceFile:728)
    at net.minecraft.client.main.Main.main(SourceFile:148)

Appreciate all the work you're doing on this - its an amazing way to play minecraft.

**Comment by jrbudda** [comment]
vivecraft makes no changes to the world, should be no reason you can't swap back and forth.

Umm does the world load if you go back to the vivecraft profile? It's vanilla vivecraft and not with Forge, right?

**Comment by klawuk** [comment]
Yes, world loads in vivecraft profile. It is vanilla but I did accidentally install update 26 with forge checked, but then I installed again with it unchecked, and thats the profile I used - vivecraft-ShadersMod 1.7.10 from the profile list

**Comment by Techjar** [comment]
It's the fucking mob spawners again.

**Comment by jrbudda** [comment]
oh, that thing I blindly put a try/catch around? is that a known 1.7.10 bug?

**Comment by Techjar** [comment]
MobSpawnerBaseLogic.spawnEntity()
MobSpawnerBaseLogic.getEntityToRender()
TileEntityMobSpawnerRenderer.func_147517_a()
TileEntityMobSpawnerRenderer.renderTileEntityAt()

**Comment by Techjar** [comment]
What the hell? This is wrapped in a try-catch. We're catching Throwable!

**Comment by Techjar** [comment]
Yeah I guess it's a known 1.7.10 bug or something, we fixed it but it obviously doesn't apply to a non-Vivecraft client, so nothing we can do there. Forge probably fixes it though, so you could use that without any mods on your vanilla client.

**Comment by jrbudda** [comment]
you also could open the world with mcedit and delete the offending mob spawner

**Comment by klawuk** [comment]
is it a particular type of mob spawner or mob spawners in general have an issue?

**Comment by klawuk** [comment]
ok doing a replace on mob spawners in mcedit fixed it. But does this mean I could have this problem any time I load up a mob spawner in the non-VR version?

**Comment by jrbudda** [comment]
I really don't know the source of the bug. It's just something I saw happen and fixed it on my end.
