### ISSUE TITLE
Matmos not working after v22

### ISSUE THREAD

**Issue by Dung3onlord** [jrbudda/minecrift#175]
So yesterday i was trying the matoos mod on all previous version of the vivecraft relase and realized that it stopped working after version 22.
Here are the mod files:
Here's liteloader - [http://www.liteloader.com/download#stable_1710](url) (download jar and choose to extract to .minecraft/mods)
Here's matmos for 1.7.10 - [https://minecraft.ha3.eu/relink/?file=matmos/bin/MAtmos_r28b__1_7_10__no_expansions.zip](url)
And finally, msi resource pack - [https://ha3.eu/x/tempshare/misc/msi_conversion.zip](url)

**Comment by Pixeldk** [comment]
Matmos is running fine on Brickrealms modpack.

**Comment by jrbudda** [comment]
fixed!
