### ISSUE TITLE
[Request] hotbar slots on your body/back

### ISSUE THREAD

**Issue by natebluehooves** [jrbudda/minecrift#176]
Hi guys! I was wondering if it'd be possible to set up hotbar shortcuts on your body. i.e. move your hand to your back and grab to pull your pickaxe off your back, etc. 

As for implementation, my idea (disclaimer: natey's ideas are stupid. do not base anything off these ideas) would be to essentially have the client just press the corresponding number key to a slot when the player reaches there, thus switching to that tool, and have the game switch to the previously used slot when you put your tool back (or if that's not possible, designate a hotbar slot as the "default" one when you put up your tools)

Yes i'm ripping off hotdogs horseshoes and hand grenades. sue me. <sup>Please don't sue me.</sup>

bonus points and a donation if however much change i happen to have in my pocket at the time if you guys can make it possible to grab items with the left hand and use them. (for slots on the right side etc. )

**Comment by jrbudda** [comment]
see response in #113 for the current direction of the hotbar. Something fancier might wait for 1.10.
