### ISSUE TITLE
Profiler [Shift+F3] crashes to launcher 

### ISSUE THREAD

**Issue by fucnknown** [jrbudda/minecrift#177]
Trying to research degraded performance in Forge+Vivecraft, I made a series of clean-installs and tried several versions, capturing information from the profiler each time. When I finally tried v26, it crashes when summoning it with Shift+F3. **Might** be related to #165 , don't know...

Log @ http://pastebin.com/dhJsDd1N //
Second attempt, everything triple checked: http://pastebin.com/waL1d0Zq

**Comment by jrbudda** [comment]
not related but also fixed shortly after 26 was released. Try this one. I think it's fixed in here and nothing else has been broken yet.

[vivecraft-1.7.10-Vivecraft-jrbudda26-installer.exe.zip](https://github.com/jrbudda/minecrift/files/354315/vivecraft-1.7.10-Vivecraft-jrbudda26-installer.exe.zip)

**Comment by fucnknown** [comment]
Nope, still crashing.
http://pastebin.com/Wjd8jMmp

**Comment by jrbudda** [comment]
interesting, how bout now
[vivecraft-1.7.10-Vivecraft-jrbudda27-installer.exe.zip](https://github.com/jrbudda/minecrift/files/355362/vivecraft-1.7.10-Vivecraft-jrbudda27-installer.exe.zip)

**Comment by fucnknown** [comment]
Excellent, working; Question, what does "Polling" refers to?
http://i.imgur.com/rQiCmB7.png

Have to say the new bar is an interesting project. But when it's enlarged it's very distracting and bothersome. It should be slightly smaller, and to be easily read it should be rotated 90º, meaning that when you watch the side of your hand, it should be readable straight away, without turning your hand around, similar to the way it's now.
Personally I would ask for the option to keep the current bar.

**Comment by Techjar** [comment]
"Poll" is, well, polling for new data from OpenVR. It also v-syncs to the HMD's refresh rate, so it spends a lot of time doing nothing.

There is an option to use the old GUI position.

**Comment by fucnknown** [comment]
That's what I thought... which makes it more aggravating since I get less than 90 fps... It could spend that time rendering dammit.

**Comment by Techjar** [comment]
What? I see 89 fps in that screenshot, which is really just an artifact in the counter, so it's 90.

**Comment by Techjar** [comment]
Also if you're under 90 you'll drop to 45 due to reprojection, so it will once again spend extra time in the polling stage. Don't turn reprojection off though, as non-multiple-of-refresh-rate frame rates are really terrible.

**Comment by fucnknown** [comment]
I'm using it without retroprojection, and it moves between 82 and 90, so there are tiny jumps occasionally, but it's much better than 45 and retroprojection which **really** messes me up

**Comment by Techjar** [comment]
Huh. For me non-reprojection is super janky and terrible. Not sure why you'd have 50% poll and not be getting 90fps. You may have something else weird going on.

**Comment by jrbudda** [comment]
fixed in 27
