### ISSUE TITLE
Rebinding Vive Controller buttons to F-keys doesn't work

### ISSUE THREAD

**Issue by Sleepydragn1** [jrbudda/minecrift#178]
Going to Settings > VR Settings > Controller Buttons... and rebinding any of the Vive Controller's buttons to a F-key (F3, F2, etc.) using keyboard(press) doesn't work. While the rebind menu seems to accept the F-key for rebinding (i.e. the little > < editing indicator in the menu goes away once the key has been pressed on the corresponding keyboard, and the key changes in the menu), it will not work in-game. Additionally, the small box that normally shows the rebound key is blank. Other keys that I've tried work, but F-keys do not (at least F3 and F2 don't, I haven't tried all of them). This is especially problematic for me, since I often use F3 to display my current coordinates to find others or allow others to find me in-game. Running back and forth between my computer to press the F3 key and my Vive room to get back in-game is rather tedious and irksome.

This bug is present both when the game is out of focus or in focus, in both single player and multiplayer, and in both the Forge and non-Forge versions of the mod.

**Comment by jrbudda** [comment]
I use F3 constantly and am kicking myself I never made it easier to press.

I looked at the button binding and actually storing an F key on the button is problematic as it means re-doing how the button bindings work and will break everyone's existing configs. 

I have a better solution tho. How bout a F3 button on the in-game menu? That way you don't lose a controller button to it, does that work?

**Comment by fucnknown** [comment]
Cool idea. One vote for that!

**Comment by jrbudda** [comment]
Check it out in v27

**Comment by Sleepydragn1** [comment]
The new menu option in v27 works wonderfully for me, great work. 

However, in a similar vein to the F3 overlay, there's currently no way to take screenshots in-game, at least as far as I know. Another menu button similar to the current "Overlay" button would fix that pretty easily, but it would have to be coded so that it closes the menu first, and then takes the screenshot.

Also, there's no feedback to tell the user that F-keys don't work within key bindings, which can be problematic. I know that when I first encountered this issue, I assumed that it was an issue on my own end, either with me pressing the wrong key on my keyboard, not having the game in focus, or not binding the correct button on the controller.

I've gone ahead and added an entry to the FAQ on the [Reddit wiki](https://www.reddit.com/r/Vive/wiki/vivecraft) (_Ctrl + F_ "Why can't I rebind a Vive controller button to an function key?") to hopefully alleviate some of that issue, but I imagine that some sort of feedback within the actual UI would also help. Perhaps the box that normally displays the rebound key could be changed to a "(X)", "NULL", "---" or something of the sort when the user attempts to rebind to an F key? I would've suggested leaving the box unchanged, but that wouldn't be very helpful if the user hadn't yet picked a key and the box was still blank.

**Comment by jrbudda** [comment]
Will fiddle with binding UI for feedback.
