### ISSUE TITLE
[Suggestion] Modifier keybinds or profile binds

### ISSUE THREAD

**Issue by GroxicTinch** [jrbudda/minecrift#182]
There is barely enough buttons on the vive controllers for regular minecraft let alone when you go into FTB, it would be awesome if we could bind for example LeftTouchPad_UL to change the keybinds of the right controller touchpad to one set of binds, then press LeftTouchPad_UR to swap out those keybinds for other keybinds.

For example
Default Binds:
    LeftTouch_UL=SetBindsTo(Alt)
    Right_UL=OpenInventory
    Right_UR=DropItem
    Right_DL=Rightclick
    Right_DR=Quicktorch

Alt Binds:
    LeftTouch_UL=SetBindsTo(Default)
    Right_UL=Slot1
    Right_UR=ListPlayers
    Right_DL=DoSomethingElseCool
    Right_DR=DoSomethingEquallyCool

That way people could possibly have all the options they need without having to open up keyboard to press the key.

I know this could be quite difficult to implement(Mostly just the gui and quickswapping the binds) but I feel that it could benefit those playing on the Vive.

**Comment by Techjar** [comment]
Not sure how easy it is to do this. The bindings are a bit of a mess.

**Comment by Aesop112** [comment]
That is like the steam controller, which has only the fly button activated profile switching, so basically you get a vast number of possible mappable buttons. I used it with steam controller for mmos a while back
