### ISSUE TITLE
[Minor Issue] Key bindings for mods lost when game is restarted

### ISSUE THREAD

**Issue by Niklars** [jrbudda/minecrift#184]
Some custom key bindings for mods (Xray for Forge as an example) is lost after the game is restarted.
It still show as correctly binded when I check the settings, but does not work. If I re-bind them again they work.

**Comment by Techjar** [comment]
The mod must be doing something dumb like caching the KeyBinding object on load.

**Comment by jrbudda** [comment]
Is this still a a thing?

**Comment by Niklars** [comment]
Ooh! I haven't tried in a while. Vacation is over :-(
I will see tonight. I wanted to try the latest update anyway.

// Niklas

2016-08-16 18:42 GMT+02:00 jrbudda notifications@github.com:
