### ISSUE TITLE
Brown fixed checkerboard when inside blocks nauseating

### ISSUE THREAD

**Issue by phr00t** [jrbudda/minecrift#188]
When your head accidentally falls into solid territory, a fixed brown checkerboard pattern fills your view. It is very nauseating to look at when trying to return to your correct position. The SteamVR compositor goes to a solid blue color when tracking is lost, because it prevents sickness. Can we just have a solid black background when searching for your ground location? Is there an option for this?

**Comment by Techjar** [comment]
Brown fixed checkerboard? It's actually the block texture, so you must be inside dirt. I don't see how it would case motion sickness, considering it's basically like having a piece of cardboard taped to your face. I guess an option for drawing a solid color is doable.

**Comment by Techjar** [comment]
There, done, that was pretty easy to do. It'll be included in v28. Here's a build for you to use right now, you'll find the option under stereo rendering. Enjoy!

[vivecraft-1.7.10-Vivecraft-jrbudda27-test3-installer.exe](https://owncloud.techjargaming.com/index.php/s/d9pGeLSCBl4hbnO/raw)

**Comment by phr00t** [comment]
oooOOoo thank you for the option! It is nauseating (for me at least), because my whole view has something to focus on that isn't being tracked. I look forward to trying it out!

**Comment by jrbudda** [comment]
closing because released in 28. Thanks phr00t! I <3 your wrapper.
