### ISSUE TITLE
Touch Hotbar

### ISSUE THREAD

**Issue by CodeKartonka** [jrbudda/minecrift#189]
Very nice work thank you !
Absolutely!

I Love you Touch HotBar it a Perfect solution for me if i use "Wrist" mode :-) just only need a slider to get offset from controller :D i hit them both sometimes
(select 1 2 3 is too close to the other controller)
http://imgur.com/bdYHcus

Another point is:
It wold be wonderful if u can add a dual hotbar :-) (double Hotbar ?)
http://i.imgur.com/9fsq7e2.png
first row from the invertar would be perfect

sorry for bad english :-(
german here :-)
#113

**Comment by Techjar** [comment]
We won't be adding a dual hotbar ourselves for various reasons. You could try the dual hotbar mod though, I'm curious to see if it works.

**Comment by jrbudda** [comment]
I still need to tweak this on 1.10 cause it clips into your hand if you have hud occlusion off.
