### ISSUE TITLE
Installation of vivecraft fails- Couldn't Download C++ Redistributables

### ISSUE THREAD

**Issue by mycophobic** [jrbudda/minecrift#194]
I've run vivecraft-1.7.10-Vivecraft-jrbudda29-installer and checked "Create Vivecraft launcher profile" and "Enable binaural audio" then clicked Install. I quickly get a popup that says "Failed: Couldn't Download C++ Redistributables". 

I've searched for solutions online but reinstalling minecraft and re-trying hasn't worked. I can't find any other instances of people having this problem and finding a solution.

**Comment by Techjar** [comment]
It's failing to retrieve the C++ redistributable files. I don't know why, maybe your firewall is misconfigured or something?

**Comment by jrbudda** [comment]
tweaked the installer to only warn you if the vc++ install fails so you can do it yourself.
