### ISSUE TITLE
HUD is the entire screen, as opposed to just the hotbar

### ISSUE THREAD

**Issue by aciou** [jrbudda/minecrift#195]
![bug](https://cloud.githubusercontent.com/assets/20638467/17095716/4e2c430a-5299-11e6-9f24-7d0fcf7f6caa.png)

I didn't have this issue with 1.7. Couldn't fix it in HUD settings.

**Comment by jrbudda** [comment]
do a reset of the video options. It's one of them. I haven't figured out which.

**Comment by aciou** [comment]
No worries, I'll give that a go. Thanks for all your work.

**Comment by jrbudda** [comment]
duplicate of https://github.com/jrbudda/Vivecraft_110/issues/19

closing here.
