### ISSUE TITLE
Can't mine with Right Trigger

### ISSUE THREAD

**Issue by Korvar** [jrbudda/minecrift#196]
I've been having a problem with mining using the right trigger.  Sometimes it works and others not.  I've tried changing the relevant options, but if I disable weapon swinging I can't mine at all.

The animation of the tool zipping forwards still happens, and the relevant block has the usual line around it indicating it's selected, but no actual mining happens.

**Comment by Techjar** [comment]
Are you holding a sword? Also 1.7 or 1.10?

**Comment by Korvar** [comment]
I'm on version 1.10

And it doesn't matter what I'm holding.  I've verified I was using a pickaxe and while swinging worked, using the right controller trigger did not.

**Comment by jrbudda** [comment]
duplicate of https://github.com/jrbudda/Vivecraft_110/issues/27

closing this one.
