### ISSUE TITLE
Direction detection is flipped on the X axis

### ISSUE THREAD

**Issue by Nixill** [jrbudda/minecrift#198]
_Forge installation with no mods, singleplayer, creative_

(edit: This is standing behavior only, not moving.)

When placing directional blocks while north or south of the target block, they would place facing you. When placing them while east or west of the target block, they would place facing away from you.

**Comment by Techjar** [comment]
Sounds like the yaw axis is negated from what it's supposed to be, which is weird. Do blocks orient backwards vertically as well?

**Comment by Nixill** [comment]
I haven't tried vertically-sensitive blocks yet (all I can think of that would be affected in vanilla is pistons). It's a little late for me to game right now, so if you can wait until morning (US), I'll get that report for you then.

**Comment by Techjar** [comment]
Okay, so this is a regression because jrbudda removed a crucial negation on the pitch and yaw.

**Comment by Techjar** [comment]
Somehow the pitch and yaw of the crosshair look rotation got un-negated. We'll be doing a release to fix this, so watch for that. In the meantime, if it bothers you, you can use v28 which doesn't have this bug.

**Comment by Techjar** [comment]
I've published v29r1 as a ninja update to fix this bug.
