### ISSUE TITLE
Inventory stays anchored to wrong point of reference when character moves

### ISSUE THREAD

**Issue by Nixill** [jrbudda/minecrift#201]
_Forge installation [with mods](https://gist.github.com/NixillUmbreon/de1337e66801063f2a95ed6442244e73), singleplayer, all gamemodes_

If you open your inventory while you're moving, the inventory will stay anchored to its point of spawning in the game world, rather than where it spawned in the real world (VR play area). This means that if you open it, for example, while falling, it quickly leaves any usable position and goes far above you until closed and reopened again.

Some cases where this causes problems:
- Opened while flying around in creative (when you stop holding W, the inertia still takes you a good distance, and that distance is longer than a minimum-size play area)
- Opened while falling off a cliff
- Opened while riding a minecart
- Opened while riding an animal
- Opened while being carried by a water current
- Opened while in creative mode and airborne (see #202)

**Comment by jrbudda** [comment]
Thanks, this was shockingly easy to fix.  Will be in next release.

**Comment by jrbudda** [comment]
fixed in versions 3 and 30
