### ISSUE TITLE
Jump and sneak not ignored in inventory

### ISSUE THREAD

**Issue by Nixill** [jrbudda/minecrift#202]
_Forge installation [with mods](https://gist.github.com/NixillUmbreon/de1337e66801063f2a95ed6442244e73) and [modified controller config](https://gist.github.com/NixillUmbreon/d048bc37149f02b306ed412000e2fc15), singleplayer, all gamemodes_

When an inventory is open, the game will still process jumps and sneaks (and therefore flying up and down) outside of the inventory.

This also has the side effect of causing #201 to happen as well.

**Comment by jrbudda** [comment]
versions 30 and 3 should no longer allow this.
