### ISSUE TITLE
First-person arms too bright at night

### ISSUE THREAD

**Issue by FeepingCreature** [jrbudda/minecrift#203]
The arms and tools visible in first person are always rendered at full brightness. As a result, they're glaringly bright during the night, making it hard to see the surroundings.

Please shade them by in-game lighting. (This will increase immersion as well.) 

The menus could also be somewhat darker during the night.

**Comment by jrbudda** [comment]
Is this limited to 1.7.10? I thought I had fixed this but maybe only for 1.10.

**Comment by FeepingCreature** [comment]
It's happening for me on 1.10. I'll go make a screen.

[edit] Correction, 1.10.2. BRB, updating.

**Comment by FeepingCreature** [comment]
Confirmed fixed in the current version. My apologies.
