### ISSUE TITLE
[Enhancement] Stabilize cursor in menus when trigger is pressed

### ISSUE THREAD

**Issue by FeepingCreature** [jrbudda/minecrift#204]
When pressing the trigger, it's easy to jiggle the cursor around. This can make it hard to use the menus, especially at a slight distance.

A possible solution would be slightly stabilizing the cursor depending on the rate of change in the trigger.

**Comment by Techjar** [comment]
Do you mean the non-dominant hand trigger? We certainly wouldn't use the dominant hand one as that's for clicking stuff. Also I'm not sure what you had in mind, but what I interpret is having the cursor lag behind where you're pointing when you hold the trigger, which would honestly just be unintuitive and useless. I'm not sure how we're supposed to "stabilize" the cursor.

**Comment by jrbudda** [comment]
he means the dominant trigger. soft press stabilizes it, full press clicks.

**Comment by Techjar** [comment]
Well how would be go about "stabilizing" the cursor anyways?

**Comment by FeepingCreature** [comment]
I do mean the dominant trigger, and the idea isn't to add it as a new function, but to reduce the amount of cursor motion in a frame depending on _how much_ the trigger was pressed that frame.

Pressing the trigger, especially quickly, exerts a slight downward jerk on the controller. This can easily make you slip into the next cell of the UI, causing mis-inputs. Instead of holding the controller extra steady, the idea here is to compensate for that jerk by slightly ignoring cursor input as it's happening. 

_Hopefully_, this should not make a difference to regular user experience, since people don't normally move their cursor and press down the trigger at the same time.

Ie, in JS-y pseudocode

```
var cursorChange = mousePos - lastMousePos;
var triggerChange = triggerLevel - lastTriggerLevel;
if (triggerChange > 4) {
  var adjustCursorDist = max(0, cursorChange.length - (triggerChange - 4) * settings.dampenStrength);
  var dampenedCursorChange = cursorChange.length(adjustCursorDist);
  mousePos = lastMousePos + dampenedCursorChange;
}
```

(Adjust constants as needed to feel good during use.)

**Comment by jrbudda** [comment]
you'd have to filter out clicking scrollbars. The simple way to do it would be just forget the trigger business and do a short running average of cursor position all the time. I'll experiment with it.

**Comment by Techjar** [comment]
Yeah but if we do an average won't it just lag behind the actual position all the time and get annoying?

**Comment by FeepingCreature** [comment]
Yeah that was the idea of avoiding. Maybe a very gentle running average that gets _slightly_ stronger when the trigger is moving?

Might be useful to dump cursor position per frame so you can see closer how much actual jitter there is. Maybe I just have unusually jittery hands.

**Comment by jrbudda** [comment]
the next steps on my  roadmap include building a much better framework for temporal VR controller/hmd data. Once I have that in place experimenting will be easy. I think a very short running average will be hardly noticeable but we'll see.

**Comment by FeepingCreature** [comment]
Brief addition, even though it's closed: a possible way to go would be to have a circle that expands as you press the trigger, that acts as an additional cursor for the click while the regular cursor keeps moving. Which would avoid lag issues while also stabilizing clicks.
