### ISSUE TITLE
Can't go back to main menu

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#205]
Dunno why no one reported this but going back to the main menu from in-game was broken in v30. Fixed in this build here. Also fixed particles.

[vivecraft-1.7.10-Vivecraft-jrbudda31-installer.exe.zip](https://github.com/jrbudda/minecrift/files/392289/vivecraft-1.7.10-Vivecraft-jrbudda31-installer.exe.zip)

**Comment by royda** [comment]
I noticed this, but (probably like many folks) returning to main menu typically meant leaving the game so I took my headset off anyways. Aka, I just dealt with it. :) Thanks for fixing though! Appreciate it

**Comment by CodeKartonka** [comment]
thx, well done! :-)
i noticed it to! same as royda ;-)
