### ISSUE TITLE
[Forge Mod] LOTR - achievements crash

### ISSUE THREAD

**Issue by royda** [jrbudda/minecrift#207]
Single-player, using 1.7.10 Vivecraft version 30 with Forge and the LOTR mod (http://lotrminecraftmod.wikia.com/wiki/Lord_of_the_Rings_Mod):
--Opening the LOTR Achievements screen crashes the game.

I go to VR Settings, then controller buttons option, then set a button to "Menu" (which is a LOTR option which opens the map screen). This works. I can click the Vive controller button and open the map. At the top left and right of this map screen are options to show additional screens (Shields, LOTR Options, etc.). I can click them and cycle through the screens just fine. Going to the "Achievements" screen crashes Minecraft however. Find attached the crash report.
[LOTRAchievementcrash-2016-07-30_19.31.10-client.txt](https://github.com/jrbudda/minecrift/files/392504/LOTRAchievementcrash-2016-07-30_19.31.10-client.txt)

**Comment by jrbudda** [comment]
I can't do anything about this one without seeing the source code for LOTRGuiAchievements as that is where the crash is. Or their dev would have to tell me what's unexpectedly null.

**Comment by jrbudda** [comment]
curiosity got the better of me and i fixed this.
