### ISSUE TITLE
Cannot teleport past a fence, chests, furnaces etc

### ISSUE THREAD

**Issue by Aesop112** [jrbudda/minecrift#21]
Cannot teleport even close distances if a fence or chest is between you and your teleport location. Requests:
I really miss the right grip button for torches!
Keyboard shortcuts to make a handy voice attack profile.
Turn up the tactile feedback and add more of it for different things.

**Comment by jrbudda** [comment]
By between you, do you mean the teleport arc is going through the fence/chest? or above it?

Quick torch is not coming back into this mod, there's just not enough buttons and it's not part of the base game. Eventually you can install a seperate mod that adds it to a button and you can map that button to the controller.

the haptics cannot be turned up so far as I know, are there other vive games with stronger rumbles? 
the OpevVR haptic only has a duration setting. I;m adding more in slowly.

Keyboard shortcuts for Non-VR things are not in the scope of this mod, there should be some kind of Forge mod that does that.

**Comment by Aesop112** [comment]
The teleport arch is going above and over  a fence or chest or furnace are the ones that 100% consistently don't work, not sure if it's just me or not definitely worth looking at :). Also, not sure if original Minecraft you were able to stand ON a fence but currently you cannot teleport onto one. 

I'm not sure if openvr is any different than steamvr games other than being open source but yes I've noticed substantially more pronounced and appropriate haptics in other games. The vr game chunks is a good example of haptics used for placing blocks. I'm not sure if there is a way to match up haptics with the  envelope of the sound but they seem to go hand and hand. 

I wanted to use Windows virtual keyboard to input for signs and in game chat, but it input isn't happening. Does openvr give you access to steams touchpad virtual keyboard? I know feed the beast might go down smooth if there were a way to search for items by steam vr virtual keyboard or even if not that Windows virtual keyboard. 

Thanks for your effort, it's turning out really awesome. Wish most game devs put out updates of great tweaks this quickly.

**Comment by jrbudda** [comment]
You can stand on fences in vanilla but you can't jump high enough to get onto them normall.. so im not sure how I feel about being able to teleport onto them. That being said I can't reproduce your issue of teleporting over a fence or chest, i can go over just fine so long as the arc lands somewhere no in the fence block.

Keyboard is possible and someone else has already added  it to vivecraft I just need to go borrow it.

**Comment by Aesop112** [comment]
I think the max value for trigger haptic pulse is 3999. I'm also hearing there are other ways of going about it though.

**Comment by Aesop112** [comment]
Okay they don't explain this very well but duration= strength. I'm guessing you already knew that. There may be a freed back library floating around somewhere.

**Comment by Aesop112** [comment]
Found this, not sure if it helps. :/

If you want longer vibrations, try something like this:

//length is how long the vibration should go for
//strength is vibration strength from 0-1
IEnumerator LongVibration(float length, float strength) {
    for(float i = 0; i < length; i += Time.deltaTime) {
        SteamVR_Controller.Input([index]).TriggerHapticPulse((ushort)Mathf.Lerp(0, 3999, strength));
        yield return null;
    }
}

And for pulsed vibrations
//vibrationCount is how many vibrations
//vibrationLength is how long each vibration should go for
//gapLength is how long to wait between vibrations
//strength is vibration strength from 0-1
IEnumerator LongVibration(int vibrationCount, float vibrationLength, float gapLength, float strength) {
    strength = Mathf.Clamp01(strength);
    for(int i = 0; i < vibrationCount; i++) {
        if(i != 0) yield return new WaitForSeconds(gapLength);
        yield return StartCoroutine(LongVibration(vibrationLength, strength));
    }
}

**Comment by jrbudda** [comment]
Yea that steam thread is like literally the only source on google for the haptics, I was just reading it. Try out v11, I added some more.

**Comment by possi** [comment]
@hitchikersguide Does is effect single-player or multiplayer only?
