### ISSUE TITLE
V31 - Invisible Invertory Cursor on ThermalExpansion

### ISSUE THREAD

**Issue by CodeKartonka** [jrbudda/minecrift#211]
Hi :-)
sorry my english is not so well

http://teamcofh.com/docs/thermal-expansion/

Cursor Invisible

gif clip :-)
https://www.dropbox.com/s/px5yir6sb5irpdg/nocursor.gif?dl=0

tested only with this here vor avoid other mod conflict
Clean Install+V31+Forge-1.7.10-10.13.4.1614
No Shader
CoFHCore-[1.7.10]3.1.3-327
ThermalExpansion-[1.7.10]4.1.3-246
ThermalFoundation-[1.7.10]1.2.5-115

**Comment by jrbudda** [comment]
see #129
