### ISSUE TITLE
v31 - Inventory-GUI to Short with "IronChest"

### ISSUE THREAD

**Issue by CodeKartonka** [jrbudda/minecrift#212]
IronChest Gui is to short on bigger Chest :-)

screenshot:
https://www.dropbox.com/s/8vo2xzyxrfwcizp/2016-08-04-AM_11_57_40.jpg?dl=0

tested again :-) only with this here for avoid other mod conflict:
Clean Install+V31+Forge-1.7.10-10.13.4.1614
No Shader
ironchest-1.7.10-6.0.62.742-universal

**Comment by Techjar** [comment]
We can't do anything about that, it's the mod's fault. The GUI is literally just too big. You could try making the game window larger. The upshot is, the cut off parts are harmless, as there's no slots there. That's probably why the developer never bothered to try to fix it, as the GUI is basically as large as it can possibly be while still fitting all the slots in the screen.

See, it does it on a normal client as well:
![image](https://qimg.techjargaming.com/i/AzX87RFw.png)
