### ISSUE TITLE
Error 105 : Interface Not Found. Opt out of SteamVR Beta.

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#214]
Until they fix it.

**Comment by Anahkiasen** [comment]
@jrbudda Was this closed because it works now or because this is a `cantfix`? To know if I can update to the beta yet

**Comment by jrbudda** [comment]
yes should be fixed in steamvr beta

**Comment by Anahkiasen** [comment]
Cool, thanks!
