### ISSUE TITLE
[REQUEST] Map keys to touch pad buttons on Vive controller

### ISSUE THREAD

**Issue by Fureniku** [jrbudda/minecrift#216]
Hey,

It'd be really useful if we could map keys to the touchpad, or maybe other points on the Vive controller. Standard movement works fine right now, but for example when in a vehicle we have no way to press W to accelerate (Playing in 1.7.10). If possible, maybe changing the keys depending on the entity the player has mounted (via player-made configs)

It'd be awesome to be able to fly an MCHeli vehicle in VR! :D

**Comment by jrbudda** [comment]
You can do this now.

**Comment by Fureniku** [comment]
Hm, any links to info on how? I did have a look around but maybe I was looking in the wrong place

**Comment by jrbudda** [comment]
see http://www.vivecraft.org/how-to-play/ the section on controller buttons.

**Comment by Chimera245** [comment]
On this same topic, is there any way to "go back" when assigning a function to a Vive button/touchpad quadrant? I always wind up clicking one too many times, then having to cycle through them all again to get to the one I wanted.

**Comment by jrbudda** [comment]
Nope
