### ISSUE TITLE
[REQUEST] Make locomotion toggle a setting that can be disabled

### ISSUE THREAD

**Issue by vdwtanner** [jrbudda/minecrift#217]
Currently, holding SHIFT toggles the locomotion method from free move to teleportation. I like the ability to use SHIFT when doing item management and can also use it for sneaking, so I was wondering if you could make the Toggle feature a setting that can be turned off.

Fantastic mod by the way! I got to mess around with it for a bit last night, and it brought the excitement back to the game. I even enjoyed fishing on a river bank haha :)

**Comment by jrbudda** [comment]
shift.. like.. on the keyboard? shift on the controller is left grip and move mode switch is right grip

**Comment by jrbudda** [comment]
Theres also this.

![image](https://cloud.githubusercontent.com/assets/1927235/17708593/ae66b1bc-63b3-11e6-8520-3aa4087b1063.png)

**Comment by vdwtanner** [comment]
Oh! I hadn't seen that When I was browsing the settings last night! I had bound the right grip to keyboard shift (left controller grip to free rotate) when I noticed that it was making the mode switch, so I assumed that that was what it was. I guess it's a non-issue then, thanks for the clarification!
