### ISSUE TITLE
Modded minecraft main menu not showing

### ISSUE THREAD

**Issue by Delectrixz** [jrbudda/minecrift#22]
The old Automat-GH version had this to however there's a workaround involving a macro to allow people to bypass the problem in the meantime. 

On the main menu when you first boot up modded minecraft you used to get a grey screen that you  bypassed using a simple macro from this [tutorial](https://www.reddit.com/r/Vive/comments/4fbwyb/minecraft_vive_forge_ftb_install_kit_guide_inside/)
This moves your mouse to click the single player button as it isn't visible. When the macro completes you can see and interract with the menu as normal. You can see it in action from Milly Moo's tutorial video [here](https://youtu.be/FXo5ilSZpGE?t=899).

Now with your version there's no greyscreen its the dirtroom environment that you created (awesome idea btw) and the menu isn't viewable until you do the macro like before, would this be something you can fix to eliminate the need for the macro? I have a feeling this will be an unknown step for most people trying modded mc.

**Comment by jrbudda** [comment]
Gonna take a wild guess looking at the mod list that the issue is CustomMainMenu. What happens if you delete that jar?

**Comment by Delectrixz** [comment]
That was the culprit! Deleting it removes the problem, id put a note in the description somewhere that "CustomMainMenu-MC1.7.10-1.6" found in FTB mod packs isn't compatible.

**Comment by jrbudda** [comment]
already on the reddit wiki. thanks.
