### ISSUE TITLE
Controllers not working 1.7.10

### ISSUE THREAD

**Issue by Cluckster13** [jrbudda/minecrift#220]
The controllers don't seem to respond whenever I enter the 1.7.10 version of this mod. They refuse to track or do anything.

**Comment by Techjar** [comment]
This most likely isn't caused by Vivecraft. Try rebooting the headset, restarting Steam and/or computer, and opting in/out of the SteamVR beta. If it still persists then I'm not sure what to tell you, but if you fix it tell us how, as it could be useful to us.

**Comment by jrbudda** [comment]
or you accidently put it into seated.

**Comment by Techjar** [comment]
Ah yes, that is also possible. However I cannot tell as the issue is rather vague.

**Comment by Cluckster13** [comment]
Nvm I did a fresh install of everything and it worked, I think I might have put it into seated mode by pressing one of the buttons maybe. Thanks anyways.
