### ISSUE TITLE
Carpet and Teleporter

### ISSUE THREAD

**Issue by davidweisgerber** [jrbudda/minecrift#221]
If you have carpet in your house and use teleporter as controls you cannot teleport to locations where there is carpet. You have to remove the carpet first. 

Tested on version 1.10.2

**Comment by jrbudda** [comment]
well thats a problem.

**Comment by jrbudda** [comment]
ok for me it just puts you at the next block up https://i.gyazo.com/32aa25557cab9419fb90c1674d837831.png

**Comment by jrbudda** [comment]
Please see if this is better. I kinda re-wrote that whole teleporting thing so let me know if it behaves weirdly with any other blocks.

[vivecraft-1.10.2-Vivecraft-jrbudda-6pre-installer.zip](https://github.com/jrbudda/minecrift/files/429117/vivecraft-1.10.2-Vivecraft-jrbudda-6pre-installer.zip)

**Comment by jrbudda** [comment]
Fixed in v6 for 1.10, will be in 1.7.10 soon
