### ISSUE TITLE
Vivecraft won't start on the Rift, Render Setup Failed Shared IPC Compositor Invalid Connect Response (307)....

### ISSUE THREAD

**Issue by maxpare79** [jrbudda/minecrift#222]
Hi, I tried both version of Vivecraft with the same result...Minecrift used to work fine btw....when I try to start it I get a message:

Render Setup Failed Shared IPC Compositor Invalid Connect Response (307)....

It's written inside minecraft on a black screen, and not a windows popup window...

The only thing left to do is close the window and then SteamVR, but once I close steam VR I get a VR Server has stopped working window...

**Comment by jrbudda** [comment]
Is your SteamVR up to date? are you in the normal or beta branch of it?

**Comment by maxpare79** [comment]
Yeah I am in the Beta branch and steam updates automatically...

I also have Minecraft windows 10 edition installed could that cause a
conflict? I can usually run the Java version and the windows 10 version
without any problems... Oh and in 2D the Java version works just fine

Also when I installed Vivecraft it tells me that it cannot install
Microsoft Visual C+ Redistributal 2010, but I already have it install on my
machine,  along with the 2005, 2008 and 2015

**Comment by jrbudda** [comment]
No its certainly a SteamVR issue. I do not know what though.

**Comment by maxpare79** [comment]
I will uninstall steamVR and re-install it and keep you posted...

**Comment by jrbudda** [comment]
another user solved this problem by using the NVIDIA control panel to force the game use the correct GPU.

**Comment by maxpare79** [comment]
Only have one GPU (1080)...but uninstalling and re-installing steam vr 
did the trick

Thanks!
