### ISSUE TITLE
White bars on black ground @startup

### ISSUE THREAD

**Issue by Gensokian** [jrbudda/minecrift#223]
So I've startet vivecraft like usual (it worked yesterday) and now I got the following (helping) error: http://imgur.com/a/YDLUV

So I thought, maybe it's because something is corrupded in MC, so I went and deleted the .minecraft folder (of course backed up the worlds) after that I reinstalled MC, with 1.7.10, installed forge 10.13.4.1614 as stated in the thread, went on and installed vivecraft, no errors so far, but when I started it, welp... 

ALSO I attached the log here.

cheers Spacy

--FORGE INSTALL LOG
[forge-1.7.10-10.13.4.1614-1.7.10-installer.jar.txt](https://github.com/jrbudda/minecrift/files/443377/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar.txt)

--MC LAUNCH LOG
[fml-client-latest.txt](https://github.com/jrbudda/minecrift/files/443380/fml-client-latest.txt)

**Comment by jrbudda** [comment]
The black screen thing is usually fixed with a reboot of SteamVR.  The log you included doesnt show a error or anything

**Comment by Gensokian** [comment]
awkward... reinstalled steamVr... still no change

**Comment by jrbudda** [comment]
those white blocks are a steamvr message, i think... Maybe restart steam? or your PC? especially since the problem started without any changed to minecraft

**Comment by Gensokian** [comment]
I'll retry tomorrow.  I did try to launch Mc as admin...  didn't respond at all (gave not responding error) 

What I did do was installing vc for 1.10 in .minecraft and THEN in the profile option use another dir to unload the mods. 

but I also removed those folders as well so Mc was complete clean

**Comment by Gensokian** [comment]
Fresh day, fresh luck... Well... not really...
I started Minecraft again and guess who's there, my good ol pall blank squares with black background...

I have no Idea why this is happening but it is... 
https://youtu.be/pWo4RZbFQCM <- This is a vid how I install it maybe you see an error....

Also, any other game runs fine, tried reinstalling SteamVR still didn't work...

**Comment by Gensokian** [comment]
So I've tinkered around a little, and installed Vivecraft for 1.10.2... "Same" results, Now I actually have text instead of blocks... (even the lenght makes up like in the Screenshot below)

Render Setup Failed, Shared IPC Connect failed after Multiple attempts 308
http://imgur.com/a/YDLUV

Running it in administrator mode like in [HERE](https://github.com/jrbudda/Vivecraft_110/issues/46)
Gives me RANDOM problems. It works, as long as I dont do anything, or move the cursor out of the game.... I think i might have goofed up something internally... I Keep trying until it works...

**Comment by jrbudda** [comment]
yay progress. That error seems to be caused by using the wrong GPU as your system default. Or maybe not running as administrator. It's not a very helpful steamvr error message is it?

**Comment by Gensokian** [comment]
Well guess what, Magic happened, I've reinstalled the GPU driver, and for some reason what so ever, it just works with administrator, You know what they say, never change a running system... I aint startin MC without admin anymore... 

> and now mod it!
> ![2016-08-30_21 50 19](https://cloud.githubusercontent.com/assets/9213561/18104544/dad79006-6efb-11e6-914f-441c9f7ca15e.png)

![2016-08-30_21 51 55](https://cloud.githubusercontent.com/assets/9213561/18104567/055f22f8-6efc-11e6-89c2-c38be13d2c2a.png)

Anyways thanks for helping the other dude which kinda helped me xD

KEEP UP THE AWESOME WORK!!!

Cheers

**Comment by jrbudda** [comment]
nice. enjoy.

**Comment by beezdul** [comment]
Running minecraft as admin fixed this for me
