### ISSUE TITLE
Game failes to open if steamvr is not started

### ISSUE THREAD

**Issue by pfgithub** [jrbudda/minecrift#226]
If steamvr is not started before opening the game, the game will open steamvr and say failed to initialize.

Windows 10, Latest vivecraft for minecraft 1.10

**Comment by Techjar** [comment]
This seems to happen now. It used to be that the initialization would wait until SteamVR was ready, but Valve broke something and now it just fails. It likely happens for games on Steam too, though I haven't tested it.

**Comment by pfgithub** [comment]
SteamVR used to not open if other apps wanted to hook into VR, now it opens
for some reason though

**Comment by Techjar** [comment]
Yes, that is a new feature, however it also used to actually start up correctly when doing that.

**Comment by jrbudda** [comment]
This shouldn't be an issue anymore
