### ISSUE TITLE
[Major problem]InvocationTargetException

### ISSUE THREAD

**Issue by cmurtheepic** [jrbudda/minecrift#227]
vivecraft crashes when trying to load it with ATlauncher modpack Unabridged. i am using 1.7.10, latest version of vivecraft. i have installed forge. and am trying to launch the modpack with the minecraft launcher with vivecraft profile. here is crash log
http://pastebin.com/TPQBM9Gw

**Comment by jrbudda** [comment]
No idea what's going on here, never used ATLauncher
