### ISSUE TITLE
How i change move key for "W"....

### ISSUE THREAD

**Issue by hereww** [jrbudda/minecrift#228]
How i change move key for "W"....
I'm developing VR Treadmill

**Comment by Techjar** [comment]
You want to change the move key from W to something else? That should just be in the vanilla controls screen.

**Comment by hereww** [comment]
where?
@Techjar

**Comment by Techjar** [comment]
It's in Options > Controls, I don't remember the name of the binding but look for something assigned to W.

**Comment by Techjar** [comment]
Oh wait, you're trying to use this in standing mode aren't you? Yeah, we'll have to add some special support for that. If you want, hop on the minecraft vive discord later, when jrbudda is online, and we can discuss it. Otherwise we can just discuss it here I suppose.

**Comment by hereww** [comment]
No,I want to use the keyboard and mouse to play minecraft.
But I use VIVE!!
@Techjar

**Comment by Techjar** [comment]
Oh, if you just want to play with keyboard and mouse, switch to seated mode in the VR options. I thought you were wanting to use the Vive controllers while having mapped inputs to keyboard keys.

**Comment by hereww** [comment]
How I switch to seated mode?Where...?
My English is poor
@Techjar

**Comment by Techjar** [comment]
In the VR settings.

**Comment by hereww** [comment]
VR settings》》》？？？？
@Techjar

**Comment by Techjar** [comment]
Launch game > Click "options" on the title screen > Go into "VR settings" > Change from "standing" to "seated" mode

You must do this on the vivecraft client, in VR, not the normal minecraft client.

**Comment by hereww** [comment]
Thanks you very much!
I test it~~~~
@Techjar

**Comment by Techjar** [comment]
You're welcome!
