### ISSUE TITLE
[Request] Ability to Change Settings Outside VR

### ISSUE THREAD

**Issue by ThomasRules2000** [jrbudda/minecrift#229]
As stated, I think it would be easier to change settings if you could open the options menu outside of the virtual world on your physical monitor. This would allow for bulk changes of configurations (e.g. when you load a new pack with the mod installed) to become much easier and faster, so decreasing the time it takes to get into a world ingame

**Comment by jrbudda** [comment]
you can interact with the mirror easily with the mouse, just hide the HMD so it stops tracking
