### ISSUE TITLE
[Truth] Not really an issue

### ISSUE THREAD

**Issue by angelo-hub** [jrbudda/minecrift#23]
Just opened an issue to tell you your release notes are hilarious, that is all. You can now close the issue.

**Comment by jrbudda** [comment]
You don't tell me what to do. This is staying open forever as a testament.

**Comment by joshburt** [comment]
Oh you guys ;)

**Comment by jrbudda** [comment]
Ok too many open issues.

**Comment by angelo-hub** [comment]
Awww RIP My Issue 2016-2016 :'(
