### ISSUE TITLE
Error when downloading 

### ISSUE THREAD

**Issue by queengxo** [jrbudda/minecrift#230]
everytime I try to reinstall it says "could not download vc++redist. Game might not work" and it doesn't?? 

EDIT: so I got it to run but it only shows on my desktop monitor and not through the VIVE headset??

**Comment by CaptainDimak** [comment]
Yo, I have the exact same issue on two separate identical windows installs, any options here?

The game is tracking everything and rendering properly, but isn't throwing anything up inside the headset.
