### ISSUE TITLE
Run in Place Orientation

### ISSUE THREAD

**Issue by bknie1** [jrbudda/minecrift#232]
Hi there.

For some reason, when I use "Run in Place" locomotion, my character is facing backwards. That is, if I try to run, I run backwards. Is there any way to orientate my character so that this doesn't happen? Is it a known bug?

Thanks.

**Comment by jrbudda** [comment]
are you playing with 'reverse hands' on by chance?

**Comment by bknie1** [comment]
Oh, yes. I'm left handed. Do I need to toggle something else so that Run In Place reflects that change?

**Comment by bknie1** [comment]
Switching off reverse hands did fix the issue. I tried manually switching controllers but the input seems to be related to the opposite controller. If you could also reverse how Run In Place detects direction at the same time you reverse the hands it might fix it? Easier said than done I'm sure. I still don't mind teleporting!

**Comment by jrbudda** [comment]
I think I fixed this.

**Comment by bknie1** [comment]
@jrbudda Thank you! My Vive's out for RMA (again) but I'll test it when I can.
