### ISSUE TITLE
[Issue] Shooting bows and hotbar interference.

### ISSUE THREAD

**Issue by bknie1** [jrbudda/minecrift#235]
I had some trouble shooting a bow. Equipping a bow puts it in my left (non-dominant controller) and an arrow in my right (dominant controller) hands. However, when I move to knock the arrow, my hotbar interferes with knocking. I end up switching items and ultimately not being able to do anything.

My roommate was able to shoot arrows but they didn't do any damage (unrelated, probably). This was in the Golden Chalice of Kurast save (vanilla Minecraft) on 1.10.2.

Thanks!

**Comment by bknie1** [comment]
Okay, so you have to hold the arrow adjacent*\* to the bow string in order to get this to work. It's less natural/less like knocking an actual arrow. I'm not sure if this can be improved upon but yeah- it was a bit confusing at first.

It might be worth adding some simple tutorials to the main Vivecraft site.

**Comment by jrbudda** [comment]
how else do you nock an arrow except perpendicular to the string?

**Comment by bknie1** [comment]
My mistake. I think I meant adjacent. I'll draw a crappy picture:
![untitled](https://cloud.githubusercontent.com/assets/16689276/18600253/a9614b84-7c2a-11e6-9d21-147f35a1910a.png)

I have to hold the arrow sideways of the bow string in order to actually make the knocking transition. Sorry about the language mix up. My roommate, who also has a Vive, encountered this issue as well. It certainly isn't game breaking now that I've figured it out but I wouldn't say it's a natural way of nocking an arrow. Granted, perhaps the alternative that you likely already tried involved doing it the more natural way and knocking hand controllers. Is this intentional? Might there be a better way to assume bow/arrow proximity without nocking heads? I was thinking something more along the lines of how QuiVR does it.

If not, don't sweat it. It just took some trial and error to get it working.

Thanks for looking into this.

**Comment by jrbudda** [comment]
that's weird, are you using a texture pack?

**Comment by jrbudda** [comment]
Closed because likely texture pack issue
