### ISSUE TITLE
[requests]

### ISSUE THREAD

**Issue by Aesop112** [jrbudda/minecrift#237]
1. Third person view for the display mirror 
2. Movement Speed relative to how far trigger is pulled.
3. Haven't seen this on requests- vastly extend reach for block breaking and placing in creative mode.
4. A selection box with copy and paste in creative mode.

**Comment by Techjar** [comment]
1. Probably possible but we'd have to hack around in the third person rendering code. So... maybe.
2. This isn't easy to do as key binds are binary input only. We'd have to hard-code custom handling for movement, and then how would we even handle the binding?
3. This is already implemented, the server side just has to support it.
4. Rather complicated, just get WorldEdit in 1.7. And can't you do this in vanilla 1.10 with structure blocks?
