### ISSUE TITLE
Bad Rendering Problem After a Steam Update

### ISSUE THREAD

**Issue by ratherwok** [jrbudda/minecrift#239]
My Vivecraft had been working fine for months until this Tuesday. There was a steam or steam vr update. After the update vivecraft started to have rendering problems. The headset rendering is messed up. Each eye has a different problem. The left eye has a distortion, the right eye has correct perspective but there are 2 sharperons and they are distorting similarly to the left eye which cause the sharperon lines to slide around on the ground.

All the other vive games work fine.

Here's a video.
https://www.youtube.com/watch?v=mb4eIaVu7xE

**Comment by Techjar** [comment]
Wat? We don't control chaperone rendering, so I have no idea how that would
happen. I feel like it's something messed up on your end.

**Comment by ratherwok** [comment]
Whether it's on my end or not I'm looking for some help. I haven't changed any setting, and when I hit the home button to bring up the steam menu in vivecraft there is no distortion, hit the button again to return to vivecraft the distortion comes back. The only place I see this distortion/glitch/bug is in vivecraft.

**Comment by Harper0921** [comment]
I just wanted to add that I am having the exact same problem.

**Comment by Shadaez** [comment]
Turning off Anisotropic Filtering and restarting the game fixes it for me, does turning AF on (and restarting) cause the bug for you?

**Comment by Shadaez** [comment]
see if this fixes it https://github.com/jrbudda/minecrift/issues/239#issuecomment-254565536

**Comment by Techjar** [comment]
Can confirm that starting the game with anisotropic filtering enabled causes this bug.

**Comment by ratherwok** [comment]
Thanks @Shadaez it fixed the problem. Although I've been playing with AF enabled since I downloaded vivecraft and everything was fine. I wonder if the steam update messed it up...

**Comment by Harper0921** [comment]
Awesome! Thank you! Turning off Anisotropic Filtering fixed it for me as well.

**Comment by jrbudda** [comment]
check the latest steamVR beta update to see if it fixes this
