### ISSUE TITLE
Suggestion: (option for) climbing up to three blocks high

### ISSUE THREAD

**Issue by Delocca** [jrbudda/minecrift#240]
This would work somewhat similarly to ladder climbing, you put both hands over the edge of the wall and pull down, then pull a bit behind to get your legs up the wall?
Of course it would allow climbing fences too. Pure awesomeness!
I know from using the Smart Moving mod that vanilla servers don't reject small climbs like this.

**Comment by Techjar** [comment]
This is one of those room scale movement things that are somewhat tricky to do right, so we'll see.

**Comment by jrbudda** [comment]
I don't really forsee implmenting this, requires button presses.
