### ISSUE TITLE
[1.10.2 v6] Both eyes see the same image

### ISSUE THREAD

**Issue by TheUnlocked** [jrbudda/minecrift#244]
In the game, it looks like there's a copy of everything slightly to the side, which I can only assume is caused by the game showing both of my eyes the exact same thing. I don't know if this is a bug or if I'm just being an idiot and there's an easy fix, but I thought I'd bring it up. I can play by keeping one eye closed, but that's really annoying to do.

**Comment by jrbudda** [comment]
There is a steamVR beta update today that may fix this

**Comment by CodeF53** [comment]
I have the newest steamVR beta and still have this issue.

**Comment by jrbudda** [comment]
@CodeF53 this issue is 3 years old and was solved by Valve. Open a new issue under the correct version of vivecraft with a full description of your problem
