### ISSUE TITLE
force open keyboard?

### ISSUE THREAD

**Issue by TakeyaSaito** [jrbudda/minecrift#246]
i cannot find anyway to do this right now but it would be amazing to have a way to force open the keyboard, like on the inventory i cannot search the NEI mods for recipes because i cannot type, unless there is already a way to do this that i am missing? i think ideally would be to be able to set a key to open the keyboard

**Comment by Techjar** [comment]
Hold left grip and press left menu.

**Comment by TakeyaSaito** [comment]
oh, well F me i did not know that, thanks!
