### ISSUE TITLE
vivecraft 1.10 not detecting forge

### ISSUE THREAD

**Issue by ghost** [jrbudda/minecrift#247]
Hi the installer is not letting me install with forge support, what version of forge do i need installed to get it to give the "install with forge option"?

**Comment by TakeyaSaito** [comment]
1.10 does not support forge i believe

**Comment by ghost** [comment]
some mods (very few) are not updating but tons have (and ofcourse there is the new ones like psi that are not on 1.7.10, cant wait to try that in vr)
https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A572&filter-sort=popularity
seems like most of the well used mods are on 1.10

**Comment by TakeyaSaito** [comment]
yeh im pretty sure we all want forge on 1.10 really badly but oh well =( maybe someday

**Comment by ghost** [comment]
The link i posted will take you to the mods for 1.10
official site for forge https://files.minecraftforge.net/ which has the 1.10 forge files,
The issue isnt that there is no forge for 1.10 but that vivecraft installer is not detecting the forge install and so will only install the vanila minecraft experience _shudder_ im guessing its setup to only detect 1 version of forge...but no idea what version, or we need to do something to the files to detect it. 
i was planning to do a complete windows reinstall next week, i may do that tonight and see if that fixes it (my android developer enviroment has had some issues so that may be related)

**Comment by TakeyaSaito** [comment]
no Vivecraft itself does not support forge on 1.10, that is what i meant

**Comment by Techjar** [comment]
Yeah, no Forge support on 1.10 Vivecraft right now. Probably will happen in the future, but it's a huge pain, just like it is on 1.7.

**Comment by ghost** [comment]
oh, well that explains why i cant get it to work, thats crazy though minecraft with out mods is awful. heres hoping the developer can get it sorted soon (not meaning that as entitled or anything, just guessing the lack of forge is a priority to fix)

**Comment by ghost** [comment]
@Techjar ok, shame though understandable. I will majorly miss playing minecraft in vr. vivecraft will be missed.

**Comment by Techjar** [comment]
Forge support is definitely on the todo list, but it requires us to basically re-implement all of the Vivecraft modifications from scratch, due to it being a different code base. And then there's all the mod compatibility issues to deal with. So, it will happen eventually, just not soon.

**Comment by ghost** [comment]
yeah a ton of mods had to redo everything to go to 1.9+ i cant play vanilla anymore though (been minecrafting since its first release and vanilla just well...ewww lol
hunting round for alternatives for now, or i may put minecraft aside for a few weeks and see where vivecraft is then. 
i thank you for many happy hours of 1.7.10 vr minecraft though, im not sure i can go fully back to flatscreen lol....damn we get spoiled these days
