### ISSUE TITLE
ViveCraft Crashes on launch?

### ISSUE THREAD

**Issue by axleman1011** [jrbudda/minecrift#25]
I recently did a fresh install of minecraft and immediately installed vivecraft following the directions and when i go to launch the game it immediately crashes. Restarting & another fresh install didn't do the trick, i'm wondering if it's a problem with some leftover drivers from when i played mincrift in the DK2 days? Has anyone else had an issue like this?

**Comment by jrbudda** [comment]
need your launcher log, it'll show the crash cause.

**Comment by LordSutter** [comment]
Same problem here, doesn't seem to matter which profile.

[crash-2016-06-01_22.01.18-client.txt](https://github.com/jrbudda/minecrift/files/293321/crash-2016-06-01_22.01.18-client.txt)

**Comment by jrbudda** [comment]
could you paste the whole launcher log including the startup? looks like something is amiss with it trying to initialize the keyboard overlay in SteamVR

**Comment by axleman1011** [comment]
Sure, here is my log

[crash-2016-06-02_11.40.08-client.txt](https://github.com/jrbudda/minecrift/files/293793/crash-2016-06-02_11.40.08-client.txt)

**Comment by jrbudda** [comment]
That's just the crash dump, the whole log would be better, although in your case axelman1011 it looks like one of the libraries did not download properly.

**Comment by axleman1011** [comment]
Ok thanks for that info, I did some testing and it turns out that my campus wifi was blocking some of the libraries from downloading. Connecting my computer to my phone's hotspot did the trick and I'm now enjoying Minecraft in VR. thanks for your help Buddha and thanks for the frequent updates to the mod!
