### ISSUE TITLE
Vivecraft 31r4 Crashing on World load

### ISSUE THREAD

**Issue by AlanRoberts91** [jrbudda/minecrift#250]
[Vivecraft 31r4 crash-2016-11-13_15.00.38-client.txt](https://github.com/jrbudda/minecrift/files/588069/Vivecraft.31r4.crash-2016-11-13_15.00.38-client.txt)
I can't seem to get a world to load. It just crashes each time. I downloaded version 30 and it works just fine.

**Comment by jrbudda** [comment]
Ah that one. In your .minecraft directory find a file called usercache.json and delete it and that should do it.

**Comment by AlanRoberts91** [comment]
That Totally fixed it!
