### ISSUE TITLE
vivecraft + ftb infinity crashes on launch

### ISSUE THREAD

**Issue by lpuo** [jrbudda/minecrift#251]
Hi, i have followed the instructions but keep getting the same crash as soon as i launch the game.  down here is the log. i tryed to change the version of optifine from the leatest got on the website to the one written in the log (OptiFine-1.7.10_HD_U_D1.jar) but still same error, even reinstalling vivecraft.
what am i doing wrong? ftb infinity runs perfectly smoothly so it shouldn't be an issue, i guess.

https://gist.github.com/9b09c38822d6544a07ae0dc0208b5087 [moved into gist for readability]

**Comment by Techjar** [comment]
Do not install OptiFine separately, it's included in Vivecraft.

**Comment by lpuo** [comment]
Thank you, will try as soon as I can and post the results (sorry for late reply) :)
