### ISSUE TITLE
[Request] FOV reduction comfort option (like google earf VR)

### ISSUE THREAD

**Issue by JereTV** [jrbudda/minecrift#253]
If you want to play on a server that doesn't allow you to teleport and you have to use the joystick movement thing. You should make it so it limits your field of view to a small circle. (Kind of what google earth did) This reduces motion sickness and will make it more comfortable to play

**Comment by jrbudda** [comment]
Interesting, I've been meaning to check out the new google earth VR, I'll take a look.

**Comment by jrbudda** [comment]
OK I have to admit I turned that setting off immediately as it ruins the immersion. Do you find the reduced FOV significantly helps while in 'tilted' view?

**Comment by Techjar** [comment]
Google Earth VR's FOV reduction is some fancy renderer, but we could achieve the same effect by just rendering a black overlay texture to the screen. It shouldn't be hard to do either. Of course we would add a comfort mode setting to toggle it.

**Comment by jrbudda** [comment]
Done
