### ISSUE TITLE
Grey/Red screen on entering map

### ISSUE THREAD

**Issue by ZavinacCiarka** [jrbudda/minecrift#254]
Hello.  Just entered the game for first time.
HUD works (also inventory, books) but the world is not displaying.

http://i.imgur.com/Lzlwv8V.jpg

Thanks for any help.
I am sorry if this is wrong place to ask.

**Comment by jrbudda** [comment]
any errors in your console? which version are you playing?

**Comment by ZavinacCiarka** [comment]
1.7.10 followed tutorial on vivecraft website. let me check the log..

**Comment by ZavinacCiarka** [comment]
none of them. just missing textures for mods. I will try again, without mods

**Comment by ZavinacCiarka** [comment]
it works without any mod installed. So I will try them one by one and will reply tomorrow.
Thank you for fast response.

**Comment by jrbudda** [comment]
Oh, yes there's some incompatible Forge mods out there. Please let me know which one it is.

**Comment by ZavinacCiarka** [comment]
Hello. I tried them one by one and ind the end, it was

ProjectRed-1.7.10-4.7.0pre12.95-Base
ProjectRed-1.7.10-4.7.0pre12.95-Lighting

From ProjectRed, I had only those two only for industrial lightning design.

**Comment by Techjar** [comment]
That's odd, I use those in my mod pack and they work fine. I suspect your game may have been soft-crashing for another reason.

**Comment by ZavinacCiarka** [comment]
Do you have newer versions of their .jar files?

**Comment by ZavinacCiarka** [comment]
it's not crashing, see picture in OP.

**Comment by Techjar** [comment]
I am using a custom build, but I have used the release version (the version you have) and it works fine.

**Comment by Techjar** [comment]
Ah, hmm. I see. That is rather odd. I'm not sure what would cause the screen to turn gray. Perhaps we have a regression with mod compatibility? I haven't actually tested it on the current Vivecraft release.

**Comment by ZavinacCiarka** [comment]
Have you modified projectred config files? Im just guessing..

**Comment by Techjar** [comment]
No, not in a way that would affect this. Can you reproduce the issue by installing just those mods and starting a new world?

**Comment by ZavinacCiarka** [comment]
Allright. Give me a minute.

**Comment by ZavinacCiarka** [comment]
1. copied projectred core&lightning mods into minecraft/mods folder
2. run steamvr
3. run jburda vivecraft 1.7.10, java 8  x64
4. create new world
5. http://i.imgur.com/7SuUlVr.png  
6. I have tried to change things in video options (opengl on/off, quality fast/smooth) but without success

**Comment by Techjar** [comment]
Hmm, strange, I've used that mod before. I'll have to test it again later. It's like something is fucking up the depth buffer, so only the UI (which ignores depth) renders, but I'm not sure where the gray is coming from. I'm only speculating though.

**Comment by ZavinacCiarka** [comment]
I have also tried the change the Render Settings parameters, but no avail.

```
##########################################################################################################
# Render Settings
#--------------------------------------------------------------------------------------------------------#
# Contains settings related to how things render in-game.
##########################################################################################################
"Render Settings" {
    # If set to false, flat wire textures will be used for logic gates. Significant performance improvement.
    B:"3D Logic Wires"=false

    # Number of lights to render, -1 for unlimited
    I:"Light Halo Render Count"=-1

    # If set to false, routed pipes will not render routing fx such as bubbles and lasers.
    B:"Routed Pipe FX"=false

    # If set to false, gates will be rendered in the TESR rather than the WorldRenderer.
    B:"Static Gates"=false

    # If set to false, wires will be rendered in the TESR rather than the WorldRenderer.
    B:"Static Wires"=false
}
```

**Comment by jrbudda** [comment]
should be fixed in 33r2 https://github.com/jrbudda/minecrift/releases

**Comment by woutwoot** [comment]
I have this same issue with the latest build. I'm trying to find out which mod is causing it for me...

**Comment by ZavinacCiarka** [comment]
Thank you very much for caring.
I will try tomorrow and then confirm if it works on my setup
