### ISSUE TITLE
Any plans for Google Daydream

### ISSUE THREAD

**Issue by JDHalm** [jrbudda/minecrift#255]
It seems cardboard works with this, are there any plans to set up Daydream controller compatibility?

**Comment by jrbudda** [comment]
Hadn't looked at it before now. TBH this is something that RiftCat would likely want to include support for so its SteamVR compatible. I'm not sure it's got enough buttons tho.

**Comment by JDHalm** [comment]
Yeah it doesn't have many. Great work here.
