### ISSUE TITLE
Roomscale rotation and movement scaling causes problems

### ISSUE THREAD

**Issue by jpfx1342** [jrbudda/minecrift#257]
I've encountered a problem when combining world rotation (either manually or via walkabout) with roomscale movement scaling. As long as you keep movement scaling at 1.0 *or* keep the world rotation at 0 degrees, there don't seem to be any problems, but as soon as you do both, the game seems to start getting confused about where your hands actually are. Specifically, the teleport line and cursors act as if your hand is somewhere it isn't. The teleport line tends to extend from somewhere near your hand instead of from the end of it.

I am using Forge with the FTB Inventions pack, however, I was also able to reproduce it in vanilla in an earlier game. (Though I didn't understand what caused it at the time.)

**Comment by Techjar** [comment]
I'm not sure how moving the room at arbitrary speeds could break the interpolated room origin. That is odd... I'll test it later.

**Comment by jrbudda** [comment]
order of operations issue somewhere in the roomscale api. that's the in-room walk multiplier stuff finaltransmit added, I've never really personally tested it.

**Comment by Techjar** [comment]
Oh, you mean that scaling. Yeah, it's definitely an issue with the order of transforms. Math is hard.

**Comment by jpfx1342** [comment]
It took me a while to set up a build environment and actually get it to compile, but I was able to sort the issue out. It was just a transformation order thing. Since most of the code uses the functions I fixed, this should sort out most of the issues with roomscale movement scaling. (It fixed everything I could find.)

**Comment by jrbudda** [comment]
Oh wow thanks. If you had come to the discord I could have given some pointers on the build environment. Thanks for the fix!
