### ISSUE TITLE
[Request] Google Earth VR like locomotion

### ISSUE THREAD

**Issue by fungiboletus** [jrbudda/minecrift#258]
Hei,
It would be really nice to fly like in Google Earth VR. Also to be able to grab the floor and slide it.

**Comment by jrbudda** [comment]
Minecraft would never stand up to moving that fast. You can already fly.

**Comment by Techjar** [comment]
To clarify what he means by that: implementing such a feature would allow you to move so quickly across the world as to cause Minecraft to freeze for extend periods when generating chunks, which just would not be very fun or useful.
