### ISSUE TITLE
[Forge Mod] Starminer Compatiblity

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/minecrift#259]
Is there any chance of getting Vivecraft to play nice with the Starminer mod?

It's a mod that adds these weird floating planet-things full of ores to worldgen. They have their own gravity field, and so "up" changes direction as you move around.

It's finicky even in an otherwise vanilla game of Minecraft, like it's hard to shoot a bow, because the arrow wants to shoot out of a weird place when you're in non-standard gravity, but when using Vivecraft at the same time, it gets REALLY weird. Like when standing on the side of a planet, your view is still Overworld-standard-upright, and your face is literally inside the rock with your Blue Circle Buddy on the "ground" like three blocks behind you, and the crosshairs point off your controller at a weird angle...

I have probably sent you to twitching on the ground, foaming at the mouth at the thought of trying to make Vivecraft work together with this mod. Which affects player point-of-view. And hasn't been updated in a year or two. And is glitchy even with some of the vanilla mechanics. And which people have never heard of. And whose main page is in Japanese.

But since both mods affect the player's point-of-view in some way, I figure there's at least a chance (a very very very small chance) that you might have some value or setting or other programming-related word that you could tweak a bit to make it stop conflicting. Like changing an ID of a new block so it stops conflicting with another mod that uses the same ID for its own new block.

Probably not gonna work, but I figure there's no harm in asking...

**Comment by Techjar** [comment]
That mod heavily modifies the vanilla render code in the same places we do, so there's no way it could ever be compatible. Minecraft wasn't even really designed to handle what that mod does (or what this one does), hence why it's a bit buggy even in vanilla. We did encapsulate its ClassTransformer so it would stop crashing the game, hence why you can actually load it, but of course its rendering changes aren't happening, resulting in the "standing on the side of a planet" thing. That's the extent of compatibility it's going to get, sorry.

**Comment by Chimera245** [comment]
I figured it would be something like that...

Oh well, now I know, and knowing is half the battle! *rides off into the sunset with G.I. Joe characters*
