### ISSUE TITLE
Scroll function in mods

### ISSUE THREAD

**Issue by jmaccini** [jrbudda/minecrift#26]
So I was checking out a few modpacks now that you implemented forge again (thanks!!). I noticed some mods have scroll bars in their menus/books and nothing seemed to work for scrolling. SteamVR has that touchpad scrollwheel feature which is pretty awesome, so it would be cool if that worked, but I'd settle for being able to grab the scroll bar with the trigger as well.
I think the controls menu option has the same issue if you don't want to load up a modpack.

**Comment by jrbudda** [comment]
being able to use the left touchpad to scroll is on my to-do list.

**Comment by jrbudda** [comment]
right touchpad as scrollwheel is now a thing in v18.

**Comment by jmaccini** [comment]
You're a hero!
