### ISSUE TITLE
Dinner Bug: Can't swing sword to attack

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/minecrift#263]
I can no longer hit things by swinging my Vive wand at them. Pointing the crosshairs and pulling the trigger works fine, as if I had some short-range unlimited-ammo sword launcher. Won't work on Hostiles or Passives.

I could use it earlier just fine, but all of a sudden now I can't, and the ability has not come back after restarting the world, the launcher, or my computer.

**Comment by jrbudda** [comment]
Did you turn it off in the options?

**Comment by Chimera245** [comment]
No, I even toggled it off and then back on, for good measure.

**Comment by jrbudda** [comment]
still can't reproduce this.

**Comment by Chimera245** [comment]
Update-- I could swing-attack with a vanilla iron sword. I've been using Tinker's Construct swords for so long, I just didn't notice vanilla ones were working... I'll try making a creative world and testing out all the weapons I can, to see if it's just Tinkers that's bugging out, or if other mods are acting weird too.

This would explain why it suddenly stopped working for me... I started with vanilla weaponry in this world, then upgraded to Tinkers' later. I think that's about when I stopped being able to swing-attack...

**Comment by jrbudda** [comment]
yea that'll do it. If their items don't inherit from ItemSword you won't get the reach. They should still work if you're close enough tho, at least on hostiles.

**Comment by Chimera245** [comment]
Literally just found that out... It seems everything from all mods works with a couple exceptions... one of which is the sword I've been using for three quarters of my time in this world... 

So, false alarm, I guess?

Just in case anyone else cares, I found out that Tinkers' Non-Longsword swords would not properly work (rapier, heavy sword, etc.) without literally being inside the enemy, and would not work on animals, and also the Draconic Staff of Power from Draconic Evolution. The ridiculously overpowered combination sword-axe-shovel-spatula won't hit enemies more than like two feet away, and is now animal-friendly.

**Comment by jrbudda** [comment]
I have no way to detect from within minecraft what is a sword in a mod, so it just shows up a general item. Not sure how I could ever fix that without creating a massive forge-item-vivecraft-database with every item from every mod and what it is

**Comment by Chimera245** [comment]
Yeah, honestly, I think it would be easier for Tinkers' to just make all their swords count as swords in the game. (Of course, I know next to nothing about programming, so there could be a reason for it.) It might have to do with some of the other sword types doing other stuff on a right-click? But the heavy sword I've been using defends like the vanilla swords to, so I'm not sure what's up with that...

**Comment by jrbudda** [comment]
this may partially fix the issue with tinker's specifically. the rendering is still all wrong but the roomscale swing should maybe work for some items.
[vivecraft-1.7.10-Vivecraft-jrbudda34-installer.zip](https://github.com/jrbudda/minecrift/files/665326/vivecraft-1.7.10-Vivecraft-jrbudda34-installer.zip)
