### ISSUE TITLE
Keyboard-press controller binding not working

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/minecrift#265]
If I assign a button on the Vive wand to be a keyboard press, it doesn't work when I press that button on the wand. I can push the actual key on the actual keyboard and it works just fine. And I made sure the Minecraft window was in focus.

I'm talking the option that prompts you to actually hit the key to tell it which one when you select that option, "keyboard-(press)" with a little box next to it, not the ones that say "keyboard-shift" etc.

**Comment by jrbudda** [comment]
Try it with keyboard-hold. I think the problem here is something to do with the controller buttons processing at 90hz while the game logic runs at 20hz.

**Comment by Chimera245** [comment]
Ah, I didn't think of that. Next time I'm on, I'll set it up that way and see what happens.

**Comment by Techjar** [comment]
Yeah I'll see about moving the button presses to the input tick handler.

**Comment by Chimera245** [comment]
That worked!
