### ISSUE TITLE
[Request] locomotion like in Climbey

### ISSUE THREAD

**Issue by headjump** [jrbudda/minecrift#266]
The game Climbey lets you hold the side-buttons on the remotes and when then moving your arm up and down (like when running in real life) the character moves in the direction of the remotes.

This is the best walking feeling I ever experienced in a VR game by today!

**Comment by jrbudda** [comment]
We already have a run-in-place locomotion in the game.

**Comment by Techjar** [comment]
Yeah we do,. Also Climbey moves in the direction of your head, not the controllers.

**Comment by headjump** [comment]
Sorry, I missed this option, thanks.

On climbey: You can change the direction to "controller" in the setup - I did it immediately and it feels quite "natural" 😃

**Comment by Techjar** [comment]
Oh, good to know.
