### ISSUE TITLE
Dinner Bug: Virtual Keyboard Summoning

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/minecrift#267]
(I knew I was forgetting one...)

I can't seem to bring up the in-game keyboard. It's supposed to be grip+menu, right? Whenever I try, hitting the menu button just exits whatever menu I was wanting to type something in.

**Comment by jrbudda** [comment]
yup, maybe I broke it with the all the button mapping changes, I don't think I tested it with a screen open.

**Comment by jrbudda** [comment]
is left grip still Sneak for you?

**Comment by Chimera245** [comment]
Yes. Left grip works fine for sneaking (though if it matters, I have it set as "keyboard-shift" instead, so I can use it to shift-click items in my inventory in addition to sneaking).

Also if it matters, the menu button works fine for pausing the game.

**Comment by Techjar** [comment]
You don't need to set it has keyboard-shift, we already handle that.

**Comment by jrbudda** [comment]
yea put it back as sneak and keyboard should work too, i changed it from being hard-coded to the grip to actually following the Sneak button around like the controls diagram says.

**Comment by Techjar** [comment]
Not to mention it also presses shift using the awt.Robot stuff, when a GUI is open.

**Comment by TrypChangeling** [comment]
I'm having the same problem in v33, even if I reset all my vr configs.

The keyboard comes up just fine with no guis open, but trying to open it with anything else open just closes the GUI.

**Comment by jrbudda** [comment]
yea im dumb

**Comment by jrbudda** [comment]
should be fixed, back hard-coded to grip

[vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip](https://github.com/jrbudda/minecrift/files/663440/vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip)

**Comment by Chimera245** [comment]
That did it! Thanks!

Though, I should point out that, as a minor graphical quirk, now my hands are rendered backwards. They still perform properly, and hold the correct tools/hotbars, but now the left hand looks like the right and vice-versa.

**Comment by jrbudda** [comment]
oh god what did I do now

**Comment by jrbudda** [comment]
ok its not me this time. What I did do was fix the arms being upside down. I just checked a with a asymetrical skin and they are rendered correctly now.
