### ISSUE TITLE
Inverted Eye stencil

### ISSUE THREAD

**Issue by Kiefy** [jrbudda/minecrift#270]
**System:** SteamVR beta, Win10 x64, i7 2600k, 16 GB, gtx1080 (376.33 driver)

**Problem:**
Using the [Asparagus Farm pack](https://www.reddit.com/r/Vive/comments/4vjqm9/minecraft_asparagus_farm_modded_server/) from your list of [Vivecraft servers](http://www.vivecraft.org/server-listings/) makes my eye stencil flip inside out. (Black Inside lens area, Rendering outside)
![I'm Blind!](http://image.prntscr.com/image/735013f33d674e7e94e9e0ce81a5074f.png)

It seems to be a bit random. sometimes it's fine, sometimes both eyes black, sometimes only one.

Occurs in both the pack-recommended ViveCraft v33, and the latest v35.

Disabling the Eye stencil feature fixes it.

It's fine without mods. and even with a lot of mods. but the full pack almost guarantees stencil inversion. but due to the random nature of the glitch, I wasn't able to pin it down to a specific mod. Probably coincidental, but i've seen it work when all but the following were not present:

* ClimateControlToMystcraft-0.2.jar
* Railcraft_1.7.10-9.12.2.0.jar
* RTG-1.7.10-1.0-snapshot-1.jar
* secretroomsmod-1.7.10-4.7.1.413.jar
* Streams-0.2.jar
* twilightforest-1.7.10-2.3.8dev.jar
* VivecraftForgeExtensions-1.7.10-0.2.2.24.jar

**Edit:**
Tried disabling all my system tray apps like MSI Afterburner. no help.

Made a video to show the problem. (Happens at 03:15)
https://dl.dropboxusercontent.com/u/1315574/eyestencilbug.mp4
Log: https://hastebin.com/gutujemila.md

Also. Some mods like Journeymap don't like Optifine. Is it possible to disable?  for science!

**Comment by jrbudda** [comment]
Optifine cannot be disabled, it's baked in. This is the second report about the eye stencil, we'll look into it.

**Comment by jrbudda** [comment]
see if this fixes it please.

[vivecraft-1.7.10-jrbudda-35r2-installer.zip](https://github.com/jrbudda/minecrift/files/706412/vivecraft-1.7.10-jrbudda-35r2-installer.zip)

**Comment by Kiefy** [comment]
The first load worked! 👍
![\o/](http://image.prntscr.com/image/74f61377d99046789b89c42eaf1efa6b.png)
Are these the right way round?  Doesn't the cut out part usually happen at the nose area?

I don't really know how it works. just going off the shape of the lenses themselves.
![Inside cut](http://image.prntscr.com/image/72102e82aa4043b6a0194a691a1f485a.png)
Amazing work you're doing here. Thank You!

Edit: Yeah, I found this image on google. Not that you need to see it :P
![vivecraft](http://i.imgur.com/QKy5nLV.jpg)

**Comment by Techjar** [comment]
Wow, I'm not sure what to say... your eye images are reversed. Are they like that in the headset? Check the SteamVR display mirror.

**Comment by Kiefy** [comment]
heh, I Didn't notice that the l/r was swapped too. but it's not like that in the HMD. It's running great!
![Mirror](http://image.prntscr.com/image/90cc5e41fe8c4c87a7b645ef59d27997.png)

**Comment by Techjar** [comment]
That is weird...

**Comment by jrbudda** [comment]
Did I reverse the display mirror eyes when I changed it to use the eye tex's?

**Comment by jrbudda** [comment]
Yup.

**Comment by jrbudda** [comment]
That'll be fixed in the next release it only affects the display mirror in dual mode.
