### ISSUE TITLE
New Minecraft launcher failing to launch VIvecraft 1.7 w/FTB

### ISSUE THREAD

**Issue by nyasara** [jrbudda/minecrift#272]
I use the FTB Infinity Evolved mudpack with Vivecraft.  Was working fine last night.  Today I try to started Minecraft and there had been an automatic update to the Minecraft launcher.  The profile for Vivecraft 1.7 w/FTB is crashing out.  The Vivecraft 1.11 profile is working fine.

http://pastebin.com/iS7539KC has the tail end of the output when I launch and it errors out.

**Comment by jrbudda** [comment]
Could you try installing again? there's actually no vivecraft code in that crash report its all Forge and the CoreModLoader.

**Comment by Techjar** [comment]
I also notice the word "game" on each log line. This is not normally in the output. Are you using a third party launcher? We only officially support Mojang's launcher, as trying to do anything about the various quirks of third party launchers is impossible.

**Comment by nyasara** [comment]
As I said, it appears that the vanilla Minecraft launcher has updated. I've been using the vanilla, and last night it had been dramatically updated, including launching a whole new style of independent log window. Perhaps I'm getting A/B tested or something, if you're not seeing that. I can try reinstalling tonight and will update with how it goes.

**Comment by Techjar** [comment]
Are you talking about the launcher that looks like this?
![launcher](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/a/ac/2016Launcher.png)

If so, that is the new launcher. I thought it worked the same as the previous one, just with a different GUI. If it is that, try the second one on the list on this page: https://minecraft.net/en-us/download/alternative

**Comment by nyasara** [comment]
Getting the old launcher, reinstalling Forge, then Vivecraft for 1.7.10+Forge, then updating the profile back to point at the FTB Infinity Evolved location has worked successfully.  

Forgetting to replace my quick launch icon and having to do that all a second time when the new launcher reasserted itself was a problem but not your fault.

Thanks for all the help.  You can close, though I would recommend a note on forums/instructions to let others know.
