### ISSUE TITLE
[ISSUE] Inherits properties from and unknown version error

### ISSUE THREAD

**Issue by BroHawk69** [jrbudda/minecrift#274]
When trying to launch the Forge version, I get an error saying "The version you are trying to play inherits properties from and unknown version" What does that even mean and how can I fix it? Also tried clean installing both Minecraft and Vivecraft, but not Forge itself. 
My crash log:
 Failed to download file. forge-1.7.10-10.13.4.1614-1.7.10.jar
Name: forge-1.7.10-10.13.4.1614-1.7.10.jar
URL: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar
Error details: HTTP 404: Not Found
Filename on disk: 5532-b2bf-dadf-c592
Path: C:\Users\minec\AppData\Local\Temp\5532-b2bf-dadf-c592
Exists: file

**Comment by jrbudda** [comment]
if you clean install minecraft you have to reinstall forge.

**Comment by jrbudda** [comment]
This is usually a launcher problem and not vivecraft so closing.
