### ISSUE TITLE
iOS + android versions [Idea]

### ISSUE THREAD

**Issue by Terraria-Lord** [jrbudda/minecrift#276]
I have been unable to launch vanilla AND modded vivecraft on my pc because APU reasons.
Solutions? a free Android / iOS app version of vivecraft PC including:
- launcher with a mcversion selection, vivecraft version selection, and mods can be added from iTunes (or if you are using android, download from the internet)
- support for bluetooth controllers(wiimotes, wii u pro controllers, xbox one elite controllers, 3rd party bt controllers and possibly HTC Vive controllers(I have never owned a vive so i dont know if these pair with bt or directly to the base stations.))
- [android only] select mod directories(requires restarting app)
anyway, just thought i would say this neat idea, because i cant play minecraft in VR right now. :(

**Comment by jrbudda** [comment]
minecraft pocket edition does not support mods.

**Comment by Techjar** [comment]
I believe they mean the desktop version ported to iOS/Android, not MCPE. This is simply not possible, making Minecraft work on mobile devices requires completely rewriting it from the ground up (for both code compatibility and performance reasons, hence why MCPE is a thing), and that is far beyond the scope of this project. Not to mention, that's probably intellectual property theft...
