### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by 8332** [jrbudda/minecrift#278]
Hey guys, I've checked FAQs and such and I haven't found a solution to this, so hopefully I'm not oblivious and didn't overlook it, but...
The 1.11.2 version works perfectly fine for me.
The 1.7.10 version with forge does not. I have no mods installed besides what comes with Vivecraft, and I have no shaders on, but whenever I pull up a world (i.e. the main menu works fine too), the world is completely black, _but I can still see the GUI_. I can tell that the game is still running though because I can hit blocks and it will still make the audio for that block (e.g. I can tell there's dirt beneath me because if I face downwards and hit the ground, it makes the noise of hitting dirt). I've tried making multiple new worlds, so I doubt that they all accidentally spawned me underground or something. If you guys need a log, let me know how I can access one.

**Comment by Techjar** [comment]
Go to .minecraft/logs and supply us with latest.log and fml-client-latest.log. Please upload them in a zip file.

**Comment by 8332** [comment]
[Logs.zip](https://github.com/jrbudda/minecrift/files/949809/Logs.zip)

**Comment by 8332** [comment]
What's the scoop on this?

**Comment by 8332** [comment]
Can I have an update please? Even if you haven't resolved it, I'd like to know where it stands.

**Comment by jrbudda** [comment]
Oh sorry, forge is usually techjar's thing. I assume you still have this problem with the latest version of Vivecraft 1.7.10? And only when installed with the Forge option? Is that with or without shadersmod?
 There's nothing in the these error logs that indicate a problem after the world is loaded. Have you tried a clean install of minecraft? Have you tried changing any of the VR Rendering options such as eye stencil or shaders to see if it makes any difference?

**Comment by jrbudda** [comment]
Ah I see from the log its Forge+Shadersmod. Please try with just Forge, or see if changing any shaders options fixes the issue.

**Comment by 8332** [comment]
It worked!! Thank you so much; I'm so excited to use it!

**Comment by darthvader45** [comment]
Weird, I have a similar issue, yet cannot see the GUI.  Will try lower shaders like Medium instead of Extreme.
