### ISSUE TITLE
1.10 Crash when joining world with newer versions of cofh core installed

### ISSUE THREAD

**Issue by gigafunk** [jrbudda/minecrift#282]
CoFHCore-1.10.2-4.1.8.12-universal.jar breaks vivecraft when joining single or multiplayer world it boots up and menu is all fine. when you make a world or join server is when it happens.
https://minecraft.curseforge.com/projects/cofhcore/files/2441735
version 1.10.2-4.1.7.11 works.

Installed mods for these logs are just CodeChickenLib-1.10.2-2.5.9.283-universal  and the newest cofh core--CoFHCore-1.10.2-4.1.10.14-universal.jar-but 12 is the first version with the issue.

[crash-2017-07-09_04.00.01-client.txt](https://github.com/jrbudda/minecrift/files/1133696/crash-2017-07-09_04.00.01-client.txt)

not sure if connected but this bit of code changed 13 days ago, the day 12 broken version came out.
https://github.com/CoFH/CoFHCore/commit/a5f021c816f791c83f3ce338992c3ca631d00fed
this changed 16 days ago
https://github.com/CoFH/CoFHLib/commit/53a620ad67a9a1fa95249cfe1ec30bd5f662e328
and this 
https://github.com/CoFH/CoFHLib/blob/d4c026b10d0006a53cebc1e4f6e8ca4aaa060100/src/main/java/cofh/lib/util/numbers/OperationProvider.java
https://github.com/CoFH/CoFHLib/tree/d4c026b10d0006a53cebc1e4f6e8ca4aaa060100/src/main/java/cofh/lib/util/numbers/world       <two things under that
and finally this
https://github.com/CoFH/CoFHLib/blob/d4c026b10d0006a53cebc1e4f6e8ca4aaa060100/src/main/java/cofh/lib/util/helpers/FluidHelper.java

I think thats all the changes between the working version and the broken version

[fml-junk-earlystartup.txt](https://github.com/jrbudda/minecrift/files/1133691/fml-junk-earlystartup.txt)
[latest.txt](https://github.com/jrbudda/minecrift/files/1133692/latest.txt)
[fml-client-latest.txt](https://github.com/jrbudda/minecrift/files/1133693/fml-client-latest.txt)

**Comment by jrbudda** [comment]
I don't even see where cofhcore modifies entityrenderer, this is a weird error.

**Comment by gigafunk** [comment]
Yeah, I tested back and forth cause it didn't makes any sense. Maybe I missed an edit
The patch note says "fixed corner case of asm not firing" I figure maybe that...
Regardless, I can use the older version just figured I'd report it.  Also, code chicken library has math methods in it(i think by itys description), could it be just the way the newer version of cofh uses the chickenchunkslib?

derp derp accidentally hit close issue...derp derp nothing to see here

**Comment by gigafunk** [comment]
The patch note says "fixed corner care of asm not firing" I figure maybe that...
Regardless, I can use the older version just figured I'd report it.

**Comment by jrbudda** [comment]
Verify this fixes it.
[vivecraft-1.10.2-jrbudda-11-installer.exe.zip](https://github.com/jrbudda/minecrift/files/1134130/vivecraft-1.10.2-jrbudda-11-installer.exe.zip)

**Comment by gigafunk** [comment]
All good! Thanks!
