### ISSUE TITLE
[Forge Mod] Allomancy - Can't load into world

### ISSUE THREAD

**Issue by Jackalopalen** [jrbudda/minecrift#283]
Trying to load vivecraft with this mod: https://minecraft.curseforge.com/projects/allomancy

Installed vivecraft w/forge through the installer. Vivecraft loads just fine w/o the mod installed. After installing the mod, the game loads just fine in the forge-only profile. But in the vivecraft+forge profile, game remains stuck at 0% after selecting a world. The last line of in the output log at this point is 

>[Netty Server IO #1/INFO] [FML]: Disconnecting Player: This server requires FML/Forge to be installed. Contact your server admin for more details.

I've tried un/reinstalling vivecraft, forge, and minecraft.

**Comment by jrbudda** [comment]
What mc version

**Comment by Techjar** [comment]
Can we also have the full log?

**Comment by Jackalopalen** [comment]
1.12.1
[launcher_log.txt](https://github.com/jrbudda/minecrift/files/1235639/launcher_log.txt)

**Comment by Techjar** [comment]
No we need the fml-client-latest.log from the logs folder.

**Comment by Jackalopalen** [comment]
[fml-client-latest.txt](https://github.com/jrbudda/minecrift/files/1235672/fml-client-latest.txt)

**Comment by Techjar** [comment]
So, you're telling me you get the "This server requires FML/Forge to be installed." error in singleplayer?

**Comment by Jackalopalen** [comment]
Yes, single player, new world, survival

**Comment by jrbudda** [comment]
It might be 1.12.1 vivecraft w/ forge isnt working at all. I got allomancy to work with 1.12. Cant get 1.12.1 w/ forge to load at all with no mods. Which is weird cause I know I tested it.

**Comment by jrbudda** [comment]
This should be fixed now.

**Comment by Jackalopalen** [comment]
thanks! works now in singleplayer
