### ISSUE TITLE
DK2 Startup issues

### ISSUE THREAD

**Issue by Turpasaunoja** [jrbudda/minecrift#284]
Whenever I try to launch the game from the minecraft launcher, first the launcher says "5 mb left", then  the log window opens up, log input stays empty, and the launcher says the game crashed. latest.log doesn't have much information, see below:

_[14:47:11] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[14:47:11] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[14:47:11] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[14:47:11] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}_

Is my system incompatible, does Vivecraft not support dk2, or what else could cause this?

System Information:
CPU: AMD FX-8350
GPU: GeForce GTX 770
MoBo: Asus Sabertooth 990FX 2.0
16 GB ddr3 RAM
OS: Win 10 Home 64-bit

Also, I'm fairly certain this is obvious, but I'm trying to play 1.7.10.

**Comment by TheTrueForce** [comment]
When did you install it? Because if it was recent, Optifine changed the downloads on their website, which broke the old installers. To my knowledge, the 1.7.10 installers aren't going to get the workaround. There's a way to do it manually, but I don't know what it is.

**Comment by Turpasaunoja** [comment]
Today, and this does make sense. If anyone has a fix, please share, I will try myself also.

**Comment by jrbudda** [comment]
Did you check the FAQ for the common causes of client crash?

**Comment by Turpasaunoja** [comment]
I did, no help there though, as far as I understood.

**Comment by Techjar** [comment]
Is that really all that's in your latest.log?

**Comment by Turpasaunoja** [comment]
Yes, I'm afraid.

**Comment by Turpasaunoja** [comment]
So does anyone have a fix or a workaround?

**Comment by Techjar** [comment]
Can you get anything from the launcher output log?

**Comment by Turpasaunoja** [comment]
```
18:50:39 | launcher | main | info | Preparing to launch minecraft client for vivecraft-1.7.10-jrbudda-40r1
-- | -- | -- | -- | --
18:50:40 | launcher | main | warn | Couldn't get hash for optifine/OptiFine/1.7.10_HD_U_D1/OptiFine-1.7.10_HD_U_D1.jar from https://libraries.minecraft.net/optifine/OptiFine/1.7.10_HD_U_D1/OptiFine-1.7.10_HD_U_D1.jar.sha1: HTTP 404: Not Found
18:50:40 | launcher | main | warn | Have local file C:/Users\GODofTimewaste\AppData\Roaming\.minecraft\libraries\optifine/OptiFine/1.7.10_HD_U_D1/OptiFine-1.7.10_HD_U_D1.jar but don't know what size or hash it should be. Have to assume it's good.
18:50:40 | launcher | main | warn | Couldn't get hash for com/mtbs3d/minecrift/1.7.10-jrbudda-40r1/minecrift-1.7.10-jrbudda-40r1.jar from https://libraries.minecraft.net/com/mtbs3d/minecrift/1.7.10-jrbudda-40r1/minecrift-1.7.10-jrbudda-40r1.jar.sha1: HTTP 404: Not Found
18:50:40 | launcher | main | warn | Have local file C:/Users\GODofTimewaste\AppData\Roaming\.minecraft\libraries\com/mtbs3d/minecrift/1.7.10-jrbudda-40r1/minecrift-1.7.10-jrbudda-40r1.jar but don't know what size or hash it should be. Have to assume it's good.
18:50:41 | launcher | main | warn | Couldn't get hash for de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar from http://vivecraft.org/jar/de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar.sha1: HTTP 404: Not Found
18:50:41 | launcher | main | warn | Have local file C:/Users\GODofTimewaste\AppData\Roaming\.minecraft\libraries\de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
18:50:42 | launcher | main | warn | Couldn't get hash for com/sun/jna/4.2.1/jna-4.2.1.jar from http://vivecraft.org/jar/com/sun/jna/4.2.1/jna-4.2.1.jar.sha1: HTTP 404: Not Found
18:50:42 | launcher | main | warn | Have local file C:/Users\GODofTimewaste\AppData\Roaming\.minecraft\libraries\com/sun/jna/4.2.1/jna-4.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
18:50:43 | launcher | main | info | Checking installations.
18:50:43 | launcher | main | info | Minecraft client vivecraft-1.7.10-jrbudda-40r1 requires 18446744073709212026 bytes to download.
18:50:43 | launcher | main | info | Starting!
18:50:43 | launcher | main | info | Using default game log configuration client-1.7.xml (outputs XML)
```

This, when running for the first time since opening my computer.

**Comment by Techjar** [comment]
This has been fixed in 40r2. Thanks for the help @Barteks2x!
