### ISSUE TITLE
Vivecraft v13 Won't Launch

### ISSUE THREAD

**Issue by Enzer** [jrbudda/minecrift#29]
I click "Play", launcher does its normal thing, before going back to the normal "Play" and not actually launching Minecraft. Launcher Log appears to think nothing is wrong, but Game Output has an exception (and I don't know where the rest of the stack trace is hiding). Vivecraft's profile is set to use release version vivecraft-1.7.10-Vivecraft-jrbudda13-nohydra. Also, I am not using Forge.

[LauncherLog.txt](https://github.com/jrbudda/minecrift/files/294553/LauncherLog.txt)
[GameOutput.txt](https://github.com/jrbudda/minecrift/files/294552/GameOutput.txt)

**Comment by jrbudda** [comment]
java.lang.ClassNotFoundException: net.minecraft.client.main.Main

Would indicate that something did not install correctly. Please try again and check your launcher profile to make sure it's loading the right jar.

**Comment by Enzer** [comment]
Unfortunately I've run the installer a few times. I did my best to follow the steps [on the Reddit wiki](https://www.reddit.com/r/Vive/wiki/minecrift_for_vive#wiki_how_do_i_install) with the caveat of changing the version to Vivecraft. I just now went so far as to follow these exact steps:
1. Rename %appdata%/.minecraft to .minecraftOld to effectively uninstall Minecraft and the launcher
2. Move the launcher to C:\Users\Enzer\Downloads\New folder from G:\Minecraft\Launcher (in case this had something to do with the launcher being on another drive)
3. Run a profile with 1.7.10 in the launcher then close Minecraft (launcher set to automatically close)
4. Run vivecraft-1.7.10-Vivecraft-jrbudda13-installer.exe with default settings plus audio
5. Open launcher and edit the ViveCraft 1.7.10 profile to use version: release vivecraft-1.7.10-Vivecraft-jrbudda13-nohydra and save
6. Hit play and the same thing as before appears to happen with the same exception

I even disabled all security software just to be sure. The JSON for the ViveCraft version looks like this:
`"ViveCraft 1.7.10": {
      "name": "ViveCraft 1.7.10",
      "lastVersionId": "vivecraft-1.7.10-Vivecraft-jrbudda13-nohydra",
      "javaArgs": "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M -Dfml.ignoreInvalidMinecraftCertificates\u003dtrue -Dfml.ignorePatchDiscrepancies\u003dtrue",
      "useHopperCrashService": false,
      "launcherVisibilityOnGameClose": "keep the launcher open"
    }`

**Comment by jrbudda** [comment]
just for giggles have you tried it WITH forge?

I really can't find or think of much that would be causing this. Your java looks up to date and it all seems normal.

**Comment by Enzer** [comment]
Your giggles have been confirmed. Vivecraft only works with Forge for me.

**Comment by jrbudda** [comment]
Yea i was looking at my own logs forge vs not forge and the forge version's launchwrapper does different... stuff... loading optifine, which is where your crash is happening. Glad its working for you now.
