### ISSUE TITLE
Bow fires backwards

### ISSUE THREAD

**Issue by Velker** [jrbudda/minecrift#291]
I am not sure if I am just doing something wrong but when I fire my bow in Vivecraft, the arrow fires directly behind me. I tried changing the VR settings, but no luck. I am playing vivecraft with the Rift and using keyboard / mouse. Can someone please help?

**Comment by jrbudda** [comment]
I swear I fixed this

**Comment by jrbudda** [comment]
Yea this should have been fixed in Vivecraft 1.12.2 5-final-r2, make sure you're up to date.

**Comment by Velker** [comment]
Yep, that was the problem! I am using vivecraft 1.12.2-jrbudda-5-RC3. Sorry I will download the latest version now. Thanks so much! This mod is amazing by the way, I have been playing it non stop, its the only way for me to play Minecraft now.
