### ISSUE TITLE
[MultiMC] Minecraft refuses to launch after installing vivecraft

### ISSUE THREAD

**Issue by polyzium** [jrbudda/minecrift#293]
Using MMC 0.6.0-1154 on Win10 64bit.
Trying to install Vivecraft with forge support.
This happens when i try to run MC after installing Vivecraft with a few more additional steps below:

1. Install vivecraft by following [this manual](http://www.vivecraft.org/multimc/)
2. Because vivecraft's entry won't appear in the Version section of "Console window for etcetc", add an empty patch entry thing? ("Add Empty" button at the right)
3. Paste vivecraft's json onto that.
4. Press "Reload" and run the game.

After that, [this appears](https://i.imgur.com/s3caA5d.png)
Log:
```
MultiMC version: 0.6.0-1154


Minecraft folder is:
C:/Users/Polyzium/MultiMC/instances/Vivecraft 1.12.2/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_151/bin/javaw.exe


Java is version 1.8.0_151, using 64-bit architecture.


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Vivecraft 1.12.2' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions/vivecraft-1.12.2-jrbudda-5-final-r3-forge/vivecraft-1.12.2-jrbudda-5-final-r3-forge.jar.
```
I dunno why it wants to download it from amazon servers...

**Comment by jrbudda** [comment]
multimc 0.6 changed how instances are set up and the instructions on the site are no longer valid. Will be fixed in the future.

**Comment by polyzium** [comment]
Fixed in latest revisions of vivecraft installer, it works now.
