### ISSUE TITLE
Can't connect to VR Headset!

### ISSUE THREAD

**Issue by GuzioMG** [jrbudda/minecrift#298]
Hello,
I have a problem, because when I start Vivecraft (without Steam VR installed, but with Trinus running and connected with phone), it returns error `Render setup failed - VR Headset not found`. With installed Steam VR and running and connected Trinus, after starting Vivecraft, it starts Steam VR and after that it returns error `Render setup failed - HMD not found (108)`.
Please, help!

**Comment by Techjar** [comment]
This is an issue with Trinus, not Vivecraft, so we can't help you unfortunately. We have never used Trinus and have no idea how it works or how to fix issues with it. Sorry. If Vivecraft is giving that error, other VR games probably will as well. You should go ask the Trinus guys about it or something (they do have a support forum, right?).

**Comment by GuzioMG** [comment]
Yes. They have a support forum, so I'll ask there or I'll ask Riftcat/VRidge guys ( <--- It's the same program, but Riftcat is VRidge's server for computer and VRidge is Riftcat's client for phone), because Riftcat on my computer even don't conect with VRidge on my phone. Okay, it connect, but then it crashes.

Thanks anyway & bye!
