### ISSUE TITLE
Free Movement

### ISSUE THREAD

**Issue by cherbert** [jrbudda/minecrift#3]
Thanks for this feature. I tried a neat little trick that seemed to work quite well. I walked on the spot while moving and it seemed to work really well in fooling the brain that I was walking and thus reducing nausea. Because of the speed at which you move I was kind of forced to run on the spot to make it more realistic for my brain.

Is there anyway you can make an option to slow down the movement speed to allow walking on the spot be more feasible?

If you haven't tried it you should! :-)

**Comment by jrbudda** [comment]
There's a movement speed multiplier in the VR locomotion options, see if that does what you want.
