### ISSUE TITLE
Error with new patch

### ISSUE THREAD

**Issue by Joviangod** [jrbudda/minecrift#30]
I get this error when I run the newest version. I ran the previous versions just fine...not sure why this is broken now:

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

I did a search of this error and it seems to be a memory error. I have the min specs for RAM with VR but I never had this error before the patch....

**Comment by jrbudda** [comment]
Answered you on reddit but for posterity you need to install 64 bit java.
