### ISSUE TITLE
Vivecraft hijacks 'Latest Version'

### ISSUE THREAD

**Issue by missionfloyd** [jrbudda/minecrift#31]
After installing, profiles set to "Use Latest Version" will use vivecraft instead of the latest vanilla version.

It seems that you have build.py setting the releaseTime key to the build time. Setting it to a past date, as forge does, and specifying the vivecraft version in launcher_profiles.json should fix it.

**Comment by jrbudda** [comment]
Thank you I was wondering about that. I'm not sure if its always been that way or I broke it.

**Comment by jrbudda** [comment]
Ok i figured out the issue, it's because I had the audacity to capitalize Vivecraft in the version id. Silly me.

**Comment by missionfloyd** [comment]
Other profiles are still using the vivecraft jar when set to Use Latest Version.

Look at build.py line 55. That's the culprit. It's setting releaseTime to the current time, The launcher assumes that vivecraft is the latest version since it is indeed newer then minecraft 1.9.4.

Delete that line, and change the default releaseTime in 1.7.10.json and 1.7.10-nohydra.json to `1960-01-01T07:00:00+00:00` (for consistency) and vivecraft should move to the end of the list.
