### ISSUE TITLE
Buildcraft Engines/Quarry/Mining Well Causes Onion Effect

### ISSUE THREAD

**Issue by GeorgeBusche** [jrbudda/minecrift#311]
Upon placing a buildcraft engine, quarry, or mining well, the game seems to "drag" across the screen, almost like stamping an image 100 times across the screen following the path of my head. Sorry for such an odd description, but I honestly don't know what to call the issue. No other blocks seem to cause this issue. I've attached a screenshot below of the issue. 
![2018-06-10_20 34 15](https://user-images.githubusercontent.com/40153081/41208176-3d667312-6cee-11e8-84e6-d4b205348d80.png)

Here is a list of mods I'm running. No other mods produce this issue.
![screenshot 1](https://user-images.githubusercontent.com/40153081/41208177-42ee6b0a-6cee-11e8-868f-de929793cba5.png)

I'm using Minecraft Version 1.12.2 with Forge.

**Comment by Techjar** [comment]
I thought this was fixed with v7.

**Comment by GeorgeBusche** [comment]
Idk, but it’s been happening to me all evening. I have the latest version of Vivecraft and Buildcraft. What do you suggest?

**Comment by Techjar** [comment]
Issue moved to appropriate repository at: https://github.com/jrbudda/Vivecraft_112/issues/57
