### ISSUE TITLE
Installing Vivecraft with Project Malmo

### ISSUE THREAD

**Issue by rs4da** [jrbudda/minecrift#313]
Is there any way to get Vivecraft working alongside Project Malmo? Unlike standard versions of Minecraft, Malmo launches the Minecraft client through a shell script rather than a standard exe launcher and thus I am unable to set the game version to Vivecraft in the launcher, whenever Vivecraft installs. I am rather new to Minecraft modding, so any help would be greatly appreciated. Thank you.

**Comment by Techjar** [comment]
If the mod doesn't just go in the mods folder and use Forge, then no, there is unfortunately no way to get it working with Vivecraft.
