### ISSUE TITLE
Server issue. 

### ISSUE THREAD

**Issue by Pixeldk** [jrbudda/minecrift#32]
02.06 18:50:43 [Server] WARN Ze_SpyRo moved wrongly!
02.06 18:50:42 [Server] WARN Ze_SpyRo moved wrongly!
02.06 18:50:21 [Server] WARN Pixeldk moved wrongly!
02.06 18:50:20 [Server] WARN Pixeldk moved wrongly!
02.06 18:50:19 [Server] WARN Pixeldk moved wrongly!

Buggy teleporting with Thermos. its not generating the right configs in spigot.yml, so have to insert them myself. and it looks like its not reading them.

**Comment by fucnknown** [comment]
This is not an issue with the Vivecraft mod, it's either the plugin from jpossi https://github.com/possi/MineVive/releases or Thermos https://github.com/TCPR/Thermos/releases

**Comment by Pixeldk** [comment]
Thanks ziggrauglurr. Will add them to both.
