### ISSUE TITLE
Seated Mode: Looking around doesn't always drag the crosshairs along while Keyhole is set to 0

### ISSUE THREAD

**Issue by Mattshark** [jrbudda/minecrift#327]
##After setting the keyhole value (Seated mode options) to 0, the crosshairs stay in the center of my screen horizontally (but can be shifted up and down). This is always the case when I move my **mouse** to look around. However, when I look around with my head, the crosshairs will, on occasion, decide to completely disregard the keyhole and will stay in its geographical location even if I completely turn my head around. Slightly nudging the mouse will snap it back into place.

I am using a mouse, not a controller, to move my crosshairs.

1.12.2 Version of Vivecraft w/Forge, launched via MultiMC.

(Sorry, I couldn't figure out how to tag this as a bug)

**Comment by Techjar** [comment]
We didn't intend for the crosshair to follow the HMD while not moving the mouse, so this is working as intended.

**Comment by Mattshark89** [comment]
Most of the time, the crosshairs do actually follow the HMD. On random occasions, it does not. This inconsistency was my issue.

**Comment by Mattshark** [comment]
Most of the time, the crosshairs do actually follow the HMD. On random occasions, it does not. This inconsistency was my issue.
