### ISSUE TITLE
[Request] Look-based interaction

### ISSUE THREAD

**Issue by dark-penguin** [jrbudda/minecrift#328]
Request: implement a mouse-less, look-based interaction - like all Android games do it. The cursor should always remain in the view center, even if a menu is opened, so you take and drop items by looking at them and pressing a button.

I'm trying to play Vivecraft via Trinus/Riftcat/iVRy, which I believe must be a *very* common usecase. This introduces a considerable lag, which is somehow not so bad for the game itself, but grabbing items with a mouse is nearly impossible. On top of that, mouse sensitivity is kinda awkward when using it like this.

This should also make implementing gamepad support possible, since we wouldn't need a pointing device anymore. Which in turn would make it possible to play while standing with a wireless gamepad, instead of sitting with a keyboard and mouse.

I've made my mouse have a 0 degrees "angle of turning", so I can turn with my head or my mouse. But I still have to move my mouse up and down to interact with the world, not to mention menus. It would be much better if everything could be controlled with just my view direction - and using a mouse or directional keys for rotation (or the right gamepad thumbstick, which is even better).

**Comment by Techjar** [comment]
No, face aim is terrible.

As for gamepads, there's already a Forge mod for that.
https://github.com/ljsimin/MinecraftJoypadSplitscreenMod
