### ISSUE TITLE
Weird in-hand item rendering

### ISSUE THREAD

**Issue by fazo96** [jrbudda/minecrift#33]
Since the new update with the bow:
- torches render weird in the hand
- sometimes porkchops are invisible. Wasn't able to reproduce it after the first time...

I love your mod by the way!

**Comment by possi** [comment]
- Map doesn't appear in Hand

**Comment by ClintChil** [comment]
Sapling also placed off axis to controller.

**Comment by jrbudda** [comment]
Oh god the map rendering code is like 100 lines of opengl spaghetti. I literally had to move it out of my way when doing the bow.

Thank you for the reports, keep them coming. I'll get to them when I can. This weekend is busy.

**Comment by Enderzt** [comment]
I second the Map issues. The map seems to be backwards and or upside down. If you spin the controller in your hand you will eventually find the map but it basically takes rotating the controller in your hand at unnatural angles to find the map.

**Comment by jrbudda** [comment]
this should be better in v15. May still be some oddities, please continue to provide feedback.
