### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by cellocollin** [jrbudda/minecrift#331]
Audio issue with Vivecraft installed.  Audio redirects to main audio and does not appear in audio mixer of vive headset

**Comment by jrbudda** [comment]
Minecraft uses whatever your OS default sound device is and has no way to influence that.

**Comment by cellocollin** [comment]
IS there any way I can change my OS default sound?

**Comment by jrbudda** [comment]
Sure in Windows. Also steamvr has some kind of setting that can change your sound device when VR boots up.

**Comment by cellocollin** [comment]
Thank you, I just got it to work
