### ISSUE TITLE
Modpack (GT:NH) crashes on startup

### ISSUE THREAD

**Issue by Nayiko** [jrbudda/minecrift#343]
Hello,

I installed vivecraft on GT New Horizons, but it crashes even before opening the loading window. And it gives me this error :

-------

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 05.03.21 10:21
Description: Initializing game

java.lang.NoSuchFieldError: ForgeHooksClient_createDisplay
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:747)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1353)
at net.minecraft.client.main.Main.main(Main.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:747)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1353)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 6229972568 bytes (5941 MB) / 6401556480 bytes (6105 MB) up to 9574547456 bytes (9131 MB)
JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -Xms6G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML:
Launched Version: vivecraft-1.7.10-jrbudda-40r9-forge
LWJGL: 2.9.1
OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
GL Caps:
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 10
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: null
OpenGlRenderer: null
OpenGlVendor: null
CpuCount: 16

-------

It's weird because I already played Divine Journey with it and it worked fine.

I tried the solution on https://github.com/jrbudda/minecrift/issues/337 but it didn't work.

Anyone know how to fix it ?

**Comment by Techjar** [comment]
This looks like you've changed the Forge version to something that isn't compatible.

**Comment by Nayiko** [comment]
Reinstalling vivecraft without touching the Forge settings doesn't fix the problem.

**Comment by Techjar** [comment]
This is weird then, because that field definitely should not be missing. Is some mod doing something stupid that it shouldn't?

**Comment by Techjar** [comment]
Actually, that's not even supposed to be a field, it should be a method.

https://github.com/jrbudda/minecrift/blob/d600cbdace100dc565bc48198aa2a57f17e823a3/patches/net/minecraft/client/Minecraft.java.patch#L1460-L1462

Some mod is definitely doing something bad. I'm not even sure the error is thrown here, because Reflector is fail-safe. Seems like someone injected something stupid.

**Comment by Nayiko** [comment]
The modlist of the modpack is ->

-------

 Advanced Solar Panels 3.5.1a
* Adventure Backpack 0.9h15-GTNH
* AE2 Stuff 0.5.1.9
* AE2 Wireless Crafting Table 1.8.7.6
* AFSU 1.2.3.a
* Anger Mod 0.6.1
* AppleCore 1.3.9
* Applied Energistics rv3-beta-35
* Architecture Craft 1.7.4-GTNH
* Aroma Backup 0.1.0.0
* Automagy 0.28.2
* Avaritia 1.18
* Avaritiaddons 1.4b
* BackPack 2.2.4
* Bartworks 0.5.14
* Baubles 1.0.1.12
* Bee Better At Bees 0.3
* Better Archivements 0.1.0
* Better Builders Wands 0.8.1r92
* Better Loading Screen 1.3.26-GTNH
* Better Questing 3.0.337-GTNH
* Bibliocraft 1.11.7
* Bibliowoods 1.9/1.7/1.5
* Binnie Mods 2.0-29.5-gtnh
* Biomes o Plenty 2.1.2-GTNH
* BlockLimiter 0.52
* Blood Arsenal 1.2.1-11
* BloodMagic 1.3.3.43
* Bug Torch 1.0.2
* Buildcraft 7.1.23
* Buildcraft Compat 7.1.7
* Build Craft Oil Tweak 1.0.3
* Carpenter's Blocks 3.3.8.2
* Catwalk Mod 2.0.4
* Chisel 2.9.8
* Chisel Tones 1.0-3
* Command Block BQ Mod 3
* Compact Kinetic Generators 1.0
* Computronics 1.6.6
* Controlling 1.0.0
* CraftPresence 1.7.5
* Craft Tweaker 3.2.2-GTNH
* Crops ++ 1.3.5.3
* Custom Main Menu 1.9.2
* Default World Generator 0.1-b13
* Draconic Evolution 1.0.2r
* Electro Magic Tools 1.2.8.0
* Ender IO 2.3.1.15_beta.20
* Ender Storage 1.4.7.38
* Ender Zoo 1.0.18.3
* Enhanced Loot Bags 1.0.4
* Enhanced Portals 3 3.0.12
* Eternal Singularity 1.0.4b
* Extra Cells 2.4.6b9
* Extra Utilities 1.2.13a
* FastCraft 1.25
* Find It 1.0.1
* Flood Light 1.2.8.137
* Forbidden Magic 0.575
* Forestry 4.3.0.0
* Forgelin 1.8.4-GTNH
* Forge Microblocks 1.2.0.347
* ForgeReloaction 0.0.1.4
* ForgeReloactionFMP 0.0.1.2
* Gadomancy 1.0.8.0
* Galacticraft-Full 3.0.22-GTNH
* GalactiGreg 1.0.3
* Galaxy Space 1.1.7-GTNH
* Gendustry 1.6.4.135a
* Gravitation Suite 2.0.68u
* Gregtech 5.09.34.02
* GT Scanner Mod 1.5.9
* GT Ore Nei Plugin 1.0.8
* GT New Horizons Core Mod 1.7.00
* GT++ 1.7.05.68
* GTNH TC Wands 1.2.1
* GTTweaker 1.7.5
* Hardcore Darkness 1.7
* Hardcore Ender Expansion 1.8.7
* Help Fixer 1.0.7
* Hodgepodge 1.4.3
* Holo Inventory 2.1.5-beta
* Hunger Overhaul 1.0.2
* IC2 Nuclear Control 2.4.3a
* IFU 1.7
* IguanaTinkerTweaks 2.1.7.5
* Industrial Craft 2 2.2.2.828a
* Industrial Craft 2 Nei Plugin 1.3.1
* Infernal Mobs 1.7.2
* InGame Info XML 2.8.2.3
* Inventory Tweaks 1.59.156
* Iron Chest Minecarts 1.0.4
* Iron Chests 6.0.62.742
* Iron Tanks 1.2.0
* ItLt 1.0.2
* Jabba 1.2.7
* JourneyMap 5.1.4p2
* Kekztech 0.5.2
* Lootgames 1.0.18
* Magic Bees 2.5.5-GTNH
* Malisis Doors 1.13.2
* Mine and Blade Battlegear 1.1.1.4-GTNH
* Minecraft Forge 10.13.4.1614
* Mod Mixins 0.0.3
* Mod Tweaker 2 0.9.6.173
* Mouse Tweaks 2.4.4
* Natura 2.4.1-dev
* Natures Compass 1.3.1
* NEI 2.0.6-GTNH
* Nei Addons 1.12.15.41
* Nei Integration 1.1.2
* Nodal Mechanics 1.1.4-GTNH
* Not Enough Thaumcraft Tabs 1.1.0
* Open Blocks 1.6.3-snapshot6
* Open Computers 1.7.5.6.22
* Open Modular Turrets 2.2.11.245
* Open Glasses 1.1-GTNH
* Open Printers 0.1.0.132
* Open Security 1.0-117
* Overloaded Armorbar 1.0.0
* Pam's Harvestcraft 1.7.10-lb-1.0.2-GTNH
* Pam's Harvestcraft Nether 1.7.10a
* Project Blue 1.1.6
* Project Red-Base 4.7.0pre12.95GT
* Project Red-Compat 4.7.0pre12.95GT
* Project Red-Fabrication 4.7.0pre12.95GT
* Project Red-Integration 4.7.0pre12.95GT
* Project Red-Lightning 4.7.0pre12.95GT
* Project Red-Mechanical 4.7.0pre12.95GT
* Project Red-World 4.7.0pre12.95GT
* Questbook 2.1.1
* Railcraft 9.12.2.1
* Random Things 2.2.4
* Realistic World Gen 1.3.2
* ReAuth 3.5.0
* RemoteIO 2.4.2
* RF Expansion 3.0.29(disabled till an update is online)
* Rogue like Dungeons 1.5.1
* Resource Loader 1.3.0
* SG Craft 1.13.8
* Sleeping Bag 0.1.1
* Special Mobs 3.3.7
* Spice of Life 2.0.0-carot-beta-6
* Standard Expansion 3.0.183-GTNH
* Steve's Carts 2.0.0.19b
* Steve's Factory Manager ALPHA97-GTNH
* Steve's Factory Manager Addon 0.10.17
* Storage Drawers 1.11.5-gtnh
* Storage Drawers Wood Addons 1.1.2c
* Super Solar Panel 1.1.2
* Super Tic 1.2.1
* Tainted Magic r7.6
* TC Node Tracker 1.1.2
* Tec Tech 4.10.0
* Thaumcraft 4.2.3.5
* Thaumcraft Mob Aspects 2B-snapsh17
* Thaumcraft-NEI-Additions 1.1.0.1
* ThaumcraftNEIPlugins 1.7a
* Thaumic Bases 1.4.22.0
* Thaumic Energistics 1.1.3.8
* Thaumic Exploration 1.1.75
* Thaumic Horizon 1.2.0.1
* Thaumic Machina 0.2.1
* Thaumic Tinkerer 2.5.557-GTNH
* TiCTooltips 1.2.5
* Tinker's Construct 1.9.0.0.Build-6-GTNH
* Tinker's Gregworks 1.0.18
* Tinker's Defense 1.2.1d
* TMechworks 0.2.16.1
* Too Much Loot 4.0.3.B2
* Toro Health 1.0.0
* Translocator 1.1.2.16
* Travellers Gear 1.16.7
* Twillight Forest 2.3.8.6-dev
* Ulity Worlds 1.0.9e
* Universal Singularities Version 8.6.2
* Waila 1.5.10
* Waila Harvestability 1.1.7
* Waila Plugins 0.2.3.1-8
* Wawla 1.0.5.120
* Warp Theory 1.1.0-GTNH
* Wireless Redstone CBE 1.4.2-GTNH
* Witchery 0.24.1
* Witchery Extras 1.0.1
* Witching Gadgets 1.2.13-GTNH
* Ztones 2.2.2custom

## Libs and Cores
* AsieLib 0.4.9
* BdLib 1.9.3.109
* Brandon's Core 1.0.0.12
* CodeChickenCore 1.07.47
* CodeChickenLib 1.1.3.140
* CofhCore 3.1.4.329
* CofhLib 1.2.1.185
* Crop Loader Core 0.1.4
* Dummy Core 1.13
* Ender Core 0.2.0.39
* InpureCore 1.0.0B9-62
* Malisis Core 0.14.3
* MicdoodleCore 3.0.13-GTNH
* Mantle 0.3.2b
* MrTJPCore 1.1.0.33
* Open Mods Lib 0.10.1
* p455w0rdslib 1.0.4
* Player api 1.4
* Sponge Mixins 1.2.0
* Wanion Lib 1.8
* YamCore 0.5.78

-------

The only changes I have made are ->

- I changed the config of  Hunger Overhaul
- I deleted Hardcore Darkness

**Comment by Nayiko** [comment]
I can launch the modpack properly with Non-VR Forge. Maybe it's a problem of version compatibility ?

**Comment by Nayiko** [comment]
My latest.log if that can help ->

https://pastebin.com/g9tNZQ9c

**Comment by Techjar** [comment]
It has to be one of the mods doing something funny. If you can isolate which mod is causing the crash, I'll investigate it and try to figure out what silly crap it's up to.

**Comment by Nayiko** [comment]
I've found the mod that caused the crash thanks to https://github.com/jrbudda/minecrift/issues/318

Downgrading SpongeMixins from 1.2.0 to 1.1.0 fixed the problem. Thank you !
