### ISSUE TITLE
Jumping hurts?

### ISSUE THREAD

**Issue by Xrave** [jrbudda/minecrift#37]
I tried jumping in a two-block and three-block room space, and it takes half a heart each time. Simulate Falling is on, everything else is default open-VR options from the packaged installer in the latest release.

**Comment by Xrave** [comment]
Ahh, figured it out. I'm a bit too tall personally. if I bend down a bit i can jump no trouble. It seems being 1.8m/6ft is a bit of a disadvantage. Steve is 1.85/6ft 1, so I'm just bareeely over the limit, maybe i'll just not wear shoes. XD

**Comment by jrbudda** [comment]
Actually Steve's bounding box maxes out at 1.8m in-game, I'm clamping the 'player height' to that value, I wonder if i need to shrink that because it's still a unintentional bug.

**Comment by Xrave** [comment]
Makes sense, but yeah, I'm hitting the ceiling and taking damage, crouching a bit manually now...

I died after jumping into the ceiling like 20 times while trying to open inventory.

**Comment by jrbudda** [comment]
This should no longer happen under any situation so long as 'Allow crawling' is off...

**Comment by jrbudda** [comment]
This should be totally gone in v23
