### ISSUE TITLE
Teleporting troublesome in Thermos, dev blames your mod?

### ISSUE THREAD

**Issue by ManOrMonster** [jrbudda/minecrift#38]
Thermos often gives movement warnings and rubberbands the teleporting character. Changing the `moved-wrongly-threshold` and `moved-too-quickly-threshold` settings in spigot.yml does not fix the issue. When this was brought up, [one of the devs said](https://github.com/CyberdyneCC/Thermos/issues/382) "There is no way to get those settings to work. You're going to have to ask the mod creator to change the way they teleport players."

Now I'm guessing there's nothing you can do about this, but I thought I'd bring it up. Is it true we need Thermos to have a server that supports Forge mods? Also, is it possible to "Open to LAN" instead? Whenever I try to do that it just brings up a keyboard and chat window.

**Comment by Pixeldk** [comment]
Isnt it https://github.com/possi/MineVive we need to fix it manormonster?

**Comment by ManOrMonster** [comment]
I don't know, all I know is that I want to play this with my sons, with only me in VR, and be able to use Forge mods. The [Vivecraft FAQ on Reddit](https://www.reddit.com/r/Vive/wiki/minecrift_for_vive) says to use Thermos for Forge support, but teleporting is spotty in Thermos. I followed the instructions on that page.

**Comment by fucnknown** [comment]
Hi, I'm the one doing the main work on the Wiki. 
Spigot/Bukkit is required to use plugins. Jposs'si plugin (MineVive, https://github.com/possi/MineVive) allows using Vivecraft natively in a server, without having to give "Teleport wands" or other troublesome systems. Forge support is required for mods both in the client and the server. 
Historically there was a mixed project called Cauldron, which enabled both. 
After a lot of drama last year Bukkit became Spigot and Cauldron was discontinued. Thermos is the only project being actively improved and worked that has both Spigot and Forge. 
The plugin is the one that needs to be checked and made compatible, unfortunately jpossi hasn't answered summons or bug reports yet. Reddit user AngelMoo apparently has both working on his server: https://www.reddit.com/r/Vive/comments/4fbwyb/minecraft_vive_forge_ftb_install_kit_guide_inside/ Pixeldk is trying to reach him.

This is all edge technology and developers are working on their own free time, improvements are already coming fast, but the ones who can't code as well can only support and coordinate until the brains can get fixing issues.

PS: KCauldron is a "possible" alternative. https://repo.prok.pw/pw/prok/KCauldron/

**Comment by Pixeldk** [comment]
Been trying to get a hold on him everywhere now.. skype, google hangouts, irc and github. Think irl is having a hold on him atm.

**Comment by Pixeldk** [comment]
And tried kcauldron. Its not reading the spigot file iether. :-/

**Comment by ManOrMonster** [comment]
Thanks for the in-depth explanation.

**Comment by ManOrMonster** [comment]
Is there any way to just "Open to LAN" and have people on my LAN join? When I click that it just opens a chat window...

**Comment by fucnknown** [comment]
jbudda, I've been thinking. Can you make it so that the client sends a "/tp <player> x y z" instruction to the server, so the player will be teleported in a traditional, server supported manner?

**Comment by jrbudda** [comment]
I'm really not sure, would work in theory, might require a good bit of moving things around.

**Comment by possi** [comment]
@ManOrMonster I can confirm this Bug (for v13). jrbudda may be able to fix this.

@ziggrrauglurr: This may be possible, but requires a server side implementation that prevents the player from cheating all around the server. Also there need to be some CustomPacketCommunication between Server and Client to determind that this teleportation-method should be used instead of default one.

**Comment by fucnknown** [comment]
Yeah. Was just an idea.  I found the modification needed on thermos source to either fix this or make the options configurable like in spigot. Compiling Thermos is the troublesome part...

**Comment by possi** [comment]
@Pixeldk, @ziggrrauglurr: https://www.reddit.com/r/Vive/comments/4m6unh/vivecraft_server_with_mods_incomming/d3x5twe

**Comment by fucnknown** [comment]
Excellent, Thank you!  (Nevermind, got it to compile after putting a local copy of fernflower in the cache)

**Comment by ManOrMonster** [comment]
Thanks for all your work guys, possi's Thermos edit worked perfectly.
