### ISSUE TITLE
Center of Playspace Indication?

### ISSUE THREAD

**Issue by RenStrike** [jrbudda/minecrift#4]
In locomotion mode it's best if you stand in the direct center of the playspace, since that is where the player capsule appears to be.  Any way to get a subtle glow at the center of the playspace so I always know where it's at, without having to check the bounds and then guess whether i'm in the center or not.

Alternatively (or preferably in addition to) is there any way to have the player capsule actual be around me in locomotion mode, rather than the center of the playspace?

**Comment by jrbudda** [comment]
I tried having the player body follow the camera around in 'free move' mode like it does in teleport mode but it caused massive issues with the entity movement when you used the trigger. I may look into it again at some point, but given that most interactions use the hands as reference I don't think its a huge deal.

I actually already put a room origin indication in some test code, when I get around to making options I'll put a way to turn it on.

**Comment by RenStrike** [comment]
Room origin would make trigger movement much more usable.  I ran into issues when i would be standing as far forward in my playspace as i could, then move in that direction, and my head would get embedded into blocks since the player body is actually at the center of the playspace.

So, in teleport mode, does the body actually follow the camera?  That must be why physically walking up/down blocks works in TP mode, but not in locomotion mode.

**Comment by jrbudda** [comment]
Correct, in TP mode the camera drags the body around, in free mode the body drags the camera (actually the room) around.

I'd ultimately like to have the camera move the body in both cases, but it's mess for free move.

**Comment by jrbudda** [comment]
Done in v6
