### ISSUE TITLE
Crash when loading / starting a new world with heavily modded pack

### ISSUE THREAD

**Issue by dgobi** [jrbudda/minecrift#42]
I am using the Regrowth modpack, with the correct version of forge for Vivecraft. I apologize in advance if this isn't the place for this issue, or if it's just mod incompatibility. 

To be clear, the game doesn't crash entirely, you just can't load or create a world. Doing so returns you to the main menu. 

Here is the pastebin with the log: http://pastebin.com/piQ6kNQn

Sadly I have no idea how to interpret this information. :\

**Comment by fucnknown** [comment]
Hi, please try going to the mod folder and disable microblocks, Thaumcraft and waila (just changing the extension from jar to something else is enough). And give it a spin.

**Comment by jrbudda** [comment]
net.minecraft.common.IExtendedEntityProperties seems to be missing. Which is a class that forge adds, is Forge installed, do other forge mods work? is your profile pointed at the correct vivecraft-forge jar?

**Comment by dgobi** [comment]
Hi, yes other forge mods work. When run without Vivecraft everything functions fine.  

ziggrrauglurr - unfortunately this mod pack has a ton of dependencies on those mods, so disabling them leads to a cascade of disabling almost every mod in the pack and causes it to be essentially non functional. Is VIvecraft incompatible with those mods?

Looks like I will have to content myself with 2D feedthebeast packs for the time being. Thanks for the help anyways!
