### ISSUE TITLE
[Feature Request] Custom Packet for Player-Information

### ISSUE THREAD

**Issue by possi** [jrbudda/minecrift#43]
Please send a CustomPaylopadPacket with additional Information:
- On Connect: Currently a Request "MC|Vive" with Value "please" is send. Change the "please" to "jrbudda15" or such to allow version checking on Server-Side
- On Movement-Schema-Change send a Packet Like: "MC|Vive|Movement" with value "teleportation"/"classic" or such.

Thanks in advanced ;)

**Comment by jrbudda** [comment]
onplayerjoin will send MC|Vive|Version with the minecraftversionstring instead of 'please'. Lol.

On mode switch will send MC|Vive|FreeMove with 1 or 0. 1 is free move, 0 is teleport.
