### ISSUE TITLE
[Forge Mods] No GUI with mods installed

### ISSUE THREAD

**Issue by famguy07** [jrbudda/minecrift#46]
I used forge mod loader and pointed the vive profile to the modded directory and there are no GUIs in the game. everything else works fine. i can provide a mod list if necessary.

**Comment by jrbudda** [comment]
yea need a mod list, check to make sure you havent installed mainmenureplacer

**Comment by famguy07** [comment]
buildcraft 7.1.16
chocolatequest 1.7.10-1.0
code chiken core 1.7.10-1.0.7.47
flatbedrock 1.0.2
galacticraft core 1.7-3.0.12.375
galacticraft planets 1.7-3.0.12.375
immibis core 59.1.4
immibis macroblocks 59.1.1
immibis microblocks 59.1.2
ironchest 1.7.10-6.0.60.741
mantle 1.7.10-0.3.2b
micdoodle core 1.7-3.0.12.375
not enough items 1.7.10-1.0.5.120
pams harvestcraft 1.7.10Lb
RWG alpha 1.3.2 (realistic world generation)
TConstruct 1.7.10-1.8.8
Waila 1.5.10-1.7.10
Xaeros Minimap 1.9 for 1.7.10

its a technic modpack here:
http://www.technicpack.net/modpack/ztripleacustom01.852167

**Comment by jrbudda** [comment]
any changes in v18?

**Comment by denny99** [comment]
I've tested this modpack. Seems to work now.

**Comment by famguy07** [comment]
Sorry for the delay, but I was in Canada for the weekend. I just tested with v19 as well and the issue seems to be fixed. Thanks.

**Comment by jrbudda** [comment]
Canada, eh? Almost made it.
