### ISSUE TITLE
Stuck at the end after killing the dragon

### ISSUE THREAD

**Issue by plaidpants** [jrbudda/minecrift#48]
I believe the credits need to roll but cannot because we are in VR. Quiting the game and switching out of VR and continuing the game allows me to run the credits and get back to my spawn point. Probably need to room similar to the start of the game to be able to run the credits. Game is in creative mode if that makes a difference. Tested with release 12, need to upgrade and see what's new.

**Comment by jrbudda** [comment]
Thanks I'll look into it.

**Comment by jrbudda** [comment]
should be fixed in v16, please confirm, thanks!.

**Comment by plaidpants** [comment]
This issue is resolved in version 16. Thanks.
