### ISSUE TITLE
Teleport Playspace Preview

### ISSUE THREAD

**Issue by RenStrike** [jrbudda/minecrift#5]
Would it be possible to get an indication of where my playspace will be upon teleporting to the new location?  This is the way The Lab and The Gallery both do it and i find it very useful.  Thanks, I love this mod! :)

**Comment by jrbudda** [comment]
Probably not from me, don't really have any desire to go digging into OpenVR to extract the playspace and deal with all the geometry needed to render it in the world. Not even sure the functionality exists in the java library. 

Given the long reach for interaction not sure how necessary it is anyway.

**Comment by RenStrike** [comment]
Agreed.  I think having the room origin displayed will fix the majority of my issues with not knowing where I am in my playspace most of the time anyway.
