### ISSUE TITLE
Crashing when attempting to hold/equip any new item from Biomes O'Plenty mod

### ISSUE THREAD

**Issue by Octavian-the-ent** [jrbudda/minecrift#50]
Only other mods installed are FastCraft (the optimizer) and Mo Creatures, which seems to work fine. 
Crashes every time I attempt to select the items in the hotbar. They will spawn correctly and can be broken and collected, but not equipped. I'm on V14 of the Vivecraft mod.

---- Minecraft Crash Report ----
// Don't do that.

Time: 6/7/16 3:29 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at biomesoplenty.common.itemblocks.ItemBlockFlower.func_77661_b(ItemBlockFlower.java:78)
    at com.mtbs3d.minecrift.gameplay.BowTracker.isActive(BowTracker.java:59)
    at com.mtbs3d.minecrift.gameplay.BowTracker.doProcess(BowTracker.java:68)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1461)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at biomesoplenty.common.itemblocks.ItemBlockFlower.func_77661_b(ItemBlockFlower.java:78)
    at com.mtbs3d.minecrift.gameplay.BowTracker.isActive(BowTracker.java:59)
    at com.mtbs3d.minecrift.gameplay.BowTracker.doProcess(BowTracker.java:68)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['test'/237, l='MpServer', x=-391.63, y=71.62, z=1187.27]]
    Chunk stats: MultiplayerChunkCache: 566, 575
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-644,64,1020), Chunk: (at 12,4,12 in -41,63; contains blocks -656,0,1008 to -641,255,1023), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Level time: 5276 game time, 5276 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 147 total; [MoCEntityBigCat['BigCat'/256, l='MpServer', x=-455.22, y=66.00, z=1223.19], EntityZombie['Zombie'/257, l='MpServer', x=-462.50, y=27.00, z=1232.50], MoCEntityBird['Bird'/258, l='MpServer', x=-461.67, y=72.00, z=1315.07], EntityCreeper['Creeper'/771, l='MpServer', x=-397.50, y=59.00, z=1192.50], EntitySkeleton['Skeleton'/1027, l='MpServer', x=-339.50, y=46.00, z=1201.50], MoCEntityBird['Bird'/259, l='MpServer', x=-459.50, y=72.00, z=1313.50], EntityZombie['Zombie'/1028, l='MpServer', x=-380.41, y=25.00, z=1206.94], EntitySkeleton['Skeleton'/1029, l='MpServer', x=-379.09, y=25.00, z=1207.28], EntitySkeleton['Skeleton'/1030, l='MpServer', x=-375.50, y=25.00, z=1205.50], EntityCreeper['Creeper'/1031, l='MpServer', x=-353.50, y=16.00, z=1119.50], EntityItem['item.tile.rail'/1291, l='MpServer', x=-381.12, y=34.01, z=1202.72], EntityEnderman['Enderman'/785, l='MpServer', x=-332.53, y=16.00, z=1159.47], EntitySkeleton['Skeleton'/787, l='MpServer', x=-339.50, y=46.00, z=1197.50], EntityCreeper['Creeper'/788, l='MpServer', x=-394.78, y=59.00, z=1190.78], EntityCreeper['Creeper'/789, l='MpServer', x=-404.84, y=58.00, z=1189.04], MoCEntityHorse['WildHorse'/286, l='MpServer', x=-436.84, y=72.00, z=1104.81], MoCEntityOgre['Ogre'/287, l='MpServer', x=-441.63, y=39.00, z=1133.22], EntityCreeper['Creeper'/288, l='MpServer', x=-447.50, y=39.00, z=1126.50], EntitySkeleton['Skeleton'/289, l='MpServer', x=-445.50, y=39.00, z=1125.50], MoCEntityHorse['WildHorse'/290, l='MpServer', x=-446.03, y=67.00, z=1119.50], EntityCreeper['Creeper'/291, l='MpServer', x=-442.59, y=12.00, z=1183.28], EntitySpider['Spider'/292, l='MpServer', x=-437.09, y=12.00, z=1187.22], EntitySpider['Spider'/293, l='MpServer', x=-439.13, y=11.00, z=1187.09], EntityCreeper['Creeper'/294, l='MpServer', x=-442.13, y=12.00, z=1189.63], EntityCreeper['Creeper'/295, l='MpServer', x=-441.56, y=11.00, z=1184.84], EntityCreeper['Creeper'/296, l='MpServer', x=-440.34, y=11.00, z=1186.63], MoCEntityKitty['Kitty'/297, l='MpServer', x=-440.00, y=64.00, z=1212.38], MoCEntityKitty['Kitty'/298, l='MpServer', x=-435.38, y=67.00, z=1225.97], EntityItem['item.item.seeds'/1074, l='MpServer', x=-386.53, y=63.13, z=1232.91], MoCEntityMiniGolem['MiniGolem'/311, l='MpServer', x=-424.50, y=17.00, z=1084.50], MoCEntitySilverSkeleton['SilverSkeleton'/313, l='MpServer', x=-428.50, y=16.00, z=1211.50], MoCEntitySilverSkeleton['SilverSkeleton'/314, l='MpServer', x=-426.50, y=16.00, z=1211.50], EntityMinecartChest['entity.MinecartChest.name'/315, l='MpServer', x=-430.50, y=25.50, z=1216.50], EntityPig['Pig'/316, l='MpServer', x=-416.50, y=70.00, z=1259.50], EntityItem['item.tile.flower1.dandelion'/1093, l='MpServer', x=-340.63, y=62.13, z=1208.78], EntityZombie['Zombie'/326, l='MpServer', x=-405.48, y=58.00, z=1190.14], EntityZombie['Zombie'/327, l='MpServer', x=-404.41, y=59.00, z=1196.00], EntityZombie['Zombie'/328, l='MpServer', x=-403.50, y=59.00, z=1198.50], EntityPig['Pig'/329, l='MpServer', x=-415.50, y=73.00, z=1213.50], EntityItem['item.item.seeds'/330, l='MpServer', x=-409.31, y=71.13, z=1206.19], EntityPig['Pig'/331, l='MpServer', x=-410.50, y=66.00, z=1217.50], EntityPig['Pig'/332, l='MpServer', x=-413.16, y=71.00, z=1216.38], EntityPig['Pig'/333, l='MpServer', x=-414.50, y=68.00, z=1217.50], EntityCreeper['Creeper'/1102, l='MpServer', x=-381.50, y=23.00, z=1236.50], EntityPig['Pig'/334, l='MpServer', x=-412.50, y=69.00, z=1258.22], EntityZombie['Zombie'/1103, l='MpServer', x=-376.50, y=23.00, z=1234.50], EntityPig['Pig'/335, l='MpServer', x=-412.50, y=69.00, z=1259.81], EntityZombie['Zombie'/1104, l='MpServer', x=-381.50, y=23.00, z=1235.50], EntityPig['Pig'/336, l='MpServer', x=-411.50, y=68.00, z=1257.50], EntityZombie['Zombie'/1105, l='MpServer', x=-378.50, y=23.00, z=1236.50], EntityZombie['Zombie'/1106, l='MpServer', x=-375.50, y=26.00, z=1193.50], EntityItem['item.tile.flower2.poppy'/351, l='MpServer', x=-399.22, y=68.13, z=1150.53], EntityItem['item.tile.flowers.clover'/352, l='MpServer', x=-398.91, y=69.13, z=1149.69], EntityItem['item.tile.flower1.dandelion'/353, l='MpServer', x=-393.09, y=69.13, z=1154.25], EntityItem['item.tile.flower2.poppy'/354, l='MpServer', x=-396.13, y=68.13, z=1156.06], EntityItem['item.tile.rail'/355, l='MpServer', x=-386.19, y=25.13, z=1178.34], EntityItem['item.tile.rail'/356, l='MpServer', x=-388.88, y=25.13, z=1225.81], EntityItem['item.tile.rail'/357, l='MpServer', x=-387.84, y=25.13, z=1223.94], EntityItem['item.tile.rail'/358, l='MpServer', x=-388.88, y=25.13, z=1232.88], EntitySquid['Squid'/359, l='MpServer', x=-385.22, y=61.22, z=1235.50], EntityItem['item.item.seeds'/620, l='MpServer', x=-338.63, y=63.13, z=1209.13], EntityItem['item.tile.saplings.firSapling'/621, l='MpServer', x=-349.13, y=84.13, z=1245.28], EntitySkeleton['Skeleton'/371, l='MpServer', x=-381.50, y=14.00, z=1110.50], EntityMinecartChest['entity.MinecartChest.name'/372, l='MpServer', x=-378.50, y=25.50, z=1172.50], EntityItem['item.tile.saplings.firSapling'/628, l='MpServer', x=-361.06, y=78.13, z=1250.63], EntityItem['item.tile.rail'/373, l='MpServer', x=-383.19, y=25.13, z=1179.88], EntityMinecartChest['entity.MinecartChest.name'/374, l='MpServer', x=-375.50, y=26.50, z=1190.50], EntityMinecartChest['entity.MinecartChest.name'/375, l='MpServer', x=-370.50, y=40.50, z=1196.50], EntityItem['item.tile.saplings.firSapling'/631, l='MpServer', x=-347.56, y=89.13, z=1247.44], EntityItem['item.tile.flower1.dandelion'/376, l='MpServer', x=-370.88, y=33.13, z=1197.81], EntityItem['item.tile.rail'/377, l='MpServer', x=-374.19, y=36.13, z=1201.25], EntityItem['item.tile.flowers2.minersdelight'/378, l='MpServer', x=-376.19, y=36.13, z=1201.94], EntityItem['item.tile.rail'/379, l='MpServer', x=-383.81, y=25.13, z=1228.19], EntitySquid['Squid'/380, l='MpServer', x=-383.97, y=62.22, z=1236.91], MoCEntityBird['Bird'/381, l='MpServer', x=-381.50, y=79.00, z=1285.50], MoCEntityBird['Bird'/382, l='MpServer', x=-380.50, y=123.00, z=1287.50], EntityItem['item.item.seeds'/638, l='MpServer', x=-338.94, y=64.13, z=1156.13], MoCEntityBird['Bird'/383, l='MpServer', x=-380.50, y=123.00, z=1286.50], EntityItem['item.item.seeds'/639, l='MpServer', x=-393.97, y=62.13, z=1236.94], EntityItem['item.tile.flower2.poppy'/389, l='MpServer', x=-362.69, y=15.13, z=1211.84], EntityItem['item.tile.rail'/390, l='MpServer', x=-364.63, y=34.13, z=1214.81], EntityItem['item.tile.rail'/391, l='MpServer', x=-363.13, y=34.13, z=1215.81], EntityItem['item.tile.rail'/392, l='MpServer', x=-365.88, y=34.13, z=1215.81], EntityItem['item.tile.rail'/393, l='MpServer', x=-363.25, y=21.13, z=1242.81], EntityItem['item.tile.rail'/394, l='MpServer', x=-362.13, y=21.13, z=1244.81], MoCEntityBird['Bird'/396, l='MpServer', x=-360.66, y=72.00, z=1265.22], MoCEntityFirefly['Firefly'/141, l='MpServer', x=-519.50, y=66.00, z=1076.50], MoCEntityBird['Bird'/397, l='MpServer', x=-361.50, y=72.00, z=1265.50], MoCEntityButterfly['ButterFly'/144, l='MpServer', x=-518.41, y=64.00, z=1097.75], EntityCreeper['Creeper'/656, l='MpServer', x=-379.50, y=24.00, z=1228.50], EntitySpider['Spider'/663, l='MpServer', x=-414.50, y=29.00, z=1159.50], EntitySkeleton['Skeleton'/408, l='MpServer', x=-344.50, y=18.00, z=1129.50], EntitySkeleton['Skeleton'/409, l='MpServer', x=-344.50, y=18.00, z=1130.50], EntityItem['item.tile.flower1.dandelion'/410, l='MpServer', x=-345.81, y=64.13, z=1204.88], MoCEntityBoar['Boar'/155, l='MpServer', x=-514.81, y=70.00, z=1165.16], EntityItem['item.tile.saplings.firSapling'/411, l='MpServer', x=-348.41, y=84.13, z=1246.88], MoCEntityBoar['Boar'/156, l='MpServer', x=-516.59, y=70.00, z=1164.50], EntitySkeleton['Skeleton'/676, l='MpServer', x=-370.50, y=55.00, z=1227.50], EntitySkeleton['Skeleton'/677, l='MpServer', x=-370.50, y=55.00, z=1228.50], EntityPig['Pig'/422, l='MpServer', x=-331.50, y=63.00, z=1117.50], EntityPig['Pig'/423, l='MpServer', x=-330.50, y=64.00, z=1119.50], MoCEntityDragonfly['DragonFly'/168, l='MpServer', x=-507.53, y=66.00, z=1070.25], MoCEntityDragonfly['DragonFly'/169, l='MpServer', x=-504.41, y=66.00, z=1065.97], EntityZombie['Zombie'/425, l='MpServer', x=-324.50, y=40.00, z=1134.50], EntityItem['item.item.seeds'/426, l='MpServer', x=-330.81, y=63.13, z=1165.13], MoCEntityBird['Bird'/427, l='MpServer', x=-336.56, y=70.00, z=1233.78], MoCEntityBird['Bird'/428, l='MpServer', x=-333.38, y=70.00, z=1232.50], EntityCreeper['Creeper'/940, l='MpServer', x=-418.50, y=29.00, z=1167.50], MoCEntityDragonfly['DragonFly'/173, l='MpServer', x=-511.28, y=66.00, z=1118.66], MoCEntityDragonfly['DragonFly'/174, l='MpServer', x=-511.22, y=66.00, z=1116.41], MoCEntityDragonfly['DragonFly'/175, l='MpServer', x=-510.19, y=65.00, z=1114.56], MoCEntityBear['Bear'/433, l='MpServer', x=-314.50, y=65.00, z=1060.50], MoCEntityBear['Bear'/434, l='MpServer', x=-317.50, y=65.00, z=1063.50], EntityZombie['Zombie'/946, l='MpServer', x=-458.50, y=27.00, z=1233.00], EntitySheep['Sheep'/435, l='MpServer', x=-316.22, y=72.00, z=1143.78], EntitySheep['Sheep'/436, l='MpServer', x=-317.53, y=72.00, z=1143.63], EntitySheep['Sheep'/437, l='MpServer', x=-316.31, y=72.00, z=1142.47], EntitySheep['Sheep'/438, l='MpServer', x=-318.50, y=72.00, z=1141.50], MoCEntityDeer['Deer'/185, l='MpServer', x=-497.50, y=69.00, z=1204.50], EntityCreeper['Creeper'/953, l='MpServer', x=-416.50, y=29.00, z=1166.50], MoCEntityDeer['Deer'/198, l='MpServer', x=-492.50, y=69.00, z=1210.50], MoCEntityBird['Bird'/459, l='MpServer', x=-299.50, y=70.00, z=1304.50], MoCEntityBird['Bird'/460, l='MpServer', x=-296.50, y=70.00, z=1305.50], MoCEntityMouse['Mouse'/468, l='MpServer', x=-284.50, y=71.00, z=1245.50], EntitySkeleton['Skeleton'/1242, l='MpServer', x=-416.50, y=18.00, z=1245.50], MoCEntityFox['Fox'/478, l='MpServer', x=-269.50, y=72.00, z=1259.50], EntityZombie['Zombie'/227, l='MpServer', x=-452.50, y=49.00, z=1115.50], EntitySkeleton['Skeleton'/1251, l='MpServer', x=-469.50, y=39.00, z=1137.50], MoCEntityMiniGolem['MiniGolem'/228, l='MpServer', x=-460.91, y=39.00, z=1131.78], EntityCreeper['Creeper'/229, l='MpServer', x=-457.50, y=45.00, z=1128.50], MoCEntityMiniGolem['MiniGolem'/230, l='MpServer', x=-464.69, y=39.00, z=1131.94], EntityCow['Cow'/231, l='MpServer', x=-454.59, y=69.00, z=1128.41], EntityCow['Cow'/232, l='MpServer', x=-446.53, y=68.00, z=1132.72], EntitySkeleton['Skeleton'/1256, l='MpServer', x=-469.50, y=39.00, z=1138.50], EntityCow['Cow'/233, l='MpServer', x=-461.31, y=70.00, z=1131.53], EntityCow['Cow'/234, l='MpServer', x=-454.25, y=69.00, z=1136.09], MoCEntityBigCat['BigCat'/236, l='MpServer', x=-454.16, y=66.00, z=1215.72], EntityZombie['Zombie'/1008, l='MpServer', x=-372.56, y=25.00, z=1212.00], EntityZombie['Zombie'/1264, l='MpServer', x=-414.50, y=29.00, z=1161.50], EntityItem['item.tile.saplings.firSapling'/1265, l='MpServer', x=-361.88, y=88.13, z=1251.88], MoCEntityRaccoon['Raccoon'/247, l='MpServer', x=-505.50, y=69.00, z=1267.50], MoCEntityFox['Fox'/248, l='MpServer', x=-486.75, y=67.00, z=1283.97], EntitySkeleton['Skeleton'/249, l='MpServer', x=-464.50, y=21.00, z=1218.50], EntityZombie['Zombie'/250, l='MpServer', x=-467.50, y=21.00, z=1224.50], EntityZombie['Zombie'/1275, l='MpServer', x=-415.50, y=29.00, z=1163.50], EntityClientPlayerMP['test'/237, l='MpServer', x=-391.63, y=71.62, z=1187.27], EntitySkeleton['Skeleton'/254, l='MpServer', x=-471.50, y=29.00, z=1231.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3405)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1345)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 448891504 bytes (428 MB) / 858210304 bytes (818 MB) up to 4241293312 bytes (4044 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    UCHIJAAAA   MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 980/PCIe/SSE2'
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda14-forge-nohydra
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (4)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 14
Mipmaps: 2
Anisotropic Filtering: 4
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 368.22
OpenGlRenderer: GeForce GTX 980/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by jrbudda** [comment]
Hmm... I know what's doing it, but I dunno why it's crashing. I think I can work around it, stay tuned.

**Comment by Octavian-the-ent** [comment]
Cool. Is it something to do with how bows were changed to work in your mod?

**Comment by Octavian-the-ent** [comment]
I switched to ExtraBiomesXL and it seems to work.

**Comment by fucnknown** [comment]
Octavian, I would like to add that Fastcraft works by trying to improve **Cos** and **Sin** calculations, this improvements are already in Optifine which is part of Vivecraft. Therefore you don't need to add said mod.

**Comment by jrbudda** [comment]
this should be fixed maybe in v17, didn't test.

**Comment by jrbudda** [comment]
Assume fixed
