### ISSUE TITLE
[Forge Mod] Terrafirmacraft Bugs

### ISSUE THREAD

**Issue by denny99** [jrbudda/minecrift#51]
First:
I'm using V16 of ViveCraft and TFC 0.79.29.922.

The game crashes with the following error code while loading the world

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 07.06.16 23:42
Description: Exception in server tick loop

java.lang.VerifyError: (class: net/minecraft/entity/player/EntityPlayer, method: func_70620_b signature: (Lnet/minecraft/item/ItemStack;I)Lnet/minecraft/util/IIcon;) Illegal target of jump or branch
    at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:377)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.7.0_79, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 481281152 bytes (458 MB) / 830447616 bytes (791 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M -XX:-UseSplitVerifier
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 17
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   tfc_coremod{0.79.29} [TFC[coremod]](minecraft.jar) 
    UCHIJAAAA   terrafirmacraft{0.79.29} [TerraFirmaCraft]([1.7.10]TerraFirmaCraft-0.79.29.922.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.7.10_HD_U_D1
    Render Distance Chunks: 12
    Mipmaps: 4
    Anisotropic Filtering: 16
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 4.5.0 NVIDIA 368.22
    OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

**Comment by jrbudda** [comment]
Well that's a new one. Typical Forge compatibility issue. Will look into.

**Comment by jrbudda** [comment]
Not sure if relavant, but the version of Terrafirmacraft for 1.7.10 is built with a different Forge, have you tested it with non-vivecraft Forge 1614?

**Comment by denny99** [comment]
The first thing i've tested, before posting :). It is working with this forge version.

**Comment by Techjar** [comment]
We're no longer modifying the EntityPlayer class in v19, so it may work now. Please test.

**Comment by jrbudda** [comment]
oooh i can test this

**Comment by jrbudda** [comment]
It loads! Will re-open if more speicifc bugs exist with this mod.

**Comment by denny99** [comment]
I've got another one for you :). The TFC Bars are missing.
**TFC Vive:**
![2016-06-13 10_29_59-vivecraft 1 7 10 vivecraft-jrbudda19 vr](https://cloud.githubusercontent.com/assets/1826849/16001445/4bc31d86-3152-11e6-97ec-45591c3e9bbd.png)

**Forge Only:**
![2016-06-13 10_32_39-steam](https://cloud.githubusercontent.com/assets/1826849/16001456/601149ac-3152-11e6-93db-f8cc7f9cfcd8.png)

**Comment by Techjar** [comment]
Huh, even the experience bar is missing. That's weird. I'll have to look into TFC's rendering.

**Comment by Techjar** [comment]
Actually, can you try this build? We just pushed some render-related changes.
[vivecraft-1.7.10-Vivecraft-jrbudda20-installer.exe](https://owncloud.techjargaming.com/index.php/s/dSj7nCeoKi0Eo9x/download)

**Comment by denny99** [comment]
That would have been too easy. So no it doesn't work.

**Comment by jrbudda** [comment]
Theres some alpha transparency stuff going on with the menu rendering sometime. Are they there if you turn on 'menu background' ? This is just a guess.

**Comment by denny99** [comment]
Nope

**Comment by Techjar** [comment]
Yeah I'm not sure why TFC doesn't work. The Forge compat for the hooks it's using is there. And yeah the UI seems to still have some transparency issues.
