### ISSUE TITLE
[Forge Mod] Block-texture changing mods like Carpenter's Blocks don't work in Vivecraft

### ISSUE THREAD

**Issue by ph2001** [jrbudda/minecrift#52]
As you requested here:

https://www.reddit.com/r/Vive/comments/4my75a/vivecraft_update_16/d40ajnf?context=10000

**Comment by jrbudda** [comment]
Are you also seeing the block direction/orientation being wrong if you quit the game and reload?

**Comment by ph2001** [comment]
Yeah for some blocks, for example Industrialcraft Iron Furnace.

**Comment by jrbudda** [comment]
but not carpenterblocks? Im seeing even the regular slope and oblique blocks reload with the wrong orientation.

**Comment by ph2001** [comment]
Uhh not that I know of. 
Carpenter's blocks simply refuse to take on any texture at all. You normally rightclick the framework-like blocks and they take on the texture of whatever block you put "inside" them. But in Vivecraft, the block vanishes from your hand while the carpenterblock is unchanged.

You can put a bunch of carpenterblocks down in normal Minecraft, apply textures to them, and they will all be naked framework blocks in Vivecraft.

**Comment by jrbudda** [comment]
Weird I saw the texture thing. And the textures are there if you load up non-vivecraft forge. But it's also losing the orientation of the blocks. I hope I didn't break something else...

**Comment by ph2001** [comment]
Huh, yeah, I see it now. Tested with r17, the carpenter blocks lose their orientation and also their specific shape. Not sure if that was a thing before.

I had like 2 cubes and a bunch of random shapes put down, and inside Vivecraft, all of the random shapes are triangle blocks with the same orientation on top of having no texture.

**Comment by jrbudda** [comment]
Well at least I'm not crazy, do you mind going back a couple versions and seeing if the behavior was the same or if I broke it recently? thanks!

**Comment by ph2001** [comment]
Present in r14, present in r10. So it seems that bug has been a thing since the start.

**Comment by jrbudda** [comment]
This should be fixed in v19, please test

**Comment by ph2001** [comment]
It seems to be working fine, I can't find any bugs with it so far. You and Techjar are officially gods.

Leave me your donation details please, I can't guarantee it but I'm pretty sure my mom will want to donate for your efforts.

**Comment by jrbudda** [comment]
Click my name here on github there's info on my profile. Don't know about Techjar. And thanks.
