### ISSUE TITLE
Bugs I'm encountering

### ISSUE THREAD

**Issue by Nier-Replicant** [jrbudda/minecrift#54]
~~1st Bug: When pressing Lgrip + Menu key, the keyboard isn't appearing / working.~~
Edit: Ahh I did not know that SteamVR needed to be running, I thought that the Keyboard was independent rather than linked. Neato.

**Comment by Nier-Replicant** [comment]
2nd Bug: I get hap-tic feedback when ever someone else (Or even NPCs) besides me uses something (Such as doors or landing) it seems.

**Comment by jrbudda** [comment]
for the keyboard thing, is SteamVR running?

**Comment by aznboi589** [comment]
Actually no, I'm going to test it now.

**Comment by jrbudda** [comment]
and yea the second thing is the haptics are tied to the sound effects, I'm not sure of a better way to do it at the moment.

**Comment by Nier-Replicant** [comment]
Ah okay, so it's a known issue / non-issue i assume, it's just really strange when I'm near someone or something and my controllers vibrate for no reason.

Edit: Would it be possible to trigger the haptic feedback via the use button?
