### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/minecrift#55]
Don't know if this is possible, but some mods need the ability to hold a key, like thuamcraft craft needs to hold r and move the mouse up to change focis. Would there be a way to bind a selected key from the keyboard to then be able to press/hold via the vive controller in game?

**Comment by jrbudda** [comment]
yes. very soon.

**Comment by jrbudda** [comment]
see if this does what you want

[vivecraft-1.7.10-Vivecraft-jrbudda17-installer.exe.zip](https://github.com/jrbudda/minecrift/files/305248/vivecraft-1.7.10-Vivecraft-jrbudda17-installer.exe.zip)

**Comment by zeshinumi** [comment]
it does! Although for the thing I was looking at, it seems it activates a temporary window for the thuamcraft wand (talking about when trying to attach a wand foci) and, normally, it's waiting for a mouse direction movement. However looking around or moving the controls does not seem to create this effect, and I can't move the mouse to do it either. But that button binding will help with a ton of other mods :D

**Comment by jrbudda** [comment]
Ok, yea i dunno about the Mouse thing. Minecraft uses the LWJGL Mouse input from the window and I cannot simulate movement. Adding mouse simulation to custom mod window is going to be very difficult.

somewhat surprised it's not working with the normal mouse tho.
