### ISSUE TITLE
Sign UI opens but doesn't bring up SteamVR keyboard

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#57]
In previous versions the sign UI (when you place a sign) wouldn't open at all. Now it does, but you have to use your real keyboard to type on it since it doesn't open the in-game one. It should, as this would make sense.

**Comment by Nier-Replicant** [comment]
You must have SteamVR open before launching ViveCraft.
I thought i had that problem too.

**Comment by Techjar** [comment]
No, the SteamVR keyboard opens for chat as it should, but it does not open when editing signs. The same goes for editing books, and probably anywhere else that involves entering text besides the chat.

**Comment by jrbudda** [comment]
Can you use the button combo (left_grip + left_menu) to bring up the keyboard in these situations?

**Comment by Techjar** [comment]
That button combination does indeed work, but it would be more convenient if the keyboard opened automatically in places where you'd obviously be typing.

**Comment by jrbudda** [comment]
Agreed! I was just curious.

**Comment by Techjar** [comment]
This still hasn't been implemented? I'd do it myself but I don't know how to open the keyboard from code.

**Comment by jrbudda** [comment]
MCOpenVR.setKeyboardOverlayShowing

It might need some changes, I dunno if the Sign UI inherits from GuiTextField. Also if you edit the sign UI have to check it for Forge compatibility,.

**Comment by Techjar** [comment]
Fixed by PR #87
