### ISSUE TITLE
Can't type many symbols on in-game keyboard

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#58]
Alphanumeric characters of course work fine. Haven't tried all the symbols, but many don't work, such as these: " @ # $ ^ & ( )

**Comment by jrbudda** [comment]
thank you, will correct, let me know of any others, have do do each manually.

**Comment by Techjar** [comment]
Well since you have to do it manually, couldn't you just add all of the symbols which appear on the SteamVR keyboard?

**Comment by jrbudda** [comment]
Keyboard changes based on your location settings I think. Even then there's some stuff lost in translation cause of the java keyboard simulator.

Should be much better in v17. Gonna close this, Post more if you find.

**Comment by Techjar** [comment]
I'm still unable to type the following symbols: + " ! £ €

**Comment by jrbudda** [comment]
What is the key combination for the 2 money symbols on your keyboard?

**Comment by Techjar** [comment]
Well, the 2 money symbols don't physically exist on my keyboard, they're just on the SteamVR keyboard. Can you even implement Alt+156 (£) and Alt+0128 (€) key combinations?
