### ISSUE TITLE
[Forge Mod] Pixelmon crashing after battle

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/minecrift#59]
When you battle in the pixelmon mod, and you complete a battle, the game crashes. I assume this might have something to do with a call involving the player perspective rendering since pixelmon takes control of the camera for a battle. I also tested disabling the moving camera during battle in the pixelmon config with the same result. I have a pastbin of the crash here: http://pastebin.com/U7dXRtBM

**Comment by jrbudda** [comment]
Test this.

[vivecraft-1.7.10-Vivecraft-jrbudda17-installer.exe.zip](https://github.com/jrbudda/minecrift/files/305841/vivecraft-1.7.10-Vivecraft-jrbudda17-installer.exe.zip)

**Comment by zeshinumi** [comment]
Will do once I get home from work tomarrow

**Comment by zeshinumi** [comment]
Perfect!
