### ISSUE TITLE
Cant move under blocks without dying

### ISSUE THREAD

**Issue by mikedaman34** [jrbudda/minecrift#6]
How high does a ceiling have to be? I'll stand under a space 3 blocks tall and start to die. I didn't have this issue in the original mod. For example, when building a tunnel, if it's only 3 blocks high (which is over my head) when teleporting into the tunnel the screen flashes and I'll die if I don't teleport out quick enough. Maybe I'm missing something?

**Comment by jrbudda** [comment]
I'll look into it, sounds like a bounding box bug

**Comment by antifreak** [comment]
Ahh, thought i broke my version because of a mod i installed =)

Is there a temporary workaround (like disable damage from blocks)?

Thanks for your hard work

**Comment by mikedaman34** [comment]
Thanks for all your hard work on this!

**Comment by jrbudda** [comment]
test v7 please

**Comment by rogueqd** [comment]
Confirm this is fixed in v8 (I didn't test v7, quick updates!)

**Comment by jrbudda** [comment]
see if the 'invisble block' scenario still happens in v9, please.

**Comment by mikedaman34** [comment]
I'll check it out today. The issue was fixed in V7. Thanks for all your 
time and effort. This has been a blast to play!

On 5/28/2016 1:00 AM, jrbudda wrote:

> see if the 'invisble block' scenario still happens in v9, please.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/jrbudda/minecrift/issues/6#issuecomment-222292186, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/ASrNj_LClwV9UJSD1GPsK8tzB5NQkW-tks5qF9obgaJpZM4InJZq.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
