### ISSUE TITLE
TP survival mode to false not working as a client

### ISSUE THREAD

**Issue by zonfar** [jrbudda/minecrift#64]
When I join my friends minecraft (They dont have vive) I can't set the TP survive to false (I find not being able to TP around objects extremely annoying)

**Comment by ph2001** [comment]
Multiplayer mode disallows extended teleporting (through corners, over 2 block gaps) in general and will display warnings in the server log even on straight line teleports ("<playername> moved wrongly!"). It's some sort of cheat protection. I haven't found any instructions on disabling it anywhere.

I doubt this can be fixed easily.

**Comment by jrbudda** [comment]
is this still happening?
