### ISSUE TITLE
[Forge Mod] Applied Energistics 2 multiparts don't appear on client

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#65]
AE2 multiparts (the blocks which include things like cables, terminals, etc.) do not show up on the client at all. It's not that they don't render, they actually just aren't there. They still exist server-side though, as I can't place any other blocks in the position.

**Comment by jrbudda** [comment]
Could you dig thru the Game Output tab when you load it up? Almost certainly a error in there somewhere that would help. Put the whole thing on pastebin and copy link here. Thanks!

**Comment by Techjar** [comment]
Unfortunately I already did this and could not find anything of interest. I have the launcher set to close because otherwise it was logging me out every time I launched for some reason, but I'm looking at the log files. Here's the FML client log: https://gist.github.com/88f03cb8cbe6578ef133a9f7261c671b

**Comment by Techjar** [comment]
Forge Multipart blocks are doing the same thing. They exist only on the server, nothing appears at all on the client.

**Comment by Techjar** [comment]
I've dug through quite a bit of the patched code and I'm having trouble even comprehending what's going on here. There's no error or log output of any kind, the blocks just don't show up. The client seems to recognize "something" there, as I can't teleport to the position, but I don't get any visual indication of a block being there, such as the selection outline. This makes absolutely no sense. As far as I can tell, Vivecraft doesn't even touch any code relating to blocks or TileEntities, so I can't understand why it's breaking multiparts.

**Comment by jrbudda** [comment]
Welcome to my world.

If I had to guess it's something in EntityRenderer not being properly made to do what Forge does. Or renderhelper or one of those.

**Comment by Techjar** [comment]
Well there's no patches to RenderHelper, so it's not that class. I'll dig through the EntityRenderer code, but I don't see how that would affect it as I thought that was just for rendering entities, not static blocks in the world that get cached to a VBO.

EDIT: Why the fuck is the world being rendered from a class called EntityRenderer!? Who wrote this code!? Oh, right... Wait, nevermind, maybe this just renders the entities and other dynamic stuff in the world. ...Nope, it handles all the world rendering, though it's not the part actually caching the block renders, it just calls the subroutine which renders those.

**Comment by Techjar** [comment]
I might be onto something, I discovered that WorldRenderer is being patched by Vivecraft, but the patch does absolutely nothing. Not sure why it's there, but I'm going to try deleting it so Forge will runtime patch the class. Will report back soon.

**Comment by Techjar** [comment]
Okay, the patch doesn't exactly do nothing, it applies a few small changes. I can probably turn these changes into a ClassTransformer and avoid the diff patch entirely, if necessary. I need to look further into what it's actually doing.

**Comment by jrbudda** [comment]
Update your local copy, I removed the patch to worldrenderer along with a number of other ones that weren't getting deleted from github.

I cannot tell you how many times I've wanted to move or rename something sensibly and been forced not to because 'Forge'. It's a nightmare.

**Comment by Techjar** [comment]
Well when I deleted the WorldRenderer patch it wouldn't compile anymore. I looked into it though and it appears to be related to optifine compatibility, specifically with the fast render option.

EDIT: Oh, I think there's a misunderstanding here. I have the latest copy. The file I'm referring to is in the mcppatches directory.

**Comment by Techjar** [comment]
Okay, well it turns out that WorldRenderer is being patched with reflection methods Forge, so that's not the issue. Will keep digging through code and report back when I find anything else.

**Comment by jrbudda** [comment]
Where are you seeing the patch for woldrenderer?

**Comment by jrbudda** [comment]
I believe mcpatches is only used when you install the thing. The patches generated by getchanges.py and used in the build are in in just /patches

**Comment by Techjar** [comment]
That may be true, but that means those patches still apply to the build. But it doesn't matter anyways since the forge compatibility is already there (though I'm not sure where it's coming from). Where does the bulk of Reflector.java come from, anyways?

**Comment by jrbudda** [comment]
Let me sync that folder again. There should be no patch to worldrenderer applied.

I have not touched Reflector. I assume that started as an Optifine file to support Forge and MinecRift used it to extended Forge support to the new files it modified.

**Comment by Techjar** [comment]
Ah, of course! OptiFine is installed along with MCP and everything else, so it's changes appear in the mcp/src drecitory. That's where the Reflector class is coming from. Anyways, WorldRenderer isn't the issue, so I'll keep looking for missing Forge stuff.

P.S. Don't touch the contents of mcppatches. The install failed when I tried deleting WorldRenderer.java.patch, thinking it was the problem. It seems to contain important patches necessary to get MCP to compile. I think it has to do with the OptiFine compatibility.

**Comment by Techjar** [comment]
Well, I've dug through a lot of code, and I have not even the slightest clue as to what's going on here. I put in some debug code (read: log spam), and both the block and TileEntity exist on the client world, but the block behaves as air.

**Comment by fucnknown** [comment]
Techjar,  just an idea, how about contacting thatslch at https://github.com/AppliedEnergistics/Applied-Energistics-2 his latest commit was a month ago so we know he is active, he might have some helpful input.

**Comment by Techjar** [comment]
Yeah, I'll try that, but none of the AE2 devs have been around IRC much lately.

**Comment by Techjar** [comment]
The plot thickens: Forge Multipart stuff appears in a multiplayer server, but not in singleplayer. AE2 multiparts are broken in both cases.

**Comment by Techjar** [comment]
Okay, with the latest changes for the head orientation stuff, Forge Multiparts now appear in singleplayer. AE multiparts are still broken. Additionally, breaking Forge Multiparts breaks the whole tile client side, not just the one part.

**Comment by Techjar** [comment]
I've been digging through more code, and I've realized that Forge adds a lot of more obscure stuff - stuff that you can't find by simply Ctrl-F'ing for "forge." I'm going to do some extensive work on Forge compatibility. It'll take some time (probably a few days a most, depending on how extensive it is), so try not to make any major changes to the patch files in the meantime. I basically have to start comparing Forge-ified source files to non-Forge-ified ones, find out what's missing, and either implement it or avoid patching the class altogether.

**Comment by jrbudda** [comment]
What I do is do a Compare in notepad++ on vanilla minecraft files vs the forge files of the same name. The set I have has obfuscation differences so there's a lot of false positives but it's usually easy to tell what's a significant change.

**Comment by jrbudda** [comment]
You could also just paste the forge file wholesale into the vivecraft project and see what breaks.

**Comment by Techjar** [comment]
Yeah I'm already using Notepad++ for editing so that works nicely. And yeah there's obfuscation differences on mine too. It'll just be a slow and arduous process. Luckily there's not too many files to check.

**Comment by Techjar** [comment]
I think I found the problem! Will report back soon...

**Comment by Techjar** [comment]
I've fixed it! The problem turned out to be a missing call to TileEntity.onDataPacket() (a method added by Forge) in the NetHandlerPlayClient class. I got a clue about what was going on when I noticed my mod (HexWool) wasn't loading it's tile data, since I use that method to load it on the client. I added the reflection code for it and it works now. I'm going to add the Forge reflection code to RenderItem to fix mod support there, then I'll make a PR.

**Comment by jrbudda** [comment]
Awesome! so it was NetHandlerPlayClient  after all! damn the diff's look so similar.

**Comment by Techjar** [comment]
Yeah this ended up being simpler to fix than I expected, after I figured out what was wrong. I'll still continue to work on Forge compatibility as I find issues, but so far everything I've tested works fine.

**Comment by jrbudda** [comment]
Do you think you'll have the PR ready tonight? I've just got the rest of my changes finalized for 19. I'll wait for you if it's going to be soon.

**Comment by Techjar** [comment]
Yeah I might have the PR ready soon, currently working on the RenderItem patch. Shouldn't take too long if my change works.

**Comment by jrbudda** [comment]
Awesome! Interested to see it, I haven't even looked at how to add new Forge reflection methods yet.

**Comment by jrbudda** [comment]
I'm gonna go thought Automat's commits and see if there's any other MC files he added without doing the Forge stuff. I think RenderItem is the only one that I've attempted to add.

**Comment by Techjar** [comment]
Yeah, I'm still working on the RenderItem patch. There's a few more Forge reflection things I need to add, so it might take a bit. I don't think there's much Forge stuff elsewhere.

**Comment by jrbudda** [comment]
Lot of unintended consequences to the look change thing, just had to fix sunsets, the sky color was changing based on how you moved your controller around, lol.

**Comment by Techjar** [comment]
Haha oops.

**Comment by Techjar** [comment]
Alright the RenderItem stuff is working with Forge now. I look and most of the changes are just some bugfix related stuff that probably doesn't matter much, so I just implemented the important parts that actually call the custom item renderers for now.

**Comment by Techjar** [comment]
Fixed in PR #82.

**Comment by jrbudda** [comment]
Thanks a ton, that's great work.

Next file that's going to need looking at is n.m.c.multiplayer.PlayerControllerMP. That was modified and not forgified.

ItemRenderer was also modified but I guess isn't causing any problems? I know a bunch of that gets overwritten by Optifines ItemRendereOF.java

**Comment by jrbudda** [comment]
Also what all mods does this fix that you know of? for the release notes.

**Comment by Techjar** [comment]
PlayerControllerMP is actually the class I had to modify to fix the first bug in the list, so that's taken care of. As for mods this fixes, probably a ton. Ones I know of are: AE2, Forge Multipart and HexWool (my mod). Basically V19 is going to make modded Vivecraft exponentially more playable.

**Comment by jrbudda** [comment]
Oh never mind me I just actually looked at the PR

**Comment by jrbudda** [comment]
You fixed Carpenterblocks too, that's gonna make a lot of people happy

**Comment by Techjar** [comment]
Yeah the TileEntity data thing probably fixes a plethora of mods, since onDataPacket() is the most common way to load tile data from the server. Same for Block.removedByPlayer() as basically all mods use that to change block breaking behavior.

**Comment by jrbudda** [comment]
You get top billing in the release notes.

**Comment by Techjar** [comment]
Haha thanks. :3

**Comment by Techjar** [comment]
Release title should be somehow related to the greatly improved Forge mod compatibility. Also do/can you use IRC? Because if so I have a great idea.
