### ISSUE TITLE
When placing things, momentarily change head orientation to where you point the right controller

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#66]
This could possibly fix a lot of issues with placing things that depend on head orientation, if it can be implemented. Note that I said where you point the controller, not the orientation of the controller itself, so you would need to calculate the angle between the pointer position and the player's (player model, not tracked) head position. You could also add a binding to trigger this behavior when held, to assist with placement of things like Forge Multipart parts, but leave it unbound by default.

**Comment by jrbudda** [comment]
What things are we talking about that depend on head orientation?

**Comment by Techjar** [comment]
Well, based on one of your other issues you opened, I'd guess lilypads and water buckets. A lot of mod things also depend on it, such as attaching BuildCraft gates to pipes. The gates place where I'm looking, not where I'm pointing. This also makes it tricky to right-click the gates, which is why I suggested adding a binding to also trigger this different behavior.

Basically, it's a slightly hacky possible solution to the head pos raytrace problem that doesn't require messing with Item.java. This would also have the added benefit of working on multiplayer servers, whereas changing the actual raytrace would only work for singleplayer.

**Comment by jrbudda** [comment]
Ah ok, the solution is to just update Items.java to use the correct source/direction. Doing so requires either some tricky ASM insertion or rewriting the whole java file with Forge reflection methods. That's the correct way, tho time consuming. Not gonna bother with a temporary hack. It'll get done eventually.

**Comment by Techjar** [comment]
Yes, but changing Item.java will not work for multiplayer, since the server is also doing checks on head orientation for block placement and interaction.

**Comment by jrbudda** [comment]
Does it? I was under the impression  that C08PacketPlayerBlockPlacement included the block x,y,z position provided by the client and it just used that without doing the raytacing again. Could be wrong.

**Comment by Techjar** [comment]
That may be true to vanilla stuff, but mods like Forge Multipart and BuildCraft are doing "sub-block placement." There are values in C08PacketPlayerBlockPlacement that handle sub-block coordinates, but I'm not entirely sure whether mods are using that or just doing a server-side raytrace.

If you insist on making the changes to Item.java, I would like it done sooner rather than later. If you're having trouble writing the ASM code for it or can't be bothered to do it right now, I know how to use the ASM library, so you could give me the changes that need to be made and I could try to write the ClassTransformer for it.

**Comment by Techjar** [comment]
(This appends my previous comment.) I looked into the code of the 2 aforementioned mods. Forge Multipart is using the sub-block coords passed in C08PacketPlayerBlockPlacement, therefore the Item.java changes would work for multiplayer. BuildCraft, however, is doing it's own raytrace in the item placement code, and therefore will still be dependent on head orientation. This means the Item.java changes will NOT work for multiplayer BuildCraft (or even singleplayer), and my solution or something similar is still necessary for it to be more usable.

My solution would make mods like BuildCraft more usable, and it would also act as a temporary solution to all other head pos raytrace issues until the Item.java changes are implemented. If you insist on not implementing this solution, an (albeit not quite as intuitive) alternative would be to add a binding that, when held, makes a marker render at the position you're looking at.

**Comment by jrbudda** [comment]
Item.java getMovingObjectPositionFromPlayer on line 760. First couple lines would have to change to use mc.lookaimcontroller.getAimSource(0) and mc.lookaimcontroller.getAimPitch/Yaw. Interpolation probably not needed.

I've never touched ASM before. Even the minecrift guys are only using it for 1 class. I would have preferred they did it all from the start or just built minecrift on top of Forge, this hybrid stuff is for the birds.

We tried doing the look override thing for correctly shooting the bow, had to send the head direction the entire time the bow was equipped, tried when just drawing the bow or just before firing but didn't work. I think the next lookmovepacket was getting processed before the arrow spawned or something.

**Comment by Techjar** [comment]
Alright, if the changes are that simple I could have that whipped up pretty easily. As for the look override thing, that's why I suggested putting it on a controller binding, so you can just hold the button down while you're trying to do the interaction. As I said, you can leave it unbound by default as it's only needed for mods.

**Comment by Techjar** [comment]
Are you going to implement the look override? As I said it's necessary for BuildCraft and probably some other mods to be reasonably usable, as they do stupid things with performing their own raytrace.

**Comment by jrbudda** [comment]
What would be the best condition under which to send the HMD direction instead of the controller? holding a block? I don't think 'as' you place it is going to work. The bow thing required sending it the whole time the bow was equipped.

**Comment by Techjar** [comment]
Well I actually meant to send the direction as the calculated angle between the MC head position and where the controller is pointing, which will make your MC head look where you're pointing. I suggested just adding it as a binding (unbound by default as it's only needed for mods), because there's a lot of random circumstances where you'd need to use it, ranging from placing certain items to right clicking certain blocks.

**Comment by jrbudda** [comment]
hmm.. would there be a downside to ALWAYS having the player look at the crosshair? except when trying to shoot/throw?

**Comment by Techjar** [comment]
Well, in multiplayer you'd have to point at a player to look at them, rather than just looking at them. That's not really a major concern though, since it's purely cosmetic. It would also make driving boats weird, but I think you could just have it go back to head orientation when in a vehicle, as you probably aren't going to be interacting with stuff while in a boat.

**Comment by jrbudda** [comment]
controller orientation would be best while riding, no? like free-move.

**Comment by Techjar** [comment]
Actually, yeah, that probably would be best. As a side note, could you possibly fix riding horses? My head is currently inside the horse.

**Comment by jrbudda** [comment]
Yea I'm not sure what to do there, someone mentioned this on reddit. I made it when you're riding it doesn't change your height, I didn't like the floor coming up to my chest. Was fine for boats and minecarts, horses ofc put you 'up'. Maybe I should just allow that.

**Comment by Techjar** [comment]
Could you allow it conditionally for horses?

**Comment by jrbudda** [comment]
Possibly, there was some serious server/client sync issues on minecarts with regards to player height. Have to dig back into that. to turn it back on at all.

**Comment by Techjar** [comment]
Well, no worry if you can't get that fixed for the next update. Not that worried about horses. The look override thing is pretty important though.

**Comment by jrbudda** [comment]
See if that does it. I've got no server to test with.

[vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip](https://github.com/jrbudda/minecrift/files/310105/vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip)

**Comment by Techjar** [comment]
Which change is this? The look override?

**Comment by jrbudda** [comment]
it should normally set the player look vector to look AT the crosshair, unless holding a bow, then it's using the bowtracker aim, also unless you're holding a thrown projectile or boat, in which case it's controller direction

**Comment by Techjar** [comment]
Okay, I'll do some testing and report back.

**Comment by jrbudda** [comment]
It's not sending the HMD direction at all anymore, tho if you're looking at your crosshair it should be similar.

**Comment by Techjar** [comment]
The look direction still seems to be tied to the HMD direction, as I still have to look directly at the BuildCraft gates to right-click them.

**Comment by jrbudda** [comment]
I dont suppose you can login twice and see what your player model is doing?

**Comment by jrbudda** [comment]
wait i screwed up

**Comment by jrbudda** [comment]
Assuming that was the issue...

[vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip](https://github.com/jrbudda/minecrift/files/310108/vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip)

**Comment by Techjar** [comment]
Well that didn't fix it, and I can't login to a server twice for obvious reasons.

**Comment by Techjar** [comment]
Okay, I had someone else join, and according to them my head is in a fixed orientation no matter which way I orient anything.

**Comment by jrbudda** [comment]
Ok so I think I've got it sorted. Was a bug in the crosshair origin that was totally screwing up the direction vector, leftover rminecrift code.
[vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip](https://github.com/jrbudda/minecrift/files/310139/vivecraft-1.7.10-Vivecraft-jrbudda19-installer.exe.zip)

**Comment by Techjar** [comment]
Ugh, unfortunately it still seems that the head orientation is tied to the HMD. I still have to look directly at the BC gates to click them.

**Comment by jrbudda** [comment]
Well I dunno then, could it be different under forge? I was testing on vanilla with water buckets which use that player raytrace, I could look away and still get it to spawn at the crosshair.

**Comment by Techjar** [comment]
Well, here's the code in BuildCraft that's doing it's own raytrace: https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/transport/BlockGenericPipe.java#L272

**Comment by jrbudda** [comment]
Before when your friend said your head was in a fixed orientation... was that orientation aiming at the gate? or could it be using something else?

**Comment by Techjar** [comment]
No, my head orientation was just some random angle that didn't change no matter how I rotated my head or the controllers, so yeah BC could be using something else, but I'm not sure what. It calls EntityPlayer.getLookVec()

**Comment by Techjar** [comment]
Did you change EntityLivingBase.getLook() to use the controller aim as well? I believe you didn't, because in multiplayer I can right-click on the gate and open the GUI as expected, without looking at it (though it doesn't show the outline). In singleplayer, I still have to look directly at the gate to open it's GUI.

**Comment by jrbudda** [comment]
Wasn't me, but it looks like entityLivingbase.getlook has been overidden to use the HMD. I have no idea why, there isn't even a check if its a entityplayer.

**Comment by Techjar** [comment]
Yeah, I noticed that. That's why I'm saying to change it to use the aim orientation, because this is the method BC uses.

**Comment by jrbudda** [comment]
I'm gonna revert that whole file to vanilla. There's no reason we should have to modify entitylivingbase for VR. That way it'll use the same look vector I pass to the server elsewhere.

**Comment by Techjar** [comment]
I wouldn't revert that, it looks like it contains stuff related to the "direction affects pitch while flying" setting. It already has all the Forge reflection code, so it's not breaking anything.

**Comment by jrbudda** [comment]
Too late. Every file I remove from distribution is one file I don't have to deal with porting this to a new Forge or Minecraft version someday.

**Comment by jrbudda** [comment]
I've also now completely taken Entity, EntityLivingBase and EntityPlayer out of Vivecraft. That gets rid of the one ASM patch we had. So try not to change anything in those 3 files anymore since they're the 3 shared by the server.

All the custom code is now in EntityPlayerSP and hopefully it sets up the look/move packets properly to keep the server in sync. Still tweaking things but this is totally the way to go. I did have to switch back to sending the left-Controller direction to the server while moving forward in freemove since that's what the server uses for MoveFlying()

**Comment by Techjar** [comment]
So I'm guessing the changes to those classes were pretty minimal and not necessary for Vivecraft to work correctly.

**Comment by jrbudda** [comment]
10% of it is necessary, but not necessary in those specific files. The other 90% was Forge compatibility code to make the other 10% possible.

**Comment by Techjar** [comment]
Yeah, I did notice almost all of the code was just Forge compatibility stuff.

**Comment by jrbudda** [comment]
It's like 'ok we need to add 3 lines of code to file X, which requires also adding 100 lines of code to make it Forge compatible' 'yea sounds like a great idea!'

Anyway with those files gone the singleplayer and multiplayer experience should be much more similar.

**Comment by Techjar** [comment]
Alright, awesome. Also I think honestly the best way to fix the RenderItem is to just add in the Forge compatibility code, rather than bothering with the ASM, since the ASM would require Forge to be installed.

**Comment by jrbudda** [comment]
Yup, gonna look into that.

**Comment by Techjar** [comment]
Can you push the changes so I can test it?

**Comment by jrbudda** [comment]
committed. might still be some bugs. Did not test at all with forge.

**Comment by Techjar** [comment]
Good news: it works perfectly now! I'm even able to interact with things I couldn't before even by looking directly at them. While I get that this isn't necessarily an optimal solution, it's the most compatible with mods and works without changing Item.java. Thanks!

**Comment by Techjar** [comment]
Hey jrbudda, do/can you use IRC? Because if so I have a great idea.

**Comment by jrbudda** [comment]
I'm been hanging out on the vivecraft and Vive discords https://discordapp.com/channels/178567952780623872/178567952780623872

**Comment by Techjar** [comment]
Oh, right, forgot about that. Well either way I created a #Vivecraft channel on EsperNet in case anyone wants to use IRC instead of discord. You can list it somewhere along with the discord link if you want.

Also there doesn't seem to be anyone in the Discord. Either that or I'm missing something, never actually used it before.
