### ISSUE TITLE
Emulate scroll wheel with right touchpad vertical axis when a GUI is open

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#67]
This would be nice so we don't have to grab and move the scrollbar with the pointer. It would also make it possible to scroll through chat using the controller.

**Comment by jrbudda** [comment]
It would be super nice and I've looked into it and it's like super impossible to do. The various GUI's in the game with scrollbars are all different and all listen directly to the mouse and I cannot simulate the mousewheel in java. I'd have to programmatically scroll the containers., but then you get Forge involved and it's all south from there.

**Comment by Techjar** [comment]
Ah, I see. I wasn't aware you couldn't just spew virtual "scroll wheel" inputs out like you are doing with the keyboard.

**Comment by jrbudda** [comment]
It might be possible to do it that way but it would come with the same need for the game window to have focus.

**Comment by Techjar** [comment]
That's fine, the game window already has to be in focus for typing to work, so I don't really see this as an issue.

**Comment by fucnknown** [comment]
Vote for that option too

**Comment by CoreyHyde** [comment]
I would like to add to this that when using CraftGuide (which would be super useful since I have to otherwise take off the headset to look up a recipe), grabbing and moving the scroll bar doesn't even work so that one's unusable so far.

**Comment by jrbudda** [comment]
Already done, look for it in v18.

**Comment by Techjar** [comment]
The vertical axis on the right touch pad is now also scrolling through the inventory, which makes placing things slightly tricky. Any way to make it so this functionality is only enabled when a GUI is open?

**Comment by jrbudda** [comment]
oooh... I guess the scrollwheel cycles the inventory too, doesnt it. unintentional. Yea will have to do a screen check.
