### ISSUE TITLE
Taking damage through blocks

### ISSUE THREAD

**Issue by puppet-head** [jrbudda/minecrift#7]
An odd one, a two block tunnel going straight forwards with nothing in sight but the lava sound playing, I teleport forward and start taking damage though the wall/floor/ceiling(?).

Anyone else seen this?

**Comment by jrbudda** [comment]
It's a bug in v6

**Comment by phiresky** [comment]
This also happens when under a block even with a free space of height three

**Comment by jrbudda** [comment]
test v7 please

**Comment by mnmean** [comment]
I'm still suffocating at 2 blocks, but only sometimes and in the same one-block space. I can walk down a hallway in free move mode and there will be one spot I take damage. I'm standing on my blue buddy and even tried ducking. Same behavior in both 1.6 and 1.7. Survival mode. 

As an added bonus, when I respawn, some of the blocks I've dug have been replaced.

I'm also running Optifine; I don't know if that would be a problem.

**Comment by fucnknown** [comment]
I think you might be having syncing issues, the blocks you think are gone, are still there. Try not to dig from too far

**Comment by mnmean** [comment]
That could well be the problem, but the game's not much fun having to keep track of that -- and I'm a miner more that a builder. 

Is there a way to limit the reach of my pickaxe so it won't pick so far as to cause problems?

**Comment by jrbudda** [comment]
Gonna have to look into if this is an actual anti-cheat mechanism or the mod is just doing something wrong. Are the invisible blocks  from breaking normally with r trigger or by smacking them? Is this singleplayer or multiplayer and if multiplayer what is the server running?

**Comment by mnmean** [comment]
Single-player, breaking the blocks with the trigger. What ziggy said about syncing only applies to multi-player? Because I like the theory of their being invisible blocks that weren't destroyed, because it would match up with what I'm experiencing. However, picking at the space where the block would be doesn't do anything but pick the next targeted block. 

Let me know what experiments you'd like me to run. I'd be happy to do them.

**Comment by jrbudda** [comment]
in single player there is still a 'server', it just runs alongside the client, but the game logic still has to communicate back and forth with it via packets so the opportunity exists fo de-sync... but it's most likely a bug and not a function of lag or anything since there should be no lag.

**Comment by puppet-head** [comment]
Just tried 8 and still have the same problem, but its definitely a missing blocks problem. 

I destroy the block, move forwards, take damage and move back, then sometimes where I was standing the block is back.  Also reloading shows blocks that weren't there when saved.

**Comment by mnmean** [comment]
Tried 7. I didn't do much digging, but I couldn't stand in negative tree space less than 4 without taking damage. I also popped into a 3-high cave and took damage wherever I went.

On to eight!

**Comment by mnmean** [comment]
No problems with the trees in 8... but still taking damage in dug tunnels. It _always_ happens in blocks that I've dug out at the very tip of my range, so at least we know that's a factor.

**Comment by jrbudda** [comment]
It's weird I've not experienced this, i test only single player. Are you installing with or without Forge?

**Comment by mnmean** [comment]
Without forge. 

I think I figured something out. I tried building out at the edge of my range with the controller at my waist. No problems. Then I tried extending my range by stretching out my arm and leaning forward a bit -- and that's what does it every time. I have long arms.

**Comment by jrbudda** [comment]
oh thats great feedback. See if you can still do it in v9, i put the reach back to defaults

**Comment by mnmean** [comment]
Fixed! Thanks! 

I guess it's hard to make your arms longer in order to troubleshoot. One of the many _fun_ things about VR.

**Comment by ArmEagle** [comment]
Indeed much better (well, plain fixed) in 9.

**Comment by jrbudda** [comment]
Gonna leave this open in case anyone else experiences it still. Plus I'd like to put the extended reach back , even it requires a modded server.

**Comment by ArmEagle** [comment]
The current reach doesn't feel limiting to me. But I can understand wanting a little bit more.
