### ISSUE TITLE
Inertia no longer affects stopping

### ISSUE THREAD

**Issue by Octavian-the-ent** [jrbudda/minecrift#70]
Inertia affects the time it takes to build up to full speed motion and slow down to a stop, but with the recent update all horizontal inertia is cancelled immediately upon letting go of the trigger. This is rather jarring, and the old method where you would somewhat gradually slow down to a stop was much more comfortable. I noticed that this only affects horizontal inertia, because when flying vertical inertia is still maintained.

**Comment by jrbudda** [comment]
as soon as you let go of the controller it's applying the 'roomscale' movement and teleporting your body under your head. Not entirely sure I can fix that.

**Comment by Octavian-the-ent** [comment]
Could you not just add in a small window after the trigger is released where speed decreases to 0, and then have the roomscale movement kick in? I really like the work you did for the roomscale movement, but for some reason the instant stopping is very uncomfortable for me. I might have to roll back the update.

**Comment by jrbudda** [comment]
What inertia setting are you on? I never even really noticed it

**Comment by Octavian-the-ent** [comment]
I use "A Lot" because as I said the near instant acceleration and deceleration on the normal setting is awful for me.

**Comment by jrbudda** [comment]
Test this. It may have unintended consequences when it comes to being moved by the game (knockback, running water, etc).

[vivecraft-1.7.10-Vivecraft-jrbudda18-installer.zip](https://github.com/jrbudda/minecrift/files/309648/vivecraft-1.7.10-Vivecraft-jrbudda18-installer.zip)

**Comment by Octavian-the-ent** [comment]
Wow dude! Works perfectly from what I can tell. You're a fantastic dev man.

**Comment by jrbudda** [comment]
When I fix seems too simple, I usually get suspicious. Let me know if any weird things happen.
