### ISSUE TITLE
Can't build due to patch errors

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#71]
I'm getting tons of random errors that don't make any sense (things like "illegal start of expression" in random method declarations) when trying to build this version of Vivecraft. The old version by Automat-GH builds just fine.

**Comment by jrbudda** [comment]
I just completely cleaned out the mcppatches folder and restored it to automats version. I'm tryin gto get that all sorted out, it's a mess.

**Comment by Techjar** [comment]
Okay, but I haven't pulled those changes. My local copy is still only up to the v18 commit. The install is spewing out errors when applying the mcppatches (though they don't seem to be harmful?).

**Comment by Techjar** [comment]
Ah, the patch to Minecraft.java is failing, which explains all the weird errors in that class specifically.

EDIT: Actually, all sorts of patches are failing. What the hell is going on here? I can run the install just fine, but I get all sorts of errors during the build.

**Comment by Techjar** [comment]
This is what I get when running applychanges.py, I truncated all the non-failed patches.

patching file net/minecraft/client/Minecraft.java
Hunk #7 FAILED at 1104.
1 out of 7 hunks FAILED -- saving rejects to file net/minecraft/client/Minecraft.jav#

patching file net/minecraft/network/NetHandlerPlayServer.java
Hunk #9 FAILED at 1179.
1 out of 10 hunks FAILED -- saving rejects to file net/minecraft/network/NetHandlerPla#

**Comment by jrbudda** [comment]
yea workin on it

**Comment by Techjar** [comment]
Yeah, I just noticed the commits coming in. That patch file is a bit of a beast.

**Comment by Techjar** [comment]
Minecraft.java patches now, but there's other failures.

patching file net/minecraft/client/renderer/ThreadDownloadImageData.java
Hunk #1 FAILED at 231.
1 out of 1 hunk FAILED -- saving rejects to file net/minecraft/client/renderer/ThreadDownloa#

patching file net/minecraft/network/PingResponseHandler.java
Hunk #1 FAILED at 30.
Hunk #2 FAILED at 92.
2 out of 2 hunks FAILED -- saving rejects to file net/minecraft/network/PingResponseH#

patching file net/minecraft/src/WrUpdateThread.java
Hunk #1 FAILED at 46.
Hunk #2 FAILED at 367.
Hunk #3 FAILED at 407.
Hunk #4 FAILED at 419.
Hunk #5 FAILED at 428.
5 out of 5 hunks FAILED -- saving rejects to file net/minecraft/src/WrUpdateThrea#

patching file net/minecraft/util/HttpUtil.java
Hunk #1 FAILED at 151.
1 out of 1 hunk FAILED -- saving rejects to file net/minecraft/util/HttpUtil.java#

**Comment by jrbudda** [comment]
huzzah i fixed it. just tested: download zip > extract > run install > run getchanges > run build > working .exe

**Comment by jrbudda** [comment]
gechanges step prolly not necessary

**Comment by Techjar** [comment]
Yeah I actually forked the repository and set yours as an upstream remote. I pulled the latest changes, and I'm currently getting the above errors when I run applychanges.py. However, it still builds successfully(?)

**Comment by jrbudda** [comment]
yup i dunno what those other ones are about

**Comment by Techjar** [comment]
Well, whatever. It builds now, so I can actually start messing with stuff to see if I can fix issue #65.

**Comment by jrbudda** [comment]
godspeed and godbless

**Comment by Techjar** [comment]
Haha, yeah I guess that's appropriate here.
