### ISSUE TITLE
Window is now flashing violently with mirror off

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#72]
Heh, the issues never end do they? It's flickering rapidly between "mirror is off" and the Mojang logo with a small image of the title screen background in the bottom left. Here's a quick recording (epilepsy warning): https://owncloud.techjargaming.com/index.php/s/qOOcA8EAaDUOBDW/raw

Additionally, the title screen background in VR flickers oddly.

**Comment by jrbudda** [comment]
Ah, shoulda checked mirror off mode when i did the render changes

**Comment by jrbudda** [comment]
Damnit there's something in GuiMainMenu that needs to change and I JUST reverted that file to stock. The fun never ends.

**Comment by Techjar** [comment]
Yeah you've got the easy part. I'm still here digging through code to track down that multipart render issue.

**Comment by Techjar** [comment]
Fixed in v19
