### ISSUE TITLE
Mod custom inventory renderers broken

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#73]
BuildCraft facades are all "missing texture", most AE2 stuff is invisible, and most amusingly all BuildCraft pipes are literally just flat pipe textures instead of being 3D objects. That's what I checked so far. Possibly related to the "icon transparency fix"?

Here's a screenshot of the BC pipes, it's pretty amusing.
![BC Pipes](https://qimg.techjargaming.com/i/577D6e1g.png)

**Comment by jrbudda** [comment]
Good way to test: in build.py look for a line where it ignores 'bee.class' and uncomment that line plus the one below it *just says continue).

That will exclude RenderItem from the build so you can test with stock Forge file.

**Comment by Techjar** [comment]
Nope, that didn't fix it. Checked the log and can confirm that the change worked, Forge isn't complaining about a descrepancy in bee.class

**Comment by Techjar** [comment]
This may give you a clue: it's not just inventory renders, it's also items dropped on the ground.

**Comment by Techjar** [comment]
Oh, you gave me the wrong line to edit. bee.class is actually GuiMainMenu.

**Comment by Techjar** [comment]
The renderers are working correctly after uncommenting the 2 lines above the one you referenced, so it's definitely caused by the RenderItem changes.

**Comment by jrbudda** [comment]
oh whoops! thats right, sorry
bny > boc

**Comment by jrbudda** [comment]
My changes to Renderitem are pretty minimal and would make a good ASM patch I guess

**Comment by Techjar** [comment]
Can you detail the changes? The patch file looks pretty extensive. I'll write that ClassTransformer at the same time as the one for Item.java. I'll work on that after I see if I can track down issue #65.

**Comment by jrbudda** [comment]
I need to go through it and see what I can boil the changes down to. I was mostly fumbling for a solution to the transparency thing and stopped when it 'worked'

**Comment by jrbudda** [comment]
And here's a dumb question maybe you know the answer to... The asm patches get applied by the tweaker which is loaded by FML. These modifications tho need to be applied for vanilla and Forge launches alike... How do we make that happen?

**Comment by Techjar** [comment]
Honestly, I have absolutely no idea. I vote we just tell people to install Forge and don't report any issues with a non-Forge install. It's far too much effort to maintain both Forge and vanilla client support. Unless you can somehow add functionality to the installer to conditionally include or exclude certain patched classes based on whether Forge is selected.

**Comment by PriestessOfEste** [comment]
I don't know if this is related or not, but tools created using Tinkers' Construct were invisible in v18. Unsure about v17, had skipped over it. If it isn't, I'll make a new issue.

**Comment by Techjar** [comment]
Yeah, that's because those tools use a custom item renderer, and the Vivecraft patch lacks the necessary Forge hooks for those to work.

**Comment by PriestessOfEste** [comment]
Lacks? As in has always been like that? Cause I can see them in v16 and earlier, same exact items and everything.

**Comment by Techjar** [comment]
Yes, that's because in v17 and earlier the patches to RenderItem were being excluded. They were added back in v18 after being fixed.

**Comment by Techjar** [comment]
Fixed in PR #82.
