### ISSUE TITLE
Replaced controller mapping still entering old input.

### ISSUE THREAD

**Issue by klave7** [jrbudda/minecrift#74]
New issue that I notice with this build. I previously had J mapped to my left-grip (for journeymap) then switched it to the new shift option with this latest release. Now when I press left-grip I get both inputs rather than just the one I changed it to.

**Comment by jrbudda** [comment]
Have you quit and reloaded the game since then?

**Comment by klave7** [comment]
I just reloaded the game and the issue was still there.  But when I reset to default and set it again it now works as expected.

**Comment by jrbudda** [comment]
Underlying bug should be fixed in v19.
