### ISSUE TITLE
WAILA mod does absolutely nothing

### ISSUE THREAD

**Issue by Octavian-the-ent** [jrbudda/minecrift#75]

**Comment by jrbudda** [comment]
I have never used this, could you explain what it is supposed to do? And are you playing single or multiplayer?

**Comment by Octavian-the-ent** [comment]
I'm playing single player. It basically just displays the name of whatever your crosshair is over, as well as the mod (if applicable) that it comes from. Very useful when you have mods that start adding a lot of new blocks and items and things. 

http://mods.curse.com/mc-mods/minecraft/waila

**Comment by jrbudda** [comment]
And is the block display wrong? or it doesnt show up at all? 2 very different problem on the code end.

**Comment by Octavian-the-ent** [comment]
It just doesn't display at all. It will work in the inventory GUI but it does nothing in-game.

**Comment by jrbudda** [comment]
If you go into the hud options and turn on 'menu backgound' (you should always have a black box over your left hand,) does the display show up there?

**Comment by Octavian-the-ent** [comment]
Turning on menu background only gives the black box when im in the game menu (the equivalent of ESC) Once I leave the game menu it goes away and the black box does not persist. The display did not work as well.

**Comment by Techjar** [comment]
Yeah I noticed this too. It's weird because Vivecraft still renders all the UI stuff in an orthographic projection matrix, just to a different framebuffer, then draws that framebuffer as a texture in world space. So, at least in theory, all 2D UI stuff should behave just fine; WAILA for some reason does not.

**Comment by jrbudda** [comment]
It depends on 'when' it draws it. If the mod is trying to grab 'frambuffermc' at the wrong time it may be trying to write to the 3d framebuffer instead. just speculation.

**Comment by Techjar** [comment]
I'll look into how WAILA is doing its rendering. Probably just some more missing Forge hooks.

**Comment by Techjar** [comment]
The problem seems to be that WAILA is using a RenderTickEvent handler which happens outside of Vivecraft's setup for the UI render-to-texture framebuffer, so it's just drawing to the screen directly, otherwise known as nowhere. Not sure how to fix this. Maybe we could just fire the RenderTickEvent from with the EntityRenderer class?

**Comment by jrbudda** [comment]
When is it fired now? Do you have a link to source?

**Comment by Techjar** [comment]
Before and after EntityRenderer.updateCameraAndRender(), for start and end phases respectively. I'm trying something probably dumb, will report back soon.

**Comment by jrbudda** [comment]
unless the mod specifically messes with the active framebuffer then it's always drawing to the 3d world framebuffer. If most mods are using that event to draw GUI elements we could fire it instead before and after entityRenderer.drawFramebuffer while guiFramebuffer is bound.

**Comment by Techjar** [comment]
Yeah, let me try that, might take a bit as EntityRenderer.java.patch is being stupid (as usual).

**Comment by jrbudda** [comment]
You shouldnt need to change entityrendere, just move the events up to line 1435 in minecraft.java before and after drawFramebuffer

**Comment by Techjar** [comment]
Ah, okay...

**Comment by jrbudda** [comment]
Not entirely sure what state those events expect the OpenGL matrix stack to be in. May have to manually set up ortho again, not sure if it's being popped off at the end of drawFramebuffer.

**Comment by Techjar** [comment]
Yeah, it's being popped off at the end. That might not be a problem though as a lot of mods are naively firing on both start and end, so leaving that alone will probably avoid double-rendering. Might be stupid but if it works who cares?

**Comment by Techjar** [comment]
Well, it sort of worked. The GL state isn't quite right, might have to insert it into drawFramebuffer() instead. How looks changes depending on the angle, it is attached to the controller though.
![image](https://qimg.techjargaming.com/i/J8mtDmbN.png)

**Comment by jrbudda** [comment]
try that
GL11.glPushMatrix
    GL11.glOrtho(0,displayWidth, displayHeight,0);
    Fire end render tick
GL11.glPopMatrix

**Comment by Techjar** [comment]
Yeah I have a different idea as the current way doesn't make any sense anyways. Give me just a bit.

**Comment by Techjar** [comment]
Okay, I've made a PR for the fix. Fully tested and working as far as I can tell. Let me know if anything explodes.

**Comment by jrbudda** [comment]
testing

https://gyazo.com/2387c08271bccc1b70022dca8adf4510

[vivecraft-1.7.10-Vivecraft-jrbudda20-installer.zip](https://github.com/jrbudda/minecrift/files/319244/vivecraft-1.7.10-Vivecraft-jrbudda20-installer.zip)

**Comment by Techjar** [comment]
The transparency is still broken. Not sure what's going on there. Maybe something to do with blend modes when we actually draw the UI texture in the world?

**Comment by jrbudda** [comment]
which transparency, it looked OK to me in that test build

**Comment by Techjar** [comment]
The WAILA UI itself has a slightly transparency (0.8) by default. Looks opaque here.

**Comment by jrbudda** [comment]
oh i had no idea, i dont think alpha blending is gonna be a thing for the projected UI. I think's its used for fully transparent sections because of the cursor issues.
