### ISSUE TITLE
Unintentional Scrollwheel Item Switchting

### ISSUE THREAD

**Issue by possi** [jrbudda/minecrift#76]
The right Touchpad Scrollwheel is a nice neat thing, but it happens to me that it accidental changes the item while holding the thumb on the touchpad to place multiple blocks. Even with trying to keep the thumb center as good as I can, it sometime switches.
Seems like it only measures movement without any time or such. Can you please check that it doesn't happen while just trying to click the touchpad multiple times :)

**Comment by jrbudda** [comment]
Yea unintended and already fixed for next build. In normal minecraft mousewheel cycles inventory.

**Comment by possi** [comment]
Which isn't a bad thing. Seems about right to me to switch the tool in my right hand with my right hand :D
But it shouldn't go wild. Thanks in advanced :)

**Comment by jrbudda** [comment]
Nah turning off the scrollwheel thing unless a menu is up. item switch stays on left hand

**Comment by jrbudda** [comment]
fixed in v19
