### ISSUE TITLE
[Trivial] Iron Axe seems to appear to small in hand

### ISSUE THREAD

**Issue by possi** [jrbudda/minecrift#77]
While the sword looks ok, the Axe appears to me like a toy.

PS. Wouldn't it be cool if those tools (and may the sword also) do a swing animation like in original. Not just this poke-thing?

**Comment by jrbudda** [comment]
the scaling is all the same isnt it?

The animation is totally up for changing, whats there is a quick and dirty replacement for VR. I got someone messaged me on reddit about fixing up combat a little, maybe he has some ideas.

**Comment by possi** [comment]
Yeah I assumed that its all the same. But subjective it looks wrong to me. Nevermind. Not important at all ;)
