### ISSUE TITLE
[Forge Mod] Thaumcraft - Unable to move inside research window

### ISSUE THREAD

**Issue by kuar-z** [jrbudda/minecrift#78]
Since v17 unable to move the screen inside the Thauminomicon window. I reverted to v16 and verified it works there. I also know it was broken with the base Automat-GH code.

Typically this is a click-and-hold type movement to navigate the window so I'm not sure why your recent changes have messed with it.

**Comment by jrbudda** [comment]
I may ultimately have to un-do all the controller-mouse code and use the simulated mouse clicks like I am for the scrollwheel. It requires the game window to have focus but It's gonna be the only way to be compatible with all these mods.

**Comment by jrbudda** [comment]
try with v23 with the game window in focus.

**Comment by kuar-z** [comment]
Resolved by v23.
