### ISSUE TITLE
[Forge Mod] Tinker's Construct Smeltery Crashes Client

### ISSUE THREAD

**Issue by kuar-z** [jrbudda/minecrift#79]
Crash log: http://pastebin.com/c9NN9nkT
Crash occurs when trying to open smeltery controller while liquids are present.

**Comment by Techjar** [comment]
Are you sure this is caused by Vivecraft? Does it not happen with a normal Forge client?

**Comment by kuar-z** [comment]
Yes, in fact there was another person on the server with just Forge and they were able to interact just fine.

**Comment by Techjar** [comment]
Yeah, well, I'm not really sure what's going on here. It's a mismatch of inventory size between client and server. I'm still looking into another obscure issue, maybe they are related. I'll give you an update when I've found and fixed that issue.

**Comment by jrbudda** [comment]
Total guess is the issue is NetHandlerPlayClient. Automat put his custom packet for checking if the server supports Vive in there and did not do any Forge compatibility additions. That may be the origin of a lot of our problems.

**Comment by jrbudda** [comment]
I take it back, they're almost identical.

**Comment by Techjar** [comment]
Yeah, the only Forge stuff in there is a bug fix for XP orb spawn positions and some chat message event.

**Comment by jrbudda** [comment]
Check with v19 please :)

**Comment by kuar-z** [comment]
Fixed. Big props to Techjar.

**Comment by Techjar** [comment]
Yeah seems that the tile data nonsense has fixed a ton of stuff. Awesome!
