### ISSUE TITLE
Manual enable for servers

### ISSUE THREAD

**Issue by HexaCubist** [jrbudda/minecrift#8]
Being able to manually enable teleport on servers in the options would be great as I have created a Minecraft VR server, however because it runs on 1.9 to support a bunch of plugins, but is backwards compatible using https://www.spigotmc.org/resources/protocolsupport.7201/

Sadly this setup does not support sending custom protocol packets easily, and the developer who makes the plugin which tells your mod that it's okay to use VR won't work. If there was either a manual setting on the client side or a message that I could send over the chat on join, then nice non-motion sickness movement would work awesomely.

**Comment by jrbudda** [comment]
I think the simplest solution is an option for default locomotion mode for each client.

**Comment by HexaCubist** [comment]
Agreed

**Comment by fucnknown** [comment]
Server setup added in the wiki https://www.reddit.com/r/Vive/wiki/minecrift_for_vive

**Comment by jrbudda** [comment]
You can now set your client to default to free move.
