### ISSUE TITLE
Stuttering with forge

### ISSUE THREAD

**Issue by rxstud2011** [jrbudda/minecrift#80]
I just starting installing with forge tick to play pixelmon. Even with no mods installed it stutters/jitters. Really nauseating. This only happens with forge, if I play the non-forge versions it works perfectly.

**Comment by fucnknown** [comment]
Have you tried the recommendations on the wiki to reduce stuttering? 
https://www.reddit.com/r/Vive/wiki/minecrift_for_vive

**Comment by rxstud2011** [comment]
I did and non of it helped. I'm also running Windows 10 64 on a SSD, AMD FX 8350 8 core, GTX 1080.

**Comment by fazo96** [comment]
check wether the game has enough ram and wether it stutters with forge but without the vivecraft mod.

**Comment by OscarHalse** [comment]
NOT RELATED TO THE ISSUE:

Hey rx I noticed you have a 1080 and a FX 8350. You may be aware, and plan to fix this soon, but I tell you just in case. You have a serious bottleneck with your CPU, I would highly encurage you upgrade. You could wait for Zen, but no longer as that CPU not on par with that GPU.

**Comment by rxstud2011** [comment]
I increased the ram to 10gb since I have 16. I will try forge non vive tonight. Also, the amd zen would require a new mobo since its amd 4. What good upgrades would you recommend that wouldn't require a new mobo?

**Comment by jrbudda** [comment]
With the latest version you have the option to turn the render target scale all the way down to 0.5x. Do that and turn off FSAA and set graphics to fast and that will for sure take the GPU out of the equation. If it's still bad I would play with the chunk loading settings found in the various video options screens as it's almost certainly related to disk activity at that point.

**Comment by rxstud2011** [comment]
I will try tonight when I get home. You are the best, keep the mod alive!

**Comment by jrbudda** [comment]
It's as fixed as it's going to get for now.
