### ISSUE TITLE
Illegal stance

### ISSUE THREAD

**Issue by Techjar** [jrbudda/minecrift#81]
With the recent changes for the head roientation, I'm getting kicked from servers now for "Illegal stance." This is obviously an issue as it affects both vanilla and Forge servers, the former of which cannot be patched to remove the stance check. The illegal stance is: 1.7999999523162842. I believe it has something to do with the head height stuff. Might we implement a check to only send that when in singleplayer (or possibly add some packet crap to detect if the server supports it)?

**Comment by jrbudda** [comment]
Yea I was wondering about that. I think Possi put a thing in to remove the checks in his plugin. If you turn off 'allow crawling' does it go away?

**Comment by Techjar** [comment]
I don't think Possi put anything to remove the checks in his plugin, since that requires modifying base code, which you can't do with the Bukkit API. I already had allow crawling disabled so that doesn't fix it.

**Comment by jrbudda** [comment]
Alright looks like a float rounding error then, will take a stab at it.

**Comment by jrbudda** [comment]
check v19, I actually turned the check back ON in the local copy just to make sure so I think it's ok. It shouldnt send illegal stances anymore.

**Comment by Techjar** [comment]
Yeah I tested the latest changes already and I'm not getting illegal stances anymore.
