### ISSUE TITLE
v19 crashes at launch

### ISSUE THREAD

**Issue by OscarHalse** [jrbudda/minecrift#85]
So downloaded and installed the new version, it crashes at launch. 

Report file without Forge: 
[crash-2016-06-13_16.33.02-client.txt](https://github.com/jrbudda/minecrift/files/312011/crash-2016-06-13_16.33.02-client.txt)

Report file with Forge:
[crash-2016-06-13_16.23.12-client.txt](https://github.com/jrbudda/minecrift/files/312007/crash-2016-06-13_16.23.12-client.txt)

Have also tried rebooting the vive, re-installing all USB drivers, rebooting PC.

**Comment by denny99** [comment]
I had the same issue, i removed my whole minecraft folder (withoud mods and config) and reinstalled forge+vivecraft.

**Comment by OscarHalse** [comment]
Eyy dude, that actually worked. Strange for it to happen in the first place though

**Comment by jrbudda** [comment]
try with v19r1 i think I fixed it. Assuming you can reproduce. It's something to do with shaders.
