### ISSUE TITLE
v19 crashes when equipping the bow

### ISSUE THREAD

**Issue by fazo96** [jrbudda/minecrift#86]
How to reproduce:
- equip bow (I only tried in survival)

By the way the new downsampling makes the game look amazing.

**Comment by possi** [comment]
+1 even without forge

MP: http://pastebin.com/6AUG4JJN
SP, no Resourcepack:: http://pastebin.com/x6JJc6eK

**Comment by jrbudda** [comment]
workin on it.

**Comment by jrbudda** [comment]
try with v19r1 plz

**Comment by fazo96** [comment]
It works, thanks for the quick fix!
