### ISSUE TITLE
v19r1 Right display seems dimmed?

### ISSUE THREAD

**Issue by kuar-z** [jrbudda/minecrift#88]
v19r1: http://i.imgur.com/Bkd1cQq.png
v19: https://i.imgur.com/figTvNz.png

**Comment by jrbudda** [comment]
Weird I don't get that at all. What version/mods are you running?

**Comment by kuar-z** [comment]
Eh, must be some mod freaking out. Clean folder with just forge on v19r1 is fine. I'll see if I can pin down which mod.

**Comment by jrbudda** [comment]
Sounds like a mod isnt cleaning up after itsself when doing OpenGL There's probably something I should be resetting between eye renders. If you can pin down the mod I can fix it.

**Comment by OscarHalse** [comment]
This happens to me as well while in menues, in game it stops. Only mods I use is treecapitor. It's very strange, but completely manageable. However I do believe you should maybe look into it :p

**Comment by jrbudda** [comment]
Confirmed caused by bspkrsCore all by itself.
