### ISSUE TITLE
Transparent textures in the Nether only render transparent for one eye

### ISSUE THREAD

**Issue by thesambassador** [jrbudda/minecrift#90]
When in the nether, transparent textures (mushrooms, flames on top of tiles, etc) have their transparent parts only rendering correctly in one eye.  

http://imgur.com/tHmBqPo 

Just went into the Nether today, just base Minecraft + running the Vivecraft installer, no mods.  I am running a multiplayer server and both of us saw the issue.  

When I exited the nether, fire didn't have the problem in the "normal" world.  Mushrooms were fine there as well.  The problem only happens in the Nether.

**Comment by jrbudda** [comment]
is this with v20 that I just put out?

**Comment by Konbonix** [comment]
It's on V19 for me.

**Comment by thesambassador** [comment]
It was with v19, I'll try v20.

**Comment by thesambassador** [comment]
Problem still happens at v20.

**Comment by jrbudda** [comment]
OK thanks, i'll look into it

**Comment by thesambassador** [comment]
I do have a custom texture pack (chroma hills) in the screenshot but my friend without any texture pack also saw it.

**Comment by jrbudda** [comment]
yea the one-eye thing is a giveaway something isnt happening correctly with alpha testing.

**Comment by jrbudda** [comment]
O this is fixed in 21
