### ISSUE TITLE
[Forge Mod] terrafirmacraft issues

### ISSUE THREAD

**Issue by fuelfuel** [jrbudda/minecrift#91]
There are two issues i found with this mod 
1. The health, thirst, and hunger bar doesn't show up on the HUD. It looks as if its in creative mode. I tried with and without a texturepack. Other then that, if you could somehow fix the HUD the mod should be playable. Unless I'm missing something 
2. I tried setting up a vive server for terrafirmacraft and i ran into a weird problem.
   I followed the guide on the vive wiki, i also added the additional library files from the thermos page. Server boots up fine and generates the world and etc. But as soon as someone attempts to connect (wether or not they have the mod or not) it crashes the server. 

It works fine without the mod installed 

This is the crash log

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 6/14/16 10:12 PM
Description: Exception in server tick loop

java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayerMP.func_71127_g()V @76: getfield
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @76
    flags: { }
    locals: { 'net/minecraft/entity/player/EntityPlayerMP', integer, 'net/minecraft/item/ItemStack', 'net/minecraft/network/Packet' }
    stack: { }
  Bytecode:
    0x0000000: 2ab7 0268 033c 1b2a b402 6cb6 0271 a200
    0x0000010: 4b2a b402 6c1b b602 754d 2cc7 0006 a700
    0x0000020: 352c b402 7a9d 000c 2ab4 026c 1b01 b602
    0x0000030: 7e2c b602 82b6 0287 9900 1b2c b602 82c0
    0x0000040: 0289 2c2a b401 8e2a b602 8d4e b401 eb2d
    0x0000050: b601 f684 0101 a7ff b02a b602 902a b400
    0x0000060: 7b95 9a00 292a b400 7e2a b402 94b6 0299
    0x0000070: a000 1b2a b402 94b6 029c 0b95 9a00 0704
    0x0000080: a700 0403 2ab4 0080 9f00 4e2a b401 ebbb
    0x0000090: 029e 592a b601 3cb6 02a1 2ab4 0294 b602
    0x00000a0: 992a b402 94b6 029c b702 a4b6 01f6 2a2a
    0x00000b0: b602 90b5 007b 2a2a b402 94b6 0299 b500
    0x00000c0: 7e2a 2ab4 0294 b602 9c0b 959a 0007 04a7
    0x00000d0: 0004 03b5 0080 2ab6 0290 2ab6 02a7 622a
    0x00000e0: b400 7895 9900 282a 2ab6 0290 2ab6 02a7
    0x00000f0: 62b5 0078 2ab4 018e b602 aab6 02b0 b202
    0x0000100: b62a b600 fa2a b802 bcb6 02c2 2ab4 0104
    0x0000110: 2ab6 0102 8d97 9900 0a2a b601 3cb6 02c5
    0x0000120: 2ab4 02c8 2ab4 0082 9f00 252a 2ab4 02c8
    0x0000130: b500 822a b401 ebbb 02ca 592a b402 cd2a
    0x0000140: b402 c82a b402 d0b7 02d3 b601 f62a b402
    0x0000150: d610 1470 0868 9a00 142a b602 dab2 02e0
    0x0000160: b602 e69a 0007 2ab6 02e9 2ab4 02ec 02a0
    0x0000170: 000b 2a2a b402 d0b5 02ec 2ab4 02ec 2ab4
    0x0000180: 02d0 9f00 222a b401 8eb6 02aa 2ab6 02f0
    0x0000190: 2ab4 02ec 2ab4 02d0 b802 f657 2a2a b402
    0x00001a0: d0b5 02ec a700 224c 2b13 02f8 b802 fe4d
    0x00001b0: 2c13 0300 b603 044e 2a2d b603 08bb 030a
    0x00001c0: 592c b703 0dbf b1  
  Exception Handler Table:
    bci [0, 420] => handler: 423
  Stackmap Table:
    append_frame(@6,Integer)
    append_frame(@33,Object[#631])
    same_frame(@49)
    chop_frame(@83,1)
    chop_frame(@89,1)
    same_frame(@131)
    same_locals_1_stack_item_frame(@132,Integer)
    same_frame(@139)
    same_locals_1_stack_item_extended(@210,Object[#2])
    full_frame(@211,{Object[#2]},{Object[#2],Integer})
    same_frame(@214)
    same_frame(@268)
    same_frame(@288)
    same_frame(@333)
    same_frame(@362)
    same_frame(@378)
    same_frame(@420)
    same_locals_1_stack_item_frame(@423,Object[#614])
    same_frame(@454)

```
at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:535)
at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:128)
at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:68)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:248)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
at java.lang.Thread.run(Unknown Source)
```
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Thermos Version: cyberdynecc:Thermos:1.7.10-1614.UNOFFICIAL
    Plugins: 
    Disabled Plugins: 
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 93838216 bytes (89 MB) / 259522560 bytes (247 MB) up to 259522560 bytes (247 MB)
    JVM Flags: 2 total; -XX:PermSize=128m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 17
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](Thermos-1.7.10-1614-Vivecraft-server.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](Thermos-1.7.10-1614-Vivecraft-server.jar) 
    UCHIJAAAA   kimagine{0.2} [KImagine](minecraft.jar) 
    UCHIJAAAA   tfc_coremod{0.79.28} [TFC[coremod]](minecraft.jar) 
    UCHIJAAAA   terrafirmacraft{0.79.28} [TerraFirmaCraft]([1.7.10]TerraFirmaCraft-0.79.28.908.jar) 
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by jrbudda** [comment]
#1 is being looked in to.

#2 is a conflict between terrafirmacraft and the server mod, you should post the issue to the author as I don't write it.

**Comment by fuelfuel** [comment]
Yeah i figured #2 was a issue with with thermos, as it works fine with forge server, but no vive mod :(

Is there a way to get the vive mod to work with the forge server, without spigot and etc (thermos)?

**Comment by jrbudda** [comment]
is this still happening with 21?

**Comment by denny99** [comment]
Tested with 23. And yes bars are still invisible. TFC must do something really strange.

**Comment by jrbudda** [comment]
Happy Birthday to this github issue!

**Comment by jrbudda** [comment]
[vivecraft-1.7.10-jrbudda-39finalr1-installer.exe.zip](https://github.com/jrbudda/minecrift/files/1076852/vivecraft-1.7.10-jrbudda-39finalr1-installer.exe.zip)
