### ISSUE TITLE
Minecarts don't work

### ISSUE THREAD

**Issue by Roncarlos** [jrbudda/minecrift#93]
Every time i'm trying to go in minecart, he disappear.

**Comment by jrbudda** [comment]
Forge or no Forge? Single player or multiplayer?

**Comment by Roncarlos** [comment]
Forge, solo.

**Comment by jrbudda** [comment]
Try with v21 please. Also try without Forge if it's still happening.

**Comment by Roncarlos** [comment]
It works now ! Thanks !
