### ISSUE TITLE
Achievement screen with mods overlapping

### ISSUE THREAD

**Issue by Caerdaryth** [jrbudda/minecrift#94]
The achievement screen is showing all the achievements for all loaded mods in one overlapping mess.

Noticed when I had a lot of mods loaded, then checked with just buildcraft loaded.  Same overlap problem.

http://imgur.com/a/hqEYj

**Comment by Techjar** [comment]
How does it look running normal Forge without Vivecraft?

**Comment by Caerdaryth** [comment]
I have added 2 pictures to album of how it looks on normal forge without vivecraft.
http://imgur.com/a/hqEYj

The button on the bottom left switches between the achievements for different mods (ie. Buildcraft, Applied Energistics, etc.).  In Vivecraft the button is not there, and all the achievements from the mods are displayed on one screen overlapping each other..

Edit - having this problem on Vivecraft v21 thru v24. Haven't tried earlier versions.

**Comment by Techjar** [comment]
I'll need to see if there's anything funny going on in the achievements GUI code.

**Comment by Techjar** [comment]
What the hell are we even doing in GUIAchievements? It looks like 100% Forge compatibility code (that probably doesn't work correctly). I'm going to delete this and see what happens.

**Comment by Techjar** [comment]
Here, can you test this build?

[vivecraft-1.7.10-Vivecraft-jrbudda24-test1-installer.exe](https://owncloud.techjargaming.com/index.php/s/hJPStbNLYWMlcdj/download)

**Comment by Caerdaryth** [comment]
That fixed it.  Thank you very much.

**Comment by Techjar** [comment]
Awesome! Fix is in PR #152
