### ISSUE TITLE
[Wishlist] Update minecraft version

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#96]
Step one: Pick a version. [Started a google sheet](https://docs.google.com/spreadsheets/d/1XpNmL3jWwAaunhDPgPzCcE-OaHbHXqMSE-VCBc8GKiE/edit?usp=sharing)
- What are current status of MCP, Forge, Optifine, Spigot, Thermos, popular mods, for more modern versions? What's consensus on best version for long term?
- How does version impact implementing custom server?
- Should we stick with vanilla codebase and Forge reflection or build straight into Forge codebase?

Step two: Nail down build process: 
- Before doing anything make sure we can build a working installer with minimal test changes to base.

Step three: Identify major gameplay changes.
- What has changed that significantly impacts VR gameplay implementation.. dual wielding?

Step four: Identify major rendering changes
- What has changed in the rendering pipeline that may invalidate 1.7.10 rendering methods.

Step five: Implement
- Minecraft.java and EntityRenderer.java will be the hardest, everything else should be routine, barring any changes identified in step three.

**Comment by Pixeldk** [comment]
Will update when i get time. But modded server is running.

Modified thermos made for vivecraft.

Personally think we need to go directly into forge. Forge got alot of things going for it that spigot cant handle. Main thing i would like to see, as its the question i get the most from new players joining. A way other players can see how you hold you hands. Being able to wave to others is a small thing, that makes all the difference.
Second, and a tie with the first, proximity chat! Its working on my server, and when playing on other servers i really miss this function.

Would say.

Go for forge.
Moving multiplayer limbs.
Incorporated voicechat.

Everyone in the mc community would talk about this budda :-)

**Comment by Techjar** [comment]
Yeah, honestly, in the long run it's better if we just re-implement Vivecraft as a Forge coremod. It will be a lot of work, especially Minecraft.java and EntityRenderer.java, but it will be much more compatible. Mind you, compatibility issues with other coremods modifying the same classes will still be a thing, but that should be obvious. We can talk to those devs about implementing support for Vivecraft when the time comes.

**Comment by jrbudda** [comment]
Current plan is to do vanilla Minecraft 1.10 when MCP is available. Forge support to be added (much) later when majority of mods have updated (likely never)

**Comment by asaf400** [comment]
I've updated the sheet to include more popular mods, as well as the compatibility list with Vive.

jrbudda, You're are awesome, keep up the good work!

**Comment by jrbudda** [comment]
Oh hello. Goodbye.
