### ISSUE TITLE
Achievement screen stuck

### ISSUE THREAD

**Issue by benk3i** [jrbudda/minecrift#98]
Hi,

I can only zoom in and out the achievement screen. I can scroll on the computer using a mouse, but not with the vive controllers.

Is it me just not finding the right button to scroll? Since I am new to Minecraft, I am using this quite a lot so right now I take of my headset each time and sit in front of the computer to figure out how to build stuff.

**Comment by kuar-z** [comment]
Going with my gut here but I suspect this is the same problem as #78

**Comment by benk3i** [comment]
Right you are! 

Good to know it's not just me then :)

**Comment by jrbudda** [comment]
try with v23 please.

**Comment by jrbudda** [comment]
should be fixed
